### ISSUE TITLE
esptool overlap error

### ISSUE THREAD

**Issue by svireli** [SmingHub/Sming#1002]
Hi
i'm using sming with docker and just compiling HttpServer_WebSockets, but esptool throws error.
I have not changed anything in example.

`/opt/esp-open-sdk/esptool/esptool.py -p /dev/ttyUSB0 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x00000 out/firmware/0x00000.bin 0x0a000 out/firmware/0x0a000.bin  0xB000 out/firmware/spiff_rom.bin`
`WARNING: Flash size arguments in megabits like '4m' are deprecated.
Please use the equivalent size '512KB'.`
`Megabit arguments may be removed in a future release.`
`usage: esptool write_flash [-h] [--flash_freq {40m,26m,20m,80m}]`
                           `[--flash_mode {qio,qout,dio,dout}]`
                          ` [--flash_size FLASH_SIZE] [--ucIsHspi]`
                           `[--ucIsLegacy] [--no-progress] [--verify]`
                           `[--compress | --no-compress]`
                           `<address> <filename> [<address> <filename> ...]`
`esptool write_flash: error: argument <address> <filename>: Detected overlap at address: 0xb000 for file: out/firmware/spiff_rom.bin`
`/workspace/Sming/Sming/Makefile-project.mk:449: recipe for target 'flash' failed
make: *** [flash] Error 2`

**Comment by slaff** [comment]
Thanks for reporting this. 

It seems that Alpine's stat does not support printf=% options. 

```
stat: unrecognized option: printf=%s
BusyBox v1.24.2 (2016-11-01 12:56:05 GMT) multi-call binary.

Usage: stat [OPTIONS] FILE...

Display file (default) or filesystem status

        -c fmt  Use the specified format
        -f      Display filesystem status
        -L      Follow links
        -t      Display info in terse form

Valid format sequences for files:
 %a     Access rights in octal
 %A     Access rights in human readable form
 %b     Number of blocks allocated (see %B)
 %B     The size in bytes of each block reported by %b
 %d     Device number in decimal
 %D     Device number in hex
 %f     Raw mode in hex
 %F     File type
 %g     Group ID of owner
 %G     Group name of owner
 %h     Number of hard links
 %i     Inode number
 %n     File name
 %N     File name, with -> TARGET if symlink
 %o     I/O block size
 %s     Total size, in bytes
 %t     Major device type in hex
 %T     Minor device type in hex
 %u     User ID of owner
 %U     User name of owner
 %x     Time of last access
 %X     Time of last access as seconds since Epoch
 %y     Time of last modification
 %Y     Time of last modification as seconds since Epoch
 %z     Time of last change
 %Z     Time of last change as seconds since Epoch
```
