### ISSUE TITLE
Automated (CI) builds failing for SDK_VERSION=2.0.0

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1008]
Submitting PR triggers CI automated build and test. This is passing for SDK 1.5.0 but failing for SDK 2.0.0.
It seems to be an error with esptool2 not being accessible.

**Comment by slaff** [comment]
> It seems to be an error with esptool2 not being accessible.

Not really, your changes in PR #1007 changed  also the permissions of `esptool2` that is used in our CI `.travis/tools/esptool2 100755 → 100644`.
