### ISSUE TITLE
Question: Why is PSTR() a noop?

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#1063]
Sorry, if this is a stupid question. Why is PSTR(str) defined as a noop in FakePgmSpace.h?

`#define PSTR(str) (str)`

I would have expected something like this:

`#define PSTR(s) (__extension__({static const char __c[] PROGMEM = (s); &__c[0];}))`

to place a string literal in PROGMEM. Is there an alternative to use instead of PSTR(str)

**Comment by ADiea** [comment]
Yes your observation seems valid. I guess no=one used PSTR in the project yet :)

**Comment by slaff** [comment]
@tius2000 That is already fixed in the latest `develop` version.
