### ISSUE TITLE
strcpy_P: terminating null byte not copied

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#1065]
IMHO _strcpy_P_ should also copy the terminating null byte.

**Comment by tius2000** [comment]
e. g. like this: 

```
char *strcpy_P(char* dest, const char* src_P) {
    for (char *p = dest; *p = pgm_read_byte(src_P++); p++) ;
    return dest;
}
```

**Comment by zgoda** [comment]
"Normal" `strcpy` copies null character so it's perfectly reasonable to expect `strcpy_P` to behave the same way.

**Comment by ADiea** [comment]
@slaff I think this is the reason we see failure in basic_progmem sample

**Comment by zgoda** [comment]
This fixes only part of the problem with `Basic_ProgMem`.
