### ISSUE TITLE
Add servo lib support

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#108]
Servo seems to be one of those Arduino AVR libs that doens't work due to highly coupled AVR timming. 
There is a new port to ESP8266 arduino in the main repo: 

https://github.com/esp8266/Arduino/tree/esp8266-sdk-1.0/hardware/esp8266com/esp8266/libraries/Servo

**Comment by kireevco** [comment]
@robotiko PRs are welcome :)

**Comment by robotiko** [comment]
Still dealing with newbie issues, but I will try to address that as small contribution to this great project as soon as I know how it goes. 
:)

**Comment by hreintke** [comment]
@robotiko : 
Are you still working on this or can we close the issue ?

**Comment by robotiko** [comment]
I have a single servo working, however it suffers from not precise timing and it is not really usable until HW timer is available and stable. 
We can close an reopen later.

**Comment by hreintke** [comment]
Solved
