### ISSUE TITLE
WPA2 Enterprise auth access

### ISSUE THREAD

**Issue by zgoda** [SmingHub/Sming#1100]
SDK 2.0 introduces support for WPA2 Enterprise wifi auth, both EAP and PEAP. This may be exposed in Sming eg. by conditional compilation when SDK 2.0 is detected.

**Comment by slaff** [comment]
Sounds good. Make a PR and I will look at it.

**Comment by zgoda** [comment]
Okay, it sems PEAP still has issues with hardcoded outer identity, I will postpone this until SDK allows changing it and start working with MS-CHAPv2 which is most popular auth method. Will get back later to this.
