### ISSUE TITLE
After `make flash` problem

### ISSUE THREAD

**Issue by yeralin** [SmingHub/Sming#1126]
Hi,

I have NodeMCU ESP8266. I flashed it with `Basic_WiFi sample`. It flashed it successfully, and everything was working. I connected to my Wi-Fi network and got IP address. Afterwards, I pressed `CTRL+]` and quit from terminal. ESP8266 was still working. But when I disconnected it from my computer and connected it back again. ESP8266 did not start the flashed program as expected. It did nothing :( I tried to press restart button, no luck.

It would start working again, only if I flash it again, and would keep working up until I disconnect it. Seems like it resets or something. 
Maybe I'm doing something wrong or missing some step? I read the docs and looked at all examples, nothing...

Thank you!

**Comment by ADiea** [comment]
Check if you have GP0 always connected to ground. It should stay at 3.3V when normal booting and 0V when programming

**Comment by yeralin** [comment]
Yep, I figured it out last night :) GP0 was connected to the ground
