### ISSUE TITLE
Fatal exception (28) = overlapping addresses

### ISSUE THREAD

**Issue by ZyperPL** [SmingHub/Sming#1127]
Hi
I just wanted to write about this "issue" if someone in the future have similar problem.

While playing with ESP8266-01 I've encountered "Fatal exception (28)" when executing some instructions, always at the same line of the code.
Fatal exception 28 is related to reading wrong part of memory, and my program (file 0x0000.bin) was bigger than 40KB. 
It gave me an idea that there's nothing wrong with the code.
After trying many things I updated esptool.py to newest git version. And it gave me an error: "Detected overlap at address: 0xa000 for file: out/firmware/0x0a000.bin".

My solution:
Changing irom0 size in following files:
$SMING_HOME/compiler/ld/standalone.rom.ld: line 8: from `irom0_0_seg :       org = 0x4020a000, len = (1M - 0x0a000)` to `irom0_0_seg :       org = 0x4020f000, len = (1M - 0x0f000)`.
$SMING_HOME/Makefile-project.mk: line 44: from `IMAGE_SDK   ?= 0x0a000.bin` to `IMAGE_SDK   ?= 0xf000.bin`.
Maximum program size will be 64KB now.

All of this was made in develop branch (latest commit: bc64de4). SDK version: 2.0.0.
 I'm not sure if my solution is ok, and if changing irom0 size is not creating some other issues.

It would be cool if Sming installation guide would provide newest version of esptool.py (the one that checks for overlapping addresses).

**Comment by slaff** [comment]
@tius2000 Let's start incorporating some of your changes in that PR #985. Can you add a  separate PR  change that allows automatic changing of the image size and LD linker script when the size of the file grows?
