### ISSUE TITLE
[solved] How to read power value in ESP8226 using Sming?

### ISSUE THREAD

**Issue by DjamesSuhanko** [SmingHub/Sming#1128]
Sorry, guys. I found the system_get_vdd33() searching in Netbeans. Solved!
-------------------------------------------
Hello.
I saw that I can read directly from ADC information about power, using this resource in Arduino IDE:
ADC_MODE(ADC_VCC);
float vdd = ESP.getVcc();

Is there something like that to Sming?

**Comment by zgoda** [comment]
@DjamesSuhanko then close it if it's solved.
