### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by hanpal** [SmingHub/Sming#1131]
You should check the quick install guides. Tried both on Mac and Ubuntu, did not succeed on any of them. Maybe this is a great product but it is way too hard to install so I guess I'll stick to the Arduino IDE.

**Comment by hanpal** [comment]
This solved my problem for linux but it was rather complicated to find the usb device and sudo was required for make flash.

> Allow our Make system to patch the file. Try doing the following:
> 
> cd $SMING_HOME
> make dist-clean
> make

The guides should  be tried out to ensure that everything works without troubleshooting or guesswork.

**Comment by kwis2** [comment]
In my opinion paradox is that Sming is very good for tool for beginner user, while to install it you have to be very advanced. It is a very weak point of Sming.... And for long time there is no solution.

**Comment by slaff** [comment]
@hanpal @kwis2 We have updated the Mac OS X getting started guide and the precompiled Mac OS X toolchain.  Can you try to follow the steps in the [document](https://github.com/SmingHub/Sming/wiki/MacOS-Quickstart) and report your progress?

**Comment by kwis2** [comment]
I have tested and since about 3 months nothing changes. It is impossible to install Sming according to #1297

**Comment by slaff** [comment]
> It is impossible to install Sming according to 

@kwis2 Did you test it on Mac OS X? We updated the Mac OS X installation procedure only.
