### ISSUE TITLE
Discussion: UDK 2.2.2 / SDK 2.1

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#1133]
Just updated my windows machine to UDK 2.2.2 with SDK 2.1, seems to work fine (at least when using sming.mk, see #985). The new version of esptool.exe is included within the UDK. 

Are there any known issues with the new SDK?

**Comment by icodk** [comment]
@tius2000 
Could you please share the steps you took for the upgrade
Thanks

**Comment by tius2000** [comment]
@icodk 
I made a backup of c:\espressif, downloaded version 2.2.2 of the UDK (http://programs74.ru/udkew-en.html) and executed the setup file.

**Comment by icodk** [comment]
@tius2000 Thanks
What about Sming?
Backup c:\tools and pulled/download developer/v3.2.0 ?

**Comment by tius2000** [comment]
I did not change anything on my Sming setup (it should be almost up-to-date with the latest develop branch). However, I'm using the refactored makefile from #985.

**Comment by icodk** [comment]
@tius2000 
Is the refactored makefile  in the development branch ?

**Comment by tius2000** [comment]
I did not test with the normal makefile as my projects all use _sming.mk_ from #985. But I do not see any reasons why it should not work. 

The PR is not not merged yet. However, it does not replace any existing file so you may just give it a try ;-)

**Comment by icodk** [comment]
@tius2000 
Will try
Thanks again

**Comment by icodk** [comment]
I renamed C:\Espressif to  C:\Espressif_ but when I try to install the latest Unofficial Devkit 
However when I try to run the installation of the newest devkit (Espressif-ESP8266-DevKit-v2.2.1-x86) I get the following message:
An old version of Unofficial Development Kit for Espressif ESP8266 was detected. Do you want to uninstall it ?
If I click No the new devkit is not installed
What did you do to hide the older version ?

**Comment by tius2000** [comment]
Dear @icodk, I made a backup of _c:\espressif_ first and let the installer then remove it and install the new version.

**Comment by icodk** [comment]
@tius2000 
Can you now switch between the two versions by just restoring the old version ?
I am concerned by the possibility that none of them will work after the switch

**Comment by tius2000** [comment]
Yes, I switched several times with no problems. If you want to be absolutely safe, make a backup of your system partition first.

**Comment by icodk** [comment]
@tius2000 
Thanks, I will try it in a VM

**Comment by icodk** [comment]
@tius2000 I tried with the  develop branch but got the errors I reported in #1140 
For some reason I get make[2]: xtensa-lx106-elf-gcc: Command not found  when compiling third-party libs
when I set ENABLE_SSL=1. may be your refactored makefile  can fix it. Where can I download it or better if I could clone the repository that works

**Comment by slaff** [comment]
We will not support Esspressif's NON-OS SDK versions >= 2.1 and < 3.0. Once this #1470 is merged we will add support for SDK 3.0.
