### ISSUE TITLE
Issues with building sming_developer ENABLE_SSL=1

### ISSUE THREAD

**Issue by icodk** [SmingHub/Sming#1140]
Cloning developer branch, running make clean && make get the following errors:
`Services/Yeelight/YeelightBulb.cpp:9:23: fatal error: TcpClient.h: No such file
or directory`
I don't need this library anyway so I commented out 
`//#include "../Services/Yeelight/YeelightBulb.h"`
in SmingCore.h and removed the library from C:\tools\Sming\Sming\Services
started make and got a bit farther to the point that all was compiled except spiffy with the error 

>The program can't start because libwinpthread-1.dll is missing from your computer
> Try reinstalling the program to fix this problem

So I  C:\tools\Sming\Sming>cd spiffy and run make clean && make
Everything compiled nicely.
Now I tried to do ` C:\tools\Sming\Sming>make clean && make ENABLE_SSL=1`
and got the following error:
`make[2]: Leaving directory `/C/tools/sming/sming/third-party/esp-open-lwip'
/bin/sh: xtensa-lx106-elf-gcc: command not found
make[2]: xtensa-lx106-elf-gcc: Command not found`
and

 `make[2]: xtensa-lx106-elf-gcc: Command not found
make[2]: *** [crypto/aes.o] Error 127`

What do I do wrong ?

**Comment by riegaz** [comment]
> Cloning developer branch, running make clean && make get the following errors:
Services/Yeelight/YeelightBulb.cpp:9:23: fatal error: TcpClient.h: No such file or directory
I don't need this library anyway so I commented out
//#include "../Services/Yeelight/YeelightBulb.h"
in SmingCore.h and removed the library from C:\tools\Sming\Sming\Services
started make and got a bit farther to the point that all was compiled except spiffy with the error

I created a pull request. https://github.com/SmingHub/Sming/pull/1148
