### ISSUE TITLE
TcpClient reconnects after calling .close()

### ISSUE THREAD

**Issue by riegaz** [SmingHub/Sming#1159]
I'm creating a TcpClient like this:

`globClient = new TcpClient(nmOnCompleted, nmOnReadyToSend, nmOnReceive);`

At some point I want to restart and before I want to close the TcpClient to do some calculation. However, after calling

`globClient->close();`

the TcpClient reconnects to the tcp server.

Maybe I do not understand the purpose of the close() function?

**Comment by ADiea** [comment]
Hi. Offtopic: Does this mean that your other issue with compiling in Windows is solved now? If so please close the other issue thank you:)

**Comment by slaff** [comment]
> the TcpClient reconnects to the tcp server.

That should not be the case. But in order to understand the issue better we need a sample application. And the log from the calls.

**Comment by riegaz** [comment]
@ADiea actually no. I moved to Linux for now since I did not manage to make it work under Windows.

@slaff I think I found the issue. I did not clear my onComplete callback.
