### ISSUE TITLE
Build system issues

### ISSUE THREAD

**Issue by Informatic** [SmingHub/Sming#1168]
- [x] `make clean` does not properly clean additional modules set in `Makefile-user.mk` variable `MODULES` (only removes `out/build/app*` files)
- [ ] Current build system does not use dependency files (`.d`), so that changes in headers do not cause rebuilds of source files

**Comment by slaff** [comment]
@Informatic Please, submit PR with the proposed changes.

**Comment by Informatic** [comment]
Yes, I (hopefully) will, in following week/weeks... :)

**Comment by Informatic** [comment]
Ok, It seems like the first one is caused by me using relative path (`../base`) in `MODULES`, so that objects instead of being stored in `out/build/MODULENAME`, wind up in `out/build/../MODULENAME`. Sadly, I don't have any idea how to solve that without moving build directories over to module directories...

**Comment by Informatic** [comment]
Ok, well, using `$(realpath ../base)` in `MODULES`, as used in rboot appcode, seems to have done the trick
