### ISSUE TITLE
List of objects that can be moved to flash

### ISSUE THREAD

**Issue by gbl08ma** [SmingHub/Sming#1173]
I have noticed that static data RAM usage, mainly rodata, has been increasing a lot in more recent Sming versions.

This is a list of constant objects that, in principle, can be annotated to never leave the flash:

- [ ] [**http_parser** `tokens`](https://github.com/nodejs/http-parser/blob/335850f6b868d3411968cbf5a4d59fe619dee36f/http_parser.c#L189) (256 bytes)
- [ ] [**http_parser** `unhex`](https://github.com/nodejs/http-parser/blob/335850f6b868d3411968cbf5a4d59fe619dee36f/http_parser.c#L224) (256 bytes)
- [ ] [**http_parser** `normal_url_char`](https://github.com/nodejs/http-parser/blob/335850f6b868d3411968cbf5a4d59fe619dee36f/http_parser.c#L243) (32 bytes)
- [ ] [**http_parser** `http_strerror_tab`](https://github.com/nodejs/http-parser/blob/335850f6b868d3411968cbf5a4d59fe619dee36f/http_parser.c#L465) (264 bytes) - alternatively, can we get rid of this entirely or make it a compile-time option? Most people probably don't need these human-friendly errors on a constrained platform as the ESP8266.

Note that for some of those, there might be alignment issues when reading from flash. I'm not sure, but I think there are problems reading from non-4-byte-aligned addresses in flash. In that case, moving arrays of 8 and 16 bit types to flash might be problematic. They could be converted to arrays of 32 bit elements which are then casted to the original types, but that will waste some flash space (four times the space they take in RAM). There are more advanced solutions (e.g. always reading 4 bytes at a time, then using bitwise operations to retrieve the correct byte), but this is slower and requires too much changes to third-party code.

I'll update this list if I find more large constants that can eventually be moved to the flash.

**Comment by slaff** [comment]
Fixed with the merge of PR #1459.
