### ISSUE TITLE
Error during installation on windows 

### ISSUE THREAD

**Issue by shodanx2** [SmingHub/Sming#1175]
https://i.imgur.com/YYZ22jI.png

Running in an administrator cmd window

Here's a dump 
[sming install error.txt](https://github.com/SmingHub/Sming/files/1133324/sming.install.error.txt)

here's the logs

[choco.summary.txt](https://github.com/SmingHub/Sming/files/1133328/choco.summary.txt)
[chocolatey.txt](https://github.com/SmingHub/Sming/files/1133327/chocolatey.txt)

The first error is 
2017-07-08 17:26:12,328 7100 [ERROR] - ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"

I have 6gb left on this drive (ssd) so it shouldn't be an issue with being out of space.

May be a chocolatey issue

**Comment by slaff** [comment]
@shodanx2 Test with the latest packages in choco and feel free to reopen the issue if the problem persists.
