### ISSUE TITLE
TwoWire::begin has reversed parameter order than on ESP8266/Arduino

### ISSUE THREAD

**Issue by max-weller** [SmingHub/Sming#1179]
I just spent a few hours debugging a small program I ported from ESP8266/Arduino to Sming. The problem was that I called [`Wire.begin(scl, sda);`](https://github.com/esp8266/Arduino/blob/master/libraries/Wire/Wire.cpp#L57) as it works on the Arduino implementation. On Sming, the order of params is reversed: [`Wire.begin(sda, scl);`](https://github.com/SmingHub/Sming/blob/master/Sming/SmingCore/Wire.cpp#L57)

I'm not sure if this should be changed here or there, but I'd at least like to put this here as a warning for other people searching for problems with I2C on Sming.

**Comment by zgoda** [comment]
You have problem elsewhere in code or you use some ancient version of Sming. In 3.2.0 the order matches Arduino core, see https://github.com/SmingHub/Sming/blob/5c37d69f45963dcc25e2fc63ce389494f337f568/Sming/SmingCore/Wire.h#L51

**Comment by zgoda** [comment]
I remember we discussed this before. @avr39-ripe @slaff any opinion on this?

**Comment by avr39-ripe** [comment]
I think we should make Wire.begin the same as ESP8266/Arduino. Update Wire implementation and update examples app.

**Comment by slaff** [comment]
> I think we should make Wire.begin the same as ESP8266/Arduino. Update Wire implementation and update examples app.

@avr39-ripe Agreed. Can you create a new PR?

**Comment by slaff** [comment]
Should be fixed with PR #1193 which is merged now in the `develop` branch.
