### ISSUE TITLE
WifiEvents documentation

### ISSUE THREAD

**Issue by kwis2** [SmingHub/Sming#1209]
Hi
I test WifiEvents, I would like to use onAccessPointConnect delegate or I am interested in onStationDisconnect reason codes, but I am not able to find any documentation or samples.

**Comment by avr39-ripe** [comment]
Hi! For reasons of different WifiEvents look here https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/include/user_interface.h#L415 or in corresponding version of your esp-nonos-sdk. For Delegates - look inside https://github.com/SmingHub/Sming/blob/develop/Sming/SmingCore/Platform/WifiEvents.cpp to find delegate params. Will try to find some time documenting it more properly..
