### ISSUE TITLE
Code E:M 1512

### ISSUE THREAD

**Issue by fernandomorse** [SmingHub/Sming#1212]
When using Httpclient I am receiving this code E: M 1512 and it stops working

**Comment by uzi18** [comment]
can not allocate 1512 bytes of memory

2017-07-29 1:32 GMT+02:00 fernandomorse <notifications@github.com>:

**Comment by fernandomorse** [comment]
Where can I read more about it?

What do I need to do to run my test program?

@uzi18

**Comment by fernandomorse** [comment]
Ok
Reading Heap and Stack, problem solved.

**Comment by kisieel** [comment]
@fernandomorse Can you please give me some more details on how you fixed the issue? I'm experiencing similar problem in my application and ran out of ideas for debugging. I'm using multiple modules at a time to it's quite a complex case.

Is it a sign of memory leak?

Thanks
