### ISSUE TITLE
Serial callback problem

### ISSUE THREAD

**Issue by kwis2** [SmingHub/Sming#1214]
When I send garbage data to serial module work unstable. I have tested sample project and there is the same behaviour. For instance with Basic_rBoot example it is enought to send `qwertyuiopasdfghjklzxcvbnm` string to fool module. It looks like there is problem with flushing data.

below is log with added
```
Serial.println(str);
stream.flush();
```
added into serialCallBack.

> ->qwertyuiopasdfghjklzxcvbnm
> qwertyuiopas
> unknown command
> ->help
> dfghjk[10]@ Q[10]@
> unknown command
> ->help
> lzxcvb[10]@ Q[10]@
> unknown command
> ->help
> nm
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command
> ->help
> lp
> unknown command

Sming 3.3.0, module ESP8266-01

**Comment by slaff** [comment]
@kwis2 Can you check if that PR #1290 fixes the reported problem?

**Comment by kwis2** [comment]
@slaff unfortunatelly I am not able to install current version of sming #1241
