### ISSUE TITLE
MqttClient_Hello with ENABLE_SSL not working

### ISSUE THREAD

**Issue by itarataiko** [SmingHub/Sming#1220]
I'm using Sming V3.3.0

MQTT start connection
+TCP connection
connect to: test.mosquitto.org
Storing 77 bytes in stream
timeout updating: 70 -> 65535
subscription 'main/status/#' registered
realloc 77 -> 226
Storing 20 bytes in stream
DNS record found: test.mosquitto.org = 37.187.106.16
TcpConnection::connect result:, 0
OnConnected
staticOnConnected: useSSL: 1, Error: 0
SSL: Starting connection...
SSL: Switching to 160 MHz
SSL: handshake start (20064 ms)
SSL: Session Id Length: 0
please start sntp first !
SSL: handshake is in progress...
TCP sent: 105
please start sntp first !

***** Fatal exception 3
pc=0x4000df1b sp=0x3ffff5c0 excvaddr=0x4023e1b0
ps=0x00000030 sar=0x00000018 vpri=0x00000030
r00: 0x402392e5=1076073189 r01: 0x3ffff5c0=1073739200 r02: 0x3ffff7c1=1073739713
r03: 0x4023e1b0=1076093360 r04: 0x0000000f=        15 r05: 0x3ffff7c1=1073739713
r06: 0x00001f88=      8072 r07: 0x00000000=         0 r08: 0x74746975=1953786229
r09: 0x726f2e6f=1919889007 r10: 0x3fff3b58=1073691480 r11: 0x00000003=         3
r12: 0x3ffff710=1073739536 r13: 0x0000000f=        15 r14: 0x0000007f=       127
r15: 0x4023e1b0=1076093360

Last lines in the stack trace are:

0x4023f024: gdb_exception_handler at /Users/igor/dev/Sming/Sming/gdb/gdbstub.c:89
0x400005e1: ?? ??:0
0x4000df1b: ?? ??:0
0x402392e5: SHA512_Update at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/crypto/sha512.c:169
0x4023e1b0: espconn_init at ??:?
0x4023e1b0: espconn_init at ??:?
0x40239372: SHA512_Final at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/crypto/sha512.c:207 (discriminator 3)
0x40231a80: x509_new at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/x509.c:195
0x4016ace7: ?? ??:0
0x401062c8: sntp_get_current_timestamp at ??:?
0x40245d6c: ax_port_malloc at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/replacements/mem.c:51
0x40245da0: ax_port_calloc at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/replacements/mem.c:65
0x4022ee7b: process_certificate at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1.c:2135
0x40230be3: do_clnt_handshake at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1_clnt.c:107
0x4022e63c: add_packet at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1.c:815
0x40230389: do_handshake at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1.c:1576
 (inlined by) basic_read at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1.c:1452
0x40102bde: lmacProcessTxSuccess at ??:?
0x40105577: wDev_ProcessFiq at ??:?
0x4000050c: ?? ??:0
0x40105274: wDev_ProcessFiq at ??:?
0x4024635c: ax_fd_getfd at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/compat/lwipr_compat.c:326
0x402448e5: axl_ssl_read at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/compat/lwipr_compat.c:76
0x4021400f: pp_attach at ??:?
0x4021405e: pp_attach at ??:?
0x4010422a: pp_post at ??:?
0x402134cf: ppTxPkt at ??:?
0x402305b4: ssl_read at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/ssl/tls1.c:301
0x40244909: axl_ssl_read at /Users/igor/dev/Sming/Sming/third-party/axtls-8266/compat/lwipr_compat.c:76
0x40221bb9: pbuf_free at ??:?
0x40100a0d: ets_timer_disarm at ??:?
0x40243558: WDTClass::alive() at /Users/igor/dev/Sming/Sming/SmingCore/Platform/WDT.cpp:24
0x40242962: TcpConnection::staticOnReceive(void*, tcp_pcb*, pbuf*, signed char) at /Users/igor/dev/Sming/Sming/SmingCore/Network/TcpConnection.cpp:821

Can you help with this issue?
Thanks

**Comment by mtzfactory** [comment]
Hi,

I have the same problem: https://github.com/SmingHub/Sming/issues/1234#issuecomment-328875862

Any solution?
