### ISSUE TITLE
docker, adafruit huzzah, blink not working

### ISSUE THREAD

**Issue by nirdroid** [SmingHub/Sming#1235]
hi, I'm using the latest docker version of sming. everything is configured and working
make, make flash successful, but no led is blinking!
I tried changing LED_PIN to 0, 2 but no blink.
I run blink with the  arduindo ide frameworks, and it works ok, so the chip is ok
maybe the framework does not identify my chip correctly?
is  docker version is being maintained?
what else should I do?

**Comment by ADiea** [comment]
Hi @nirdroid please provide more info like logs of the building / flashing and hopefully console logs.

**Comment by slaff** [comment]
@nirdroid Feel free to reopen the ticket when you can provide more information about the issue.
