### ISSUE TITLE
Missing Make target in eclipse for both Basic_ssl and Basic_webclient 

### ISSUE THREAD

**Issue by icodk** [SmingHub/Sming#1251]
Both sample projects Basic_ssl and Basic_webclient are missing Make target in eclipse
However can be build on the commandline with make, make  rebuild and make flash
Tried to add: right click on the project ->Make target->create . This has created a rebuild in the Make target window but double clicking on it generate an error:
Errors occurred during the build.
Errors running builder 'CDT Builder' on project 'Basic_Ssl'.
java.lang.NullPointerException

Any idea ?
(Developer branch on Windows)

**Comment by slaff** [comment]
This is more of an Eclipse related issue than Sming related. Feel free to reopen if you have proof that Sming is causing the problems.
