### ISSUE TITLE
Migrate to a more stable MQTT library

### ISSUE THREAD

**Issue by moelha** [SmingHub/Sming#1291]
Is it safe to use the MQTT library for production? I read from the author's github page 

> Under development. DO NOT USE in a serious development. API is not closed, so it could be changed.

Thanks

**Comment by slaff** [comment]
I would say yes. We are using it in production and there are no known issues with it.

**Comment by slaff** [comment]
Closing this issue. Feel free to reopen it If there are exact suggestion how to improve the Sming MQTT code.
