### ISSUE TITLE
MeteoControl example don't works

### ISSUE THREAD

**Issue by teicors** [SmingHub/Sming#1302]
Can somebody confirm the lib of DHT11 is working (basically the Meteocontrol sample)? I tested the schematic with ArduinoESP8266 IDE and it seems working while a new installation of Sming don't provide any value.

**Comment by slaff** [comment]
@ADiea this is the second report about issues with the DHT11 library from you. Can you please check if this is working for you?

**Comment by slaff** [comment]
@teicors The issue can be further discussed here: #1331.
