### ISSUE TITLE
Makefile - can not have same filenames in different locations

### ISSUE THREAD

**Issue by cr1st1p** [SmingHub/Sming#1304]
I have one library (added via MODULES, in my Makefile) that has a base Controller.cpp file - in one namespace.
Then, in my application, I have app/Controller.cpp , in a different namespace (a class  derived from the library one)
The problem is that current Makefile will compile the library one, but not also the app one.
This is because of the vpath setting and implicit .cpp rules, which makes Make find that 
*build/app/Controller.o dependency is on my module/Controller.cpp instead of app/Controller.cpp

There is a mention about this type of issue also in http://www.conifersystems.com/whitepapers/gnu-make/ , chapter "Pattern Rules and Search Paths"

**Comment by cr1st1p** [comment]
I'm on my way to fix this. Bumped also on a problem with the archive program ('ar') which also has problem with same filenames.

**Comment by cr1st1p** [comment]
Forgot to mention - Pull request is #1305

**Comment by slaff** [comment]
Fixed with that rebase #1335
