### ISSUE TITLE
Please add 'const' to class member functions that are not modifying the object

### ISSUE THREAD

**Issue by cr1st1p** [SmingHub/Sming#1310]
Example I bumped into, just now:
DateTime::toShortDateString() 
Code does not change internal state of the object, so it should be declared as 'const', so that I'm allowed to use it on a 'const DateObject&'.

I think most of DateTime functions should be const.

Thank you.

**Comment by slaff** [comment]
@cr1st1p Can you make a PR  with the suggested changes?

**Comment by frankdownunder** [comment]
There are static code analysis tools that would tell us which member functions can be marked const, Ill see if i can find one.

**Comment by slaff** [comment]
For the use of "const" we should make the changes across the whole Sming Framework classes and not just here and there. A "const" change should be merged with that PR #1384.
