### ISSUE TITLE
Fatal exception 28 with latest SDK2.2.0

### ISSUE THREAD

**Issue by SvenLuebke** [SmingHub/Sming#1330]
Hi!

Yes, I know...probably I shouldn't use the current SDK, but I'm interested in the error the ESP8266 is running into: As soon, as spiffs is used, the Sming samples crash on my LoLin (4MB DIO SPI EEPROM) board. Most of the other samples (which don't use spiffs) seem to work. I already got these kind of errors with SDK2.1.0. With 2.2.0 I get the following output (I compiled and flashed the sample HttpServer_ConfigNetwork):

***** Fatal exception 28
pc=0x40101d72 sp=0x3ffff990 excvaddr=0x00000004
ps=0x00000030 sar=0x00000003 vpri=0x00000000
r00: 0x00000000=         0 r01: 0x3ffff990=1073740176 r02: 0x00000000=         0
r03: 0x00000001=         1 r04: 0x00000000=         0 r05: 0x00000000=         0
r06: 0x3ffeb534=1073657140 r07: 0x00000070=       112 r08: 0x00000006=         6
r09: 0x00000000=         0 r10: 0x3fff0000=1073676288 r11: 0x00000001=         1
r12: 0x3fff0000=1073676288 r13: 0x3ffeb4bc=1073657020 r14: 0x3ffeb490=1073656976
r15: 0x3fff00b4=1073676468

According to the stacktrace, the following functions were executed last:

$SMING_HOME/../tools/decode-stacktrace.py ./out/build/app.out ./stacktrace.txt
0x40101d72: phy_change_channel at ??:?
0x40101012: os_printf_plus at ??:?
0x4021f04b: ets_sprintf at ??:?
0x4022ff30: pbuf_alloc at ??:?
0x4022fded: pbuf_free at ??:?
0x40101b3b: user_spi_flash_dio_to_qio_pre_init at ??:?
0x40214aa9: os_random at ??:?
0x40233a34: etharp_request at ??:?
0x40232967: igmp_delaying_member at igmp.c:?
0x40232a38: igmp_report_groups at ??:?
0x4021238e: chm_set_current_channel at ??:?
0x4020c1e2: wifi_softap_start at ??:?
0x4020c273: wifi_softap_start at ??:?
0x4021a687: flash_data_check at ??:?
0x4021a62c: flash_data_check at ??:?
0x4010077a: wdt_feed at ??:?

How can I debug that issue further?

Thank you for your hints!

BR,Sven

**Comment by slaff** [comment]
Can it be related to this issue ( https://github.com/espressif/ESP8266_NONOS_SDK/issues/98 )?

**Comment by SvenLuebke** [comment]
Hi @slaff, thanks for your answer!

I'm not completely sure! I often tried to get Basic_WebSkeletonApp running before...without any success. Currently it stops with the following output:

timeout updating: 70 -> 65535
Server timeout updating: 40 -> 0
fs.start: size:3756 Kb, offset:0x51000

mount res: 0

Afterwards - to verify the other samples are working - I flashed some of them. As soon, as they were using the spiffs, the samples crashed.

What I now found out: Getting the error from my first post I have to flash the init data again. If I do that, the error is gone and HttpServer_ConfigNetwork seems to be completely working stable.

Of course I verified that "healing" with Basic_WebSkeletonApp but unfortunately it didn't help.

Does that ring a bell to someone?

BR, Sven

**Comment by slaff** [comment]
>  Currently it stops with the following output:

> timeout updating: 70 -> 65535
> Server timeout updating: 40 -> 0
> fs.start: size:3756 Kb, offset:0x51000

> mount res: 0

I don't see anything wrong here. With that update 65b91672531b3dc2370ab8f570e7eee529b316ee by default Sming will print less debug messages. If you want to see again all debug messages you should recompile the library and the sample with the following commands:
```
cd $SMING_HOME
make dist-clean
export DDEBUG_VERBOSE_LEVEL=3
cd ../samples/Basic_WebSkeletonApp
make
```
