### ISSUE TITLE
Using Libraries/Adafruit_BME280_Library requires extended include path

### ISSUE THREAD

**Issue by fooker** [SmingHub/Sming#1343]
Doing `#include <Libraries/Adafruit_BME280_Library/Adafruit_BME280.h>` fails as it requires `Adafruit_Sensor.h` to be found in the include-path.

Setting `EXTRA_INCDIR += $(SMING_HOME)/Libraries/Adafruit_Sensor` before including the Sming Makefile seems to work as a workaround.

Maybe this can be done the same way as done with the `Adafruit_GFX` Library and be added to the include-path always?

**Comment by slaff** [comment]
@fooker Check this PR #1344 and tell me if it works for you.
