### ISSUE TITLE
Bad define for digitalPinToInterrupt

### ISSUE THREAD

**Issue by frankdownunder** [SmingHub/Sming#1345]
----Sming/SmingCore/Interrupts.h ----
The define for digitalPinToInterrupt looks like this:
-#define digitalPinToInterrupt(pin)  ( (p) < ESP_MAX_INTERRUPTS ? (p) : -1 )

It should be like this:
+#define digitalPinToInterrupt(pin)  ( (pin) < ESP_MAX_INTERRUPTS ? (pin) : -1 )

**Comment by slaff** [comment]
Yeah, I also noticed this while testing one of the IR libraries. Can you send a PR?

**Comment by frankdownunder** [comment]
OK.  

I was hoping to avoid fighting with git again !  I have a subversion background and git gives me a headache.

Frank
