### ISSUE TITLE
Latest commit (cd7a1d36e4cd138531658e28c39633be5eab91db) fails to compile

### ISSUE THREAD

**Issue by vijaygill** [SmingHub/Sming#1365]
The latest cut of code does not compile and fails with following error:

third-party/ws_parser/ws_parser.c: In function 'ws_parser_execute':
third-party/ws_parser/ws_parser.c:247:21: error: 'for' loop initial declarations are only allowed in C99 mode
                     for(size_t i = 0; i < chunk_length; i++) {
                     ^
third-party/ws_parser/ws_parser.c:247:21: note: use option -std=c99 or -std=gnu99 to compile your code
Makefile:557: recipe for target 'out/build/third-party/ws_parser//ws_parser.o' failed
make: *** [out/build/third-party/ws_parser//ws_parser.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by slaff** [comment]
Do the following...
```
cd $SMING_HOME
make dist-clean
make
```
this way our build system will patch the needed files.

**Comment by vijaygill** [comment]
@slaff thanks!!! it worked. I keep two versions of sming - one stable and other latest to test things out. make dist-clean did the trick.

I will close the issue now.
