### ISSUE TITLE
[Feature Request] MqttClient - Please give access to change server and port setting in runtime

### ISSUE THREAD

**Issue by dpechman** [SmingHub/Sming#1375]
Should be good to have how to access to change in runtime the variables private **server** and **port** in MqttClient library.

**Comment by frankdownunder** [comment]
I agree, there is no constructor other than the one that takes the serverhost  and port.
As a workaround, you can allocate the thing at runtime, and use the pointer to access the class later on.

**Comment by slaff** [comment]
What we can do is try to unify the connection mechanism for the network clients.
For the MqttClient this will mean the following
* Introduce constructor without parameters
* Deprecate the constructor with the server and port
* deprecated the current `connect` methods in the MqttClient class.
* introduce new `connect` method that can replace the old constructors. Ex `bool connect(const url& clientName, uint32_t sslOptions = 0);`  If someone wants to connect to a server and port, use SSL and provide username and password he/she can call:
```
MqttClient client;
client.connect("mttqs://user:password@server:port", "unique-client-name");
```

**Comment by frankdownunder** [comment]
@slaff Would you like me to have a go at this?

**Comment by slaff** [comment]
> @slaff Would you like me to have a go at this?

@frankdownunder Yep, give it a try.
