### ISSUE TITLE
WebSocket Server

### ISSUE THREAD

**Issue by 3nd0y** [SmingHub/Sming#1388]
Is there library for websocket server in Sming? Cause i couldn't find that even in Sming v3.5 :(

**Comment by slaff** [comment]
> Is there library for websocket server in Sming? ...

Yes, you can create a websocket server in Sming. Take a look at the sample
https://github.com/SmingHub/Sming/blob/develop/samples/HttpServer_WebSockets/app/application.cpp#L102 to see how to attach the Websocket resource to the desired server path.

**Comment by 3nd0y** [comment]
My bad, i thought it for WS client. Thanks @slaff
