### ISSUE TITLE
Some postParams may left unescaped

### ISSUE THREAD

**Issue by softerra** [SmingHub/Sming#1401]
Please look at the code of **formUrlParser** performing final unescaping of the params:
https://github.com/SmingHub/Sming/blob/0a749213e2397b276b8d589226a91557f61e2565/Sming/SmingCore/Network/Http/HttpBodyParser.cpp#L40-L53

The problem is at the line 48 : HashMap::remove() shifts key- and value- elements in the respective arrays so the next postParams item will have the current value of the index **i** and won't be processed on the next loop iteration after **i++**

In order to fix this and keep the rest things as expected it may be changed like that:
https://github.com/softerra/Sming/commit/54c28b9a1170a37b41fd0410e9dbd31e76c1f0e1

**Comment by slaff** [comment]
@softerra Nice catch! Can you submit a PR with the changes?
