### ISSUE TITLE
Question about SmingCore.h

### ISSUE THREAD

**Issue by Vinimuller** [SmingHub/Sming#1407]
Hello!
At my application for an ESP8266-12 I'm trying to keep things organized. For that I created a "sensorHandler.h" file inside "include" folder and inside "app"  folder I created the respective "sensorHandler.cpp" file.
At my header file I'm trying to create a class that contains variables of type String and Timer which are defined in SmingCore.h, but when I include SmingCore.h in my header file and compile, I keep receiving a bunch of erros saying:
`"error: template with C linkage template <class Element>"`

After some tests I realized that I always receive this error when I try to include SmingCore.h in any header file.

So my question is: How can I declare my class that uses variables of type Timer an String?

I'm running Sming on Ubuntu 16.04 LTS and the class that I am trying to create is:

![whatsapp image 2018-06-20 at 16 31 59](https://user-images.githubusercontent.com/25661168/41680320-81d61b2c-74a7-11e8-9fd3-37e12883374b.jpeg)

**Comment by slaff** [comment]
@Vinimuller It sounds like programming error from your side. Did you put C++ code inside extern "C" block(s)? May be the easiest is to publish the code of the application so that I can look over it when I have some time.

**Comment by Vinimuller** [comment]
@slaff Yeah, I've read about it and found something mentioning the extern "C", but I don't have C++ code inside it.
Here is the sensorHandler.cpp

![whatsapp image 2018-06-21 at 18 04 39](https://user-images.githubusercontent.com/25661168/41745567-b78652ba-757d-11e8-872a-2628e3161071.jpeg)

**Comment by slaff** [comment]
@Vinimuller Please create a sample app where the problem is reproducible. Put that app in Github and share the link with us. After that I can try to reproduce the issue locally and analyze and fix it, if needed.

**Comment by Vinimuller** [comment]
Hey @slaff, I got it fixed!
The problem was that I tried to include `#include<SmingCore/SmingCore.h>` but it actually is `#include<SmingCore.h>`
Thanks!
