### ISSUE TITLE
Refactoring: Move ArduinoJson from Services to Libraries

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1414]
The ArduinoJson library should be moved from Services to Libraries. Libraries is better suited as it contains the Arduino compatible libraries and we have mechanism there that can help us keep the third-party Arduino libraries up-to-date.

**Comment by vijaygill** [comment]
A quick question - will it become a git-module also as part of refactoring?

Thanks.
Vijay

**Comment by slaff** [comment]
> A quick question - will it become a git-module also as part of refactoring?

If there are no big differences then a volunteer, for example you :), can add it as a git submodule.

**Comment by vijaygill** [comment]
Sure! No problem! I will be glad to do it :)

**Comment by slaff** [comment]
@vijaygill Get the latest `develop` version and give it a try. ArudinoJson is now moved to Libraries.
