### ISSUE TITLE
Any plans to support the new SDK 3.0.0

### ISSUE THREAD

**Issue by stokersoft** [SmingHub/Sming#1439]
Hi,

There are some severe bugs in all espressif SDK's less than 3.0.0. They are not compatible with some routers, like Jensen Omni and Nova mesh. Its fixed in 2.2.1 but, that version has some other flaws when downloading larger content via tcp.

Any plans to support this new SDK? First thing must be to let opensdk be based on 3.0.0. right?

**Comment by slaff** [comment]
> First thing must be to let opensdk be based on 3.0.0. right?

Right. @stokersoft what you can do is create a PR in the [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) project with the 3.0.0 version or open an issue in that project.

**Comment by vijaygill** [comment]
There is branch in a fork of the esp-open-sdk https://github.com/nabovarme/esp-open-sdk/tree/sdk-v3.0.0. I have not tried it myself (just found it after reading your post), might do it this weekend.

**Comment by slaff** [comment]
@stokersoft You can try this unofficial and untested branch  (https://github.com/slaff/Sming/tree/update/sdk-3.0) which supports compilation with the v3.0 + updates of the NON-OS SDK. 

The commands to do this are:
```
cd /tmp
git clone -b update/sdk-3.0 https://github.com/slaff/Sming.git
cd Sming/Sming
export SMING_HOME=`pwd`
export SDK_BASE="$SMING_HOME/third-party/ESP8266_NONOS_SDK"
make 
```

Since you are switching between SDK versions you might need to issue this command, only once, before flashing:

```
make flashinit
```

Give it a try and let us know if it works for you and if there is more free heap.

**Comment by vijaygill** [comment]
> @stokersoft You can try this unofficial and untested branch (https://github.com/slaff/Sming/tree/update/sdk-3.0) which supports compilation with the v3.0 + updates of the NON-OS SDK.
> 
@slaff - great stuff!!! If you need tester, I can be one :) Do you keep that branch up-to-date with the develop of main repo (I notice that you do, just asking)?

Vijay

**Comment by slaff** [comment]
> great stuff!!! If you need tester, I can be one :)

@vijaygill Give it a try. As long as there is interest and progress I will keep it up to date until we merge it into develop at some later moment.

**Comment by slaff** [comment]
With the new commits this branch of Sming (https://github.com/slaff/Sming/tree/update/sdk-3.0) adds support for SDK 3.0 for rBoot applications. So far all rBoot samples seem to work as expected.
