### ISSUE TITLE
HttpServer_Websocket example has some unused files from HttpServer_Ajax example 

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#149]
Looks like orphan files in /web folder that introduces confusion in the example.

**Comment by Tavalin** [comment]
@robotiko can you submit a PR to fix please?

**Comment by robotiko** [comment]
Sure thing. 
It is blocked by #158.

**Comment by hreintke** [comment]
Sming repository is currently being restructured and cleaned. This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
