### ISSUE TITLE
Notice: Recheck your PRs

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1501]
<strike>GitHub seems to have [problems](https://developers.slashdot.org/story/18/10/22/0437245/githubs-website-remains-broken-after-a-data-storage-system-failed-earlier-today)</strike>

GitHub seems to be stable again. Check your latest PRs if all the committed changes are in there. If something is missing make sure to `push -f` the changes to the GitHub server.

**Comment by slaff** [comment]
@mikee47 the GitHub servers seem to be stable again. Can you try again to send the latest changes to your PRs and/or re-build again Travis and Appveyor builds?

**Comment by mikee47** [comment]
@slaff I've pushed a change to #1498. I've only got Travis set up on my fork and it's failing to start.

**Comment by mikee47** [comment]
Looks like Travis is working again, bless him :-)
