### ISSUE TITLE
Setting two roms fails to build

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1529]
Adding

> RBOOT_TWO_ROMS = 1

to makefile results in build failure:

> elf/bin/ld: cannot open linker script file rom1.ld: No such file or directory

**Comment by rickyitexpert** [comment]
same here

**Comment by slaff** [comment]
@riban-bw With the arrival of (partition tables)[https://sming.readthedocs.io/en/latest/_inc/Sming/Components/Storage/index.html] this should be possible and work without big efforts from your side. Feel free to re-open this ticket if you cannot implement your desired setup with the latest develop version.
