### ISSUE TITLE
Feature request: Makefile target to flash just the application firmware image

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1530]
Each time the "flash" target is called it creates and flashes the boot loader, application and file system. It would be advantageous to allow these to be flashed individually, e.g. when making a small change the the application it is irksome to flash the whole SPIFFS file system, especially if the file system contains user data altered since the last flash operation.

**Comment by rickyitexpert** [comment]
I was also thinking the same. It will cut down flashing, debugging , code testing significantly.
my spiffs is almost 1.25 bigger than original firmware. Flashing takes significant share about 60% time of my firmware development. this feature would reduce it to around 45%.

**Comment by riban-bw** [comment]
A workaround may be to manually disable SPIFFS in the local makefile (DISABLE_SPIFFS = 1) after first uploading the SPIFFS image. Another workaround is to set DISABLE_SPIFFS=1 as a parameter to make, e.g.

> make flash DISABLE_SPIFFS=1

I haven't checked whether this has other impact, e.g. making file system unavailable to application.
I have just observed that the application seems to start running before the SPIFFS is flashed which kind of makes sense but surprised me a little.
