### ISSUE TITLE
Feature request: Make target that builds and launches web server for rboot OTA

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1536]
It would be advantageous to be able to launch a web server to serve rBoot OTA images. I have tweaked my makefile thus:

```
build_ota: all
	cd $(FW_BASE) && python -m SimpleHTTPServer 8080
```

**Comment by slaff** [comment]
> It would be advantageous to be able to launch a web server to serve rBoot OTA images.

It might seem like a good idea only for testing purposes. Is that what you mean?

**Comment by riban-bw** [comment]
Yes - absolutely. Whilst iterating through the design and build stages it is handy to be able to flash the rebuild firmware to the ESP8266 module. If this is done with otaRboot then we need a web server to serve the image. One could just run this all the time or at the start of each session but this idea might be neat.

**Comment by slaff** [comment]
@riban-bw Please, take a look at PR #1537.
