### ISSUE TITLE
Building libsming from git clone gives repeated error: error: unrecognized input

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1541]
Clone sming from github and build library:

> git clone https://github.com/SmingHub/Sming.git
cd Sming
export SMING_HOME=$PWD/Sming
export ESP_HOME=PATH_TO_ESP_TOOLKIT
make -C $SMING_HOME dist-clean
make -C $SMING_HOME

Error messages in build output:

> make: Entering directory 'Sming/Sming'
Fetching Arduino Library Libraries/Adafruit_BME280_Library/ ...
Submodule 'Sming/Libraries/Adafruit_BME280_Library' (https://github.com/adafruit/Adafruit_BME280_Library.git) registered for path 'Libraries/Adafruit_BME280_Library'
Cloning into 'Sming/Sming/Libraries/Adafruit_BME280_Library'...
Submodule path 'Libraries/Adafruit_BME280_Library': checked out '321186220e1e04080bb70fa45aae6e6a5820899f'
**error: unrecognized input**
make: [Makefile:531: Libraries/Adafruit_BME280_Library/library.properties] Error 128 (ignored)

**error: unrecognized input** is repeated for each submodule checked out. It does not seem to stop the build but the error is disconcerting.

**Comment by slaff** [comment]
We could suppress all errors coming from `git-apply` but unfortunately also our verbose progress information will also be hidden. I would prefer to leave it as it is at the moment.
