### ISSUE TITLE
Serial output does not appear in gdb

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1548]
Running a gdb session with libsming compiled with ENABLE_GDB=1 the output from Serial.println() does not appear. Changing GDBSTUB_REDIRECT_CONSOLE_OUTPUT has no effect and using "tty /dev/pty0" in gdb does not work. (tty should direct program output to the specified tty.)

**Comment by slaff** [comment]
Fixed with the merge of PR #1655.
