### ISSUE TITLE
Several coding style errors

### ISSUE THREAD

**Issue by riban-bw** [SmingHub/Sming#1553]
Running `make cs` updates several files. These should be corrected and committed to avoid interfering with other PRs.

**Comment by riban-bw** [comment]
It seems that Travis-CI is configured to fail code style checks for SDK 2 for Sming that has been validated with `make cs`.

**Comment by slaff** [comment]
> It seems that Travis-CI is configured to fail code style checks for SDK 2 for Sming that has been validated 

No,  the coding style check is done only for one of the 3 builds, just because the source code does not change, and at the moment we use SDK 2.0 to be the one. But the current coding style is ok. Somehow you clang-format version is breaking it.
