### ISSUE TITLE
Migrate sming repo under opensource group

### ISSUE THREAD

**Issue by kireevco** [SmingHub/Sming#156]
I'm proposing to move sming repo to https://github.com/sming-framework
This way we will be able to add multiple integrations easily (travisci, pivotal, etc).
It will also related to https://github.com/anakod/Sming/issues/69 and https://github.com/anakod/Sming/issues/136

@anakod will need to transfer repo as is with all issues and wiki.

Let me know what you think folks.

### UPDATE
Please see [travis-ci](https://travis-ci.org/sming-framework/Sming) example for Sming repo

**Comment by Tavalin** [comment]
+1

**Comment by ystrem** [comment]
Yep +1

-----Original Message-----

**Comment by Loooopy** [comment]
+1
Sounds good, it will be easier to find for new guys.

**Comment by Hukuma23** [comment]
+1

**Comment by zhivko** [comment]
I vote for it. +1

**Comment by kennpie** [comment]
As long as n00bs like me can still get it, sure.

**Comment by kireevco** [comment]
@anakod any update on this?

**Comment by robotiko** [comment]
+1

**Comment by robotiko** [comment]
Any update on this?

**Comment by kireevco** [comment]
Done! Thank you @anakod 
(Hi from Köln)
![](https://scontent-frt3-1.cdninstagram.com/hphotos-xaf1/t51.2885-15/e35/11850424_875270485859789_1065775115_n.jpg)
