### ISSUE TITLE
Custom headers are not sent correctly

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1562]
Setting custom header results in invalid HTTP request.
```
	HttpHeaders headers;
	headers[F("X-Powered-By")] = _F("Sming");				  // Use text for non-standard field names
	getRequest->setHeaders(headers);
```

![image](https://user-images.githubusercontent.com/247452/50440510-dcbf1c80-08f6-11e9-9429-d40f9519c2d0.png)

As can be seen from the snapshot above the header name is missing.

**Comment by slaff** [comment]
@mikee47 Can you take a look at that issue, please?

**Comment by mikee47** [comment]
@slaff Just had a quick look, problem is with `HttpHeaders::setMultiple()` which needs over-riding. I'll submit a PR later today.

**Comment by mikee47** [comment]
@slaff This should sort the problem, can you check?
