### ISSUE TITLE
Problem with newpwm duty cycles in Basic_HwPWM

### ISSUE THREAD

**Issue by verybadsoldier** [SmingHub/Sming#1569]
This ticket is basically a successor to issue #1568.

> I am the maintainer of a firmware for an RGBWW Controller:
> https://github.com/verybadsoldier/esp_rgbww_firmware
> 
> It currently runs on Sming 3.5.1 and is working fine. I am using espressif PWM (ENABLE_CUSTOM_PWM = 0).
> 
> Now I tried porting the firmware over to Sming 3.7.0.1.

As I had no luck using the SDK-PWM (as described in #1568) today I tried to use the CustomPWM (newpwm) instead as I learned it is the better implementation anyway.

After some problems using `newpwm` with my own firmware I tried the provided example `Basic_HwPWM` and I was experiencing the same problems also.

The problem is that on the PWM pin I nearly get all the time full VCC voltage. My expectation is that I only get full VCC voltage when setting duty to `maxDuty`.

I hope it should be easily reproducible. I simplified the sample so that only one pin (pin `13`) is used:
```
void init()
{
	Serial.begin(SERIAL_BAUD_RATE); // 115200 by default
	Serial.systemDebugOutput(true); // Enable debug output to serial

	// WIFI not needed for demo. So disabling WIFI.
	WifiStation.enable(false);
	WifiAccessPoint.enable(false);

	HW_pwm.analogWrite(13, 50);

	debugf("PWM output set on all 8 Pins. Kindly check...");
	debugf("Now Pin 2 will go from 0 to VCC to 0 in cycles.");
        debugf("Max Duty: %i", maxDuty);
}
```
In that version I set pin `13` and I measure (nearly) full VCC of `3.25 V` already with a duty of `50`. `maxduty` is `25000`.

Other duties and the measured voltages:

duty | voltage
-- | --
0 | 0,2 mV
1 | 119mV
2 | 199 mV
10 | 0,845 V
20 | 1,643 V
35 | 2,835 V
50 | 3,25 V
100 | 3,25 V
... | always 3,25 V from here

(My DMM does not feature TrueRMS so I expect the voltages not to be very accurate but I think it is enough to get the basic idea)

I have an LED connected to that pin and I would expect an effective voltage range from `0 V` to `3.3 V` scaled from duty `0` to duty `25000` (as this is `maxduty`).

I am aware the `newpcm` was fixed recently and others seem to be able to use it. So it might be some stupidness or wrong expectations on my side. But I currently can't make sense of it.

One additional question please:
The sample is named `Basic_HwPWM` (Hardware PWM) but as far as I know the ESP8266 does not support any kind of hardware PWM and PWM is implemented in software, no? Maybe the name is just misleading?

**Comment by mikee47** [comment]
With the new PWM library both duty and period are specified 200ns intervals. See #1561 for details.
Yes, ESP8266 is lacking in direct hardware support for this kind of thing; something like an AVR or PIC are arguably better for that kind of stuff and can be added as a co-processor. However, the ESP8266 PWM implementation uses the hardware timer hence the title. It does a pretty good job, considering!

**Comment by verybadsoldier** [comment]
Thanks for reply, but sorry, I can't get it to work.

The documentations (https://github.com/StefanBruens/ESP8266_new_pwm/) says:
> E.g. for 10% duty cycle at 1kHz you need to specify a period value of 5000 and a duty cycle value of 500, a duty cycle of 5000 or above switches the channel to full on.

I used the exact values and put them in `Basic_HwPWM`:
```
void init()
{
	Serial.begin(SERIAL_BAUD_RATE); // 115200 by default
	Serial.systemDebugOutput(true); // Enable debug output to serial

	// WIFI not needed for demo. So disabling WIFI.
	WifiStation.enable(false);
	WifiAccessPoint.enable(false);

	HW_pwm.setPeriod(5000);
	HW_pwm.analogWrite(13, 500);

        debugf("Max Duty: %i", maxDuty);
}
```
According to the docs it should give 10%, right? But I get 100% which is unexpected.

Also the docs say you get 100% from `5000` duty cycle or above so I think `5000` is duty cycle maximum. But `HardwarePWM::getMaxDuty` returns `125000`.




This code:
```
HW_pwm.setPeriod(5000);
HW_pwm.analogWrite(13, 5);
```
looks like this, so there is actually PWM happening:
![image](https://user-images.githubusercontent.com/364469/50738037-f4888180-11cf-11e9-8f6f-e66b96abf95b.png)

I am sorry as I appear to have some misunderstanding. A hint where I am wrong is greatly appreciated.

**Comment by mikee47** [comment]
OK, first things first. If #1568 is resolved could you maybe post a brief note to say how you fixed the issue, then close it?

**Comment by verybadsoldier** [comment]
#1568 is not resolved. I just tried use `newpwm` instead since it appeared to be the superior approach anyway.

**Comment by mikee47** [comment]
`SDK_PWM_PERIOD_COMPAT_MODE` defaults to ON so period at 1us resolution, duty 40ns. For 1kHz use a period of 1000. To get 50% use duty=(1000 * 0.5 * 25)=12500. 10% duty = (1000 * 0.1 * 25) = 2500.

**Comment by verybadsoldier** [comment]
Sorry, still no luck. This does not give me `50%` and `10%` but both (again) still `100%`:
```
HW_pwm.setPeriod(1000);
HW_pwm.analogWrite(13, 12500);
```
and
```
HW_pwm.setPeriod(1000);
HW_pwm.analogWrite(13, 2500);
```

But now `HW_pwm::getMaxDuty` returns `25000` which seems correct!

**Comment by mikee47** [comment]
Not sure what else to suggest. I've built the `Basic_HwPWM` sample with your mods. Output on pin 13, looks fine on 'scope.

**Comment by verybadsoldier** [comment]
Well, super strange then :( Thanks for taking the time though.

A working version for me was `3.5.1`. When i go to `Basic_HwPWM`, set `ENABLE_CUSTOM_PWM=0` and put pin `13` into the fading loop then I get this on the scope:
https://streamable.com/scnwo

Pretty much as expected.

**Comment by mikee47** [comment]
This is what I get https://streamable.com/lkmwp

Sample code modified so only pin 13 is being used. I'm building under Windows using Espressif SDK3.0.

```
#include <user_config.h>
#include <SmingCore/SmingCore.h>
#include <HardwarePWM.h>

//uint8_t pins[8] = {4, 5, 0, 2, 15, 13, 12, 14}; // List of pins that you want to connect to pwm
uint8_t pins[8] = {13}; // List of pins that you want to connect to pwm
HardwarePWM HW_pwm(pins, ARRAY_SIZE(pins));

Timer procTimer;
int32 i = 0;
bool countUp = true;

int maxDuty = HW_pwm.getMaxDuty();
int32 inc = maxDuty / 50;

void doPWM()
{
	if(countUp == true) {
		i += inc;
		if(i >= maxDuty) {
			i = maxDuty;
			countUp = false;
		}
	} else {
		i -= inc;
		if(i <= 0) {
			i = 0;
			countUp = true;
		}
	}
	HW_pwm.analogWrite(13, i);

	Serial.print('.');
}

void init()
{
	Serial.setPort(UART_ID_1);
	Serial.begin(SERIAL_BAUD_RATE); // 115200 by default
	Serial.systemDebugOutput(true); // Enable debug output to serial

	// WIFI not needed for demo. So disabling WIFI.
	WifiStation.enable(false);
	WifiAccessPoint.enable(false);

	// Setting PWM values on 8 different pins
//	HW_pwm.analogWrite(4, maxDuty);
//	HW_pwm.analogWrite(5, maxDuty / 2);
//	HW_pwm.analogWrite(0, maxDuty);
//	HW_pwm.analogWrite(2, maxDuty / 2);
//	HW_pwm.analogWrite(15, 0);
	HW_pwm.analogWrite(13, maxDuty / 3);
//	HW_pwm.analogWrite(12, 2 * maxDuty / 3);
//	HW_pwm.analogWrite(14, maxDuty);

	debugf("PWM output set on all 8 Pins. Kindly check...");
	debugf("Now Pin 2 will go from 0 to VCC to 0 in cycles.");
	procTimer.initializeMs(100, doPWM).start();
}
```

**Comment by mikee47** [comment]
If the sample doesn't work then there must be something either hardware-related or to do with your dev. setup.

**Comment by verybadsoldier** [comment]
Working now for me, thanks for your support! The only SDK that worked in the end was the embedded `3.0.0` though.
