### ISSUE TITLE
{StationClass,AccessPointClass}::getMAC - undocumented change in behaviour

### ISSUE THREAD

**Issue by q3k** [SmingHub/Sming#1583]
https://github.com/SmingHub/Sming/commit/483f3bfb34bea8cf1247c73be016455673c0e42d changed the behaviour of the getMAC methods on `AccessPointClass` and `StationClass` - they now return a MAC address as `00:11:22:aa:bb:cc`, while previously they returned it as `001122aabbcc`. This is a sudden API change on the `master` branch, seemingly undocumented.

In my opinion, the behaviour change should be rolled back, as it breaks applications that rely on a fixed format of the MAC for identification. I have discovered this due to an application breaking in this exact way.

Preferably, an alternative/extended method would return a MAC object that can be rendered as a string in different formats...

**Comment by mikee47** [comment]
Agreed, have submitted a proposed solution.

**Comment by slaff** [comment]
@q3k Can you check if the fix is working for you? The updated code is **only** in the `develop` branch until we release a new version.
