### ISSUE TITLE
System remember SSID and PWD

### ISSUE THREAD

**Issue by Evgsurf** [SmingHub/Sming#1617]
This is not real issue. I just do not understand how it does work.
I build and flash some project which connect to local WiFi. -Ok , passed.
Later I build and flash Basic_Blink project which has not any! WiFi connections, but as I can see in console, board successfully connects to WiFi and get IP. 
Of couse, flashinit kills WiFi, but the question is, where board save WiFi and how to manage it?

**Comment by mikee47** [comment]
These are stored in a reserved area of flash memory by the Espressif SDK.

**Comment by Evgsurf** [comment]
I see, thank you. Any method to erase it (exclude flashinit) ?

**Comment by mikee47** [comment]
`Any method to erase it (exclude flashinit) ?`

Try `WifiStation.config("", "", false, true)`
