### ISSUE TITLE
Coding style changes: deprecated and override

### ISSUE THREAD

**Issue by mikee47** [SmingHub/Sming#1620]
I'm working on a PR to enforce use of `__ attribute__((deprecated))` throughout the framework; I'm proposing to use a macro `__deprecated` for convenience. The purpose is to ensure the framework (including samples) builds without internally referencing any deprecated items. Travis enforces this. It will also assist users in migrating their code.

The second item is to apply `override` to every overridden virtual function. The purpose is to catch typing errors; using virtual with a mis-spelled method name or parameter type will simply create a new method. Using `override` will throw a warning if the base method isn't declared `virtual`.

One possible point of contention is whether to use `virtual` or `override` on inherited destructors. I'm thinking not, as it doesn't add anything and can actually confuse. virtual destructors do not behave like regular virtual methods, and typos are already flagged by the compiler.

Any other 'modernisations' we can consider?

Thoughts?

**Comment by slaff** [comment]
> One possible point of contention is whether to use `virtual` or `override` on inherited destructors. I'm thinking not, as it doesn't add anything and can actually confuse.

Correct.

**Comment by mikee47** [comment]
What's the thinking on empty overridden destructors? Remove or keep?

**Comment by slaff** [comment]
> What's the thinking on empty overridden destructors? Remove or keep?

Remove.

**Comment by mikee47** [comment]
Is there any justification for using `#include <SmingCore/SmingCore.h>` where `<SmingCore>` is sufficient?

**Comment by slaff** [comment]
> Is there any justification for using `#include <SmingCore/SmingCore.h>` in applications when `#include <SmingCore.h>` is sufficient?

I cannot think of any ... So yes, please, use SmingCore.h  instead of SmingCore/SmingCore.h .
