### ISSUE TITLE
Adafruit_SSD1306 library add support 64 × 48 pixels OLED Shield with I2C

### ISSUE THREAD

**Issue by petrynchyn** [SmingHub/Sming#1621]
To support displays 64 × 48 pixels Adafruit_SSD1306 library I combined it with the code
https://github.com/mcauser/Adafruit_SSD1306/tree/esp8266-64x48 but I do not know how to update Adafruit_SSD1306.patch and send it to SmingHub. Who can tell me how to do this?

**Comment by mikee47** [comment]
Hi, have a look on the Wiki

https://github.com/SmingHub/Sming/blob/develop/CONTRIBUTING.md

Bottom of page for patches:

https://github.com/SmingHub/Sming/blob/develop/AddingExternalSource.md

**Comment by petrynchyn** [comment]
Thanks
