### ISSUE TITLE
Reason for irom offset

### ISSUE THREAD

**Issue by r44083** [SmingHub/Sming#1640]
Hi, I have noticed that linker script "compiler/ld/rboot.rom0.ld" defines irom section with some offset (0x2010) from irom start:
```
  irom0_0_seg :                         org = 0x40202010, len = (1M - 0x2010)
```
**Why is 0x2010, what is located at start address of irom?
For what reason you shift irom start address?**

**Comment by slaff** [comment]
Because we use bootloader. The 0x2010 offset is the space needed for the bootloader and the bootloader config at the beginning of the FLASH. After that offset starts our application.

**Comment by r44083** [comment]
Thnk you slaff.

**Comment by r44083** [comment]
Could you please answer, for what reason you use bootloader? Is it for FOTA?

**Comment by slaff** [comment]
> Is it for FOTA?

Yep.
