### ISSUE TITLE
promiscuous mode in Sming

### ISSUE THREAD

**Issue by icodk** [SmingHub/Sming#1643]
Promiscuous mode works fine in Arduino/esp8266 with both  sdk 1.5.3 [https://www.esp8266.com/viewtopic.php?f=29&t=12127 ](https://www.esp8266.com/viewtopic.php?f=29&t=12127)  and 3.0.0 but I could not make it work with Sming (tried only with 1.5.3). Everything compiles and uploads but the call back function that should be called upon reception of wifi activity is never called. Could it be an issue with  C/C++ calling calling convention ?

**Comment by mikee47** [comment]
I've just pushed #1647 which is a first attempt to provide a WifiSniffer class based on this code. The sniffer initialisation (`WifiSniffer::begin`) cannot be called in `init()`, has to be done after network stack's been initialised (i.e. onReady).

**Comment by slaff** [comment]
@icodk Take a look at the new Wifi_Sniffer sample and give it a try.
