### ISSUE TITLE
Problem with flashInit

### ISSUE THREAD

**Issue by ederjdi** [SmingHub/Sming#1644]
I would like an information if possible about the sming.
I programmed it in the first version of Sming and it worked perfectly, I downloaded version 3.7.0 and now from 3.7.1 when I write the program as blink the basic_wifi works perfectly. But when I burn files that have html the "esp" does not start I tested with the httpServer_configNetwork. This software does not show the network.
What could it be?
I downloaded the site I unzipped got the mingw files all ok
my "ESP" is esp-01, it's some configuration I have to do.

How do flashInit occurs the error of 

**18:46:28 **** Build of configuration Sming for project HttpServer_ConfigNetwork ****
make flashinit 
Flash init data default and blank data.
/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 erase_flash
Connecting...
head: 0 ;total: 0
erase size : 0
/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x7c000 /c/Espressif/ESP8266_SDK/bin/esp_init_data_default.bin 0x4b000 /c/Espressif/ESP8266_SDK/bin/blank.bin 0x100000 /c/tools/Sming/Sming/compiler/data/blankfs.bin
Connecting...
Traceback (most recent call last):
  File "esptool.py", line 567, in <module>
  File "esptool.py", line 160, in connect
Exception: Failed to connect
make: *** [flashinit] Error 255**

when I do the flashboot shows the 
**make[1]: Leaving directory `/c/tools/Sming/Sming/third-party/rboot'
/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x00000 out/firmware/rboot.bin
Connecting...
Erasing flash...
head: 1 ;total: 1
erase size : 4096

Writing at 0x00000000... (50 %) 
Writing at 0x00000400... (100 %) 
Written 2048 bytes in 0.22 seconds (73.80 kbit/s)...

Leaving...**

 and when I do the flash shows the 
**Writing at 0x0012f000... (98 %) 
Writing at 0x0012f400... (98 %) 
Writing at 0x0012f800... (99 %) 
Writing at 0x0012fc00... (100 %) 
Written 196608 bytes in 21.09 seconds (74.59 kbit/s)...

Leaving...
/c/Espressif/utils/Terminal.exe COM4 115200 

18:58:14 Build Finished (took 1m:6s.895ms)**

Remembering that I always clean and then everything
And to record the GPIO 0 is in GND
The model is ESP01
I am using sming on windows in eclipse
Thank you very much for your attention.

**Comment by slaff** [comment]
```
18:46:28 **** Build of configuration Sming for project HttpServer_ConfigNetwork ****
make flashinit
Flash init data default and blank data.
/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 erase_flash
Connecting...
head: 0 ;total: 0
erase size : 0
/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x7c000 /c/Espressif/ESP8266_SDK/bin/esp_init_data_default.bin 0x4b000 /c/Espressif/ESP8266_SDK/bin/blank.bin 0x100000 /c/tools/Sming/Sming/compiler/data/blankfs.bin
Connecting...
````

Looking at the excerpt above I guess you should execute the following commands one after the other. And in between you must make sure that the device is in FLASH mode. The easiest way to do this is to set the correct pins and power off and power on the device. Try the following sequence:

```
; make sure that your ESP01 device is in FLASH mode.

/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 erase_flash

; after success power off and then power of the device. 
; If you haven't touch anything else your ESP01 should be in FLASH mode already. 
; If not, make sure to put it in FLASH mode.

/c/Espressif/utils/ESP8266/esptool.exe -p COM4 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x7c000 /c/Espressif/ESP8266_SDK/bin/esp_init_data_default.bin 0x4b000 /c/Espressif/ESP8266_SDK/bin/blank.bin 0x100000 /c/tools/Sming/Sming/compiler/data/blankfs.bin
```

Also check if your flash size is set correctly. The command above shows me that your flash size is 512 KB. Is that correct? Or you have 256 KB?
