### ISSUE TITLE
Eclipse project files & changes

### ISSUE THREAD

**Issue by 0xPIT** [SmingHub/Sming#167]
Please remove the Eclipse project files from the project, they bloat every changeset, it's annoying.

**Comment by kireevco** [comment]
+

**Comment by kireevco** [comment]
The problem with eclipse users is that they rely heavily on project settings. 

I'd like to migrate to docker/netbeans, do this way all examples will be project-less and easy to add to netbeans.

**Comment by alonewolfx2** [comment]
actually its not a bug. @kireevco ?

**Comment by kireevco** [comment]
@alonewolfx2 from the user prospective it is. What do you think is it?

**Comment by alonewolfx2** [comment]
@kireevco i still using eclipse :)

**Comment by alonewolfx2** [comment]
maybe it can generalization or improvement but not a bug.

**Comment by 0xPIT** [comment]
To me, its a Bug that affects Developer Experience. An improvement could arise only when you change the actual code, not the IDE project files. They should simply not be in the repo.

**Comment by kennpie** [comment]
Not a bug. More an expression of user preference.

I'm using the CHERTS 'UDK'  so I've found it convenient to have eclipse project files with the sming examples. I also like Netbeans.

Maybe the project files could be placed in a separate directory (one for eclipse, one for netbeans, one for vi ;-)  )?

**Comment by kireevco** [comment]
@kennpie what should happen is that sming example should not have __any__ project files. There should be a skeleton Example for Eclipse and Netbeans project on the other hand.

**Comment by alonewolfx2** [comment]
@kireevco still it doesnt a bug you know that.

**Comment by anakod** [comment]
What problem with eclipse projects is?
May be just add to global ignore project properties files what isn't needed for work.

**Comment by kireevco** [comment]
relates to #167

**Comment by hreintke** [comment]
No updates for a long time.
If issue still exist please submit a new issue
