### ISSUE TITLE
Redefine in run time the server address in NTP Client

### ISSUE THREAD

**Issue by dpechman** [SmingHub/Sming#1691]
How can I redefine in runtime the NTP server address in NTPClient ?

**Comment by slaff** [comment]
With 
`void NtpClient::setNtpServer	(	const String & 	server	)`

See more here https://sminghub.github.io/Sming/api/classNtpClient.html#a4205f9144d89e34b43998de6d9d94ff3

**Comment by dpechman** [comment]
great! tks!
