### ISSUE TITLE
  How to feed WDT -  WDT.alive() doesn't seems to work

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#172]
How can I prevent a long running task from resetting device due to the wdt?
I have a loop and I call the WDT.alive()  but doesn't seem to work at all. 
Tried on sdk 1.1.1 and 1.2.

**Comment by Loooopy** [comment]
Check out this: http://tech.scargill.net/esp8266-debug/
Since Espressif SDK 1.01 there are some api changes.

void pp_soft_wdt_stop();    // close software watchdog
void pp_soft_wdt_restart();    // reset software watchdog

**Comment by robotiko** [comment]
DIrect call to Espressif  SDk seem to work (at least with SDK 1.2.0)  but the WDT.alive() doesn't.

**Comment by kireevco** [comment]
@Loooopy @robotiko any findings on this?

**Comment by robotiko** [comment]
@kireevco, stated in the last comment. 
WDT.alive () doesn't work, but  there is a direct SDK solution  that works for SDK 1.2.0  
calling system_soft_wdt_stop();  before the long operation 
and system_soft_wdt_restart(); every  x time  (ie on each cycle on a long loop)
works.

**Comment by kireevco** [comment]
@robotiko perfect summary, thank you.
But should't long operations be avoided as much as possible? Not doing so will block everything.

**Comment by robotiko** [comment]
@kireevco 
Sure. But if needed, WTC.alive() should work as expected or not be available at all.
The point is that current implementation doesn't work and the functionality is present

**Comment by hreintke** [comment]
No update for a long time
Please retest in current develop branch and if issue persists submit a new issue.

**Comment by alonewolfx2** [comment]
@hreintke @robotiko this issue solved with this commit https://github.com/SmingHub/Sming/commit/bffdfc51c80c9e5917a8d19f1d3be4c843bb38b3
