### ISSUE TITLE
Host architecture - BAD PIN

### ISSUE THREAD

**Issue by frankdownunder** [SmingHub/Sming#1720]
In /opt/Sming/Sming/Arch/Host/Core/Digital.cpp, we have

```
static inline bool checkPin(uint16_t pin)
{
	if(pin < 16) {
		return true;
	} else {
		hostmsg("BAD PIN %u", pin);
		return false;
	}
}
```
But a [Wemos D1 Mini](https://www.google.com/search?q=wemos+d1+mini+pinout&client=ubuntu&hs=q8D&channel=fs&tbm=isch&source=iu&ictx=1&fir=HI8V5x7XNyIhnM%253A%252CSnlcq4QotyYk3M%252C_&vet=1&usg=AI4_-kQGWGLdSbahE5I7UK8Rp8jy684mOQ&sa=X&ved=2ahUKEwjIh8zlzOLiAhXSvp4KHbCTBwwQ9QEwAHoECAUQBA#imgrc=HI8V5x7XNyIhnM:
) has pin D0 defined as GPIO 16

Should it instead be
```
	if(pin <= 16)
```

**Comment by mikee47** [comment]
Comparing with `Arch/Esp8266/Core/Digital.cpp`, yes you are correct.

**Comment by slaff** [comment]
@frankdownunder Do you want to create a PR which fixes the issue? I will take care to review it and merge it.

**Comment by frankdownunder** [comment]
OK I will
