### ISSUE TITLE
Permission denied /dev/ttyUSB0

### ISSUE THREAD

**Issue by Derkades** [SmingHub/Sming#1842]
Getting the following error when running `make flash` in `Sming/samples/Basic_Blink`:
```
(!) Spiffs support disabled. Remove 'DISABLE_SPIFFS' make argument to enable spiffs.
Killing Terminal to free /dev/ttyUSB0
make: [/home/robin/esp8266/Sming/Sming/Makefile-rboot.mk:680: kill_term] Killed (ignored)
/home/robin/esp8266/esp-open-sdk/esptool/esptool.py -p /dev/ttyUSB0 -b 115200 write_flash -ff 40m -fm qio -fs 4m 0x00000 out/firmware/rboot.bin 0x02000 out/firmware/rom0.bin
esptool.py v1.2
Traceback (most recent call last):
  File "/home/robin/esp8266/esp-open-sdk/esptool/esptool.py", line 1270, in <module>
    main()
  File "/home/robin/esp8266/esp-open-sdk/esptool/esptool.py", line 1179, in main
    esp = ESPROM(args.port, initial_baud)
  File "/home/robin/esp8266/esp-open-sdk/esptool/esptool.py", line 71, in __init__
    self._port = serial.serial_for_url(port)
  File "/usr/lib/python2.7/dist-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
make: *** [/home/robin/esp8266/Sming/Sming/Makefile-rboot.mk:663: flash] Error 1
```

I have not had any issues manually flashing unrelated .bin files using esptool. Do I need to run make flash as root? My user is in the `dialout` group.

**Comment by Derkades** [comment]
I've tested it with root permissions and it works. Regular esp-open-sdk flashing works without root permissions though, is there any way I can get it to work without sudo?

**Comment by slaff** [comment]
@Derkades You question is better suited for a general ESP8266 forum. But here is what I can do to help you:
- Check if your current user is indeed in the dialout group. Use this command `groups | grep dialout` and paste the output
- When you connect your device check that it is available as /dev/ttyUSB0.  Paste the output of 
`lsusb` and `dmesg | grep USB0`
- Is the ESP8266 in flash mode? Or do you have to set it beforehand?

**Comment by mikee47** [comment]
Have you read https://github.com/espressif/esptool/blob/master/README.md. There's a note about this:

*In Linux, the current user may not have access to serial ports and a "Permission Denied" error will appear. On most Linux distributions, the solution is to add the user to the dialout group with a command like sudo usermod -a -G dialout <USERNAME>. Check your Linux distribution's documentation for more information.*
