### ISSUE TITLE
Question: about make compile directives and automatic recompilation

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1863]
@mikee47 Probably you are the best person to answer this question:

 A project is compiled with the following directives

```
make SMING_ARCH=Host DEBUG_VERBOSE_LEVEL=3
```

The project compiles nicely and the application works as expected.
Trying to compile now without debug information using the command below:

```
make SMING_ARCH=Host 
```

Does not trigger a recompilation of the Sming library. Thus the application is linked against the already created Sming library with the verbose debug information. 
The expected result was to have recompilation of some parts of the Sming library that use DEBUG_VERBOSE_LEVEL and linking against the newly compiled library.

What am I doing wrong?

**Comment by mikee47** [comment]
You'll need to explicitly rebuild Sming. See Note here:

https://sming.readthedocs.io/en/latest/_inc/Sming/index.html#envvar-DEBUG_VERBOSE_LEVEL
