### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by frankdownunder** [SmingHub/Sming#1882]
I use a newer compiler , but it is an easy one to fix. . . 

C+ /opt/Sming/Sming/Arch/Host/Components/hostlib/startup.cpp
In file included from /opt/Sming/Sming/Platform/Clocks.h:15,
                 from /opt/Sming/Sming/Core/PolledTimer.h:28,
                 from /opt/Sming/Sming/Platform/Timers.h:23,
                 from /opt/Sming/Sming/Arch/Host/Components/hostlib/startup.cpp:36:
/opt/Sming/Sming/Core/NanoTime.h: In static member function ‘static String NanoTime::TicksConst<Clock_, ticks_>::toString()’:
/opt/Sming/Sming/Core/NanoTime.h:608:10: error: could not convert ‘ticks_’ from ‘long long unsigned int’ to ‘String’
   return ticks_;
          ^~~~~~
SHOULD AVOID THE IMPLICIT CAST
   return String(ticks_);

make[1]: *** [/opt/Sming/Sming/component-wrapper.mk:156: startup.o] Error 1
make: *** [/opt/Sming/Sming/project.mk:359: hostlib-build] Error 2

**Comment by slaff** [comment]
Should be fixed with PR #1883
