### ISSUE TITLE
Example of receive and parse JSON via Serial

### ISSUE THREAD

**Issue by piperpilot** [SmingHub/Sming#189]
Does anyone have a good example of how to receive and parse JSON received via serial from another microcontroller?  Idea being that it can be manipulated/stored and then served up via http server.

**Comment by anakod** [comment]
It should be same as parse JSON from file. PLease look https://github.com/anakod/Sming/blob/master/HttpServer_ConfigNetwork/include/AppSettings.h example

**Comment by piperpilot** [comment]
Thanks...yeah, I got that much...I'm more interested in if anyone has an efficient way to detect incoming JSON via the serial stream and then hand it off to the parser when the full message has been received.  I am working on a method to look at characters... for every { increase a counter and every } decrease it...then when the counter is zero...take the message.

Anyone have a better solution?

**Comment by anakod** [comment]
I think this example should be useful for input stream: https://github.com/anakod/Sming/blob/master/Basic_Serial/include/SerialReadingDelegateDemo.h
You can check input stream for NULL char and than split reading.

**Comment by avr39-ripe** [comment]
https://github.com/avr39-ripe/ValveControl/blob/master/app/application.cpp#L52
Here is my dirty, but fully working code to receive and parse some json from arduino. Feel free to ask anything if you find it useful :)

**Comment by kireevco** [comment]
I like that.

@avr39-ripe hey, do you think you could submit an example for Sming that will contain two codebases: sming and arduino?

**Comment by kireevco** [comment]
@avr39-ripe we need your heroic help here! :)

**Comment by avr39-ripe** [comment]
I will try to compose such example from pieces of my own test code..

**Comment by kireevco** [comment]
This will be very very helpful. Thank you!

**Comment by hreintke** [comment]
Sming repository is currently being restructured and cleaned. This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
