### ISSUE TITLE
OpenWifi not working

### ISSUE THREAD

**Issue by etmmahi** [SmingHub/Sming#1891]
Try example Basic_Wifi  with settings:

export WIFI_SSID="OpenNetwork"
export WIFI_PWD=""

The compile will fail because WIFI_PWD is not taken into the compile flags.
This happens due to the 
`ifdef WIFI_PWD 
`
check in component.mk

pse fix

Martijn

**Comment by mikee47** [comment]
```
make WIFI_SSD=OpenNetwork WIFI_PWD=
```

**Comment by mikee47** [comment]
I see what you mean.

**Comment by mikee47** [comment]
@etmmahi This should sort problem if you want to try it:

```
diff --git a/Sming/component.mk b/Sming/component.mk
index d63052f23..db370918e 100644
--- a/Sming/component.mk
+++ b/Sming/component.mk
@@ -67 +67 @@ endif
-ifdef WIFI_PWD
+ifneq ($(origin WIFI_PWD),undefined)
```
