### ISSUE TITLE
error: "WIFI_PWD" redefined [-Werror]

### ISSUE THREAD

**Issue by teicors** [SmingHub/Sming#1901]
Hi,
I updated sming to the latest version by git branch develop and I catch the error.
I did the following steps:

```
cd samples/HttpClient
make
make component-clean clean
make

```
and now I catch the error. 
the HttpClient is vanilla from git clone <Sming>. No one modification.
The same error on my projects.

**Comment by mikee47** [comment]
See #1892. The fix is to ensure WIFI_SSID is defined. The error message could be clearer but in essence it's appropriate  I think.

The use of these variables is really only for basic samples and one-off applications. In deployable devices a more sophisticated mechanism for managing connection information is needed.

**Comment by teicors** [comment]
Yes, I know. I put for my gadgets the ssid and password in an external file with the right value. The error is not related to a password empty, but to the duplicate (redefine) of password. In the example I expect an error like "SSID not defined" and not redefine of password.

**Comment by slaff** [comment]
@mikee47 The following change can be done: In Sming/component.mk replace the setting of WIFI_PASS from:
```
ifdef WIFI_SSID
	APP_CFLAGS			+= -DWIFI_SSID=\"$(WIFI_SSID)\"
endif
ifneq ($(origin WIFI_PWD),undefined)
	APP_CFLAGS			+= -DWIFI_PWD=\"$(WIFI_PWD)\"
endif
```

to 

```

**Comment by teicors** [comment]
Not exactly.. an undefined WIFI SSID is not catched.
Now I don't report any duplicate, neither the WIFI SSID voluntary missed as verify the solution.

**Comment by mikee47** [comment]
@slaff That's a good idea, thanks.

@teicors 
> undefined WIFI SSID is not catched.

We can fix that for all the samples:

```
#ifndef WIFI_SSID
static_assert(false, "Please define WIFI_SSID and, if required, WIFI_PWD.");
#define WIFI_SSID "WIFI_SSID"
#endif
```
