### ISSUE TITLE
Serial,printf, debugf uint64_t (long long)

### ISSUE THREAD

**Issue by kmihaylov** [SmingHub/Sming#1921]
Hello, I'm using some >32bit numbers, (uint64_t).
However when I use debugf to print some system information only the first 4 bytes are printed.

May you enlighten me whether this is some bug or I'm missing some parameter?

Thanks!

EX: debugf("%llx", 0x4040404040);

**Comment by mikee47** [comment]
longlong parameter types aren't currently supported; You'll need to work around this:

```
uint64_t value = 0x4040404040ULL;
debugf("%x%08x", uint32_t(value >> 32), uint32_t(value));
```

An easier way is using methods of `Serial` (or Print), if necessary wrapping with `#ifndef SMING_RELEASE`, etc.

**Comment by kmihaylov** [comment]
God bless you!
