### ISSUE TITLE
IoT protocol AllJoyn. 

### ISSUE THREAD

**Issue by STASIUK** [SmingHub/Sming#193]
Newly Microsoft presented windows 10 and with it the windows 10 sdk.
It includes Open Source protocol for the Internet of things which is called AllJoyn.
He is becoming popular and enables all device (pc, tablet, tv, arduino, raspberry, esp8266 and other) communicate with each other one protocol.
I ask you to consider a proposal to add this protocol in the esp8266 module. 
What do you think?

**Comment by alonewolfx2** [comment]
i think it would be very good

**Comment by kireevco** [comment]
@STASIUK Sounds good. 
But do you think this is more important than working HTTPS #99 or stable HTTP #154 ?

Sming team doesn't have enough resources and unfortunately right now we need to set priority for everything.

**Comment by alonewolfx2** [comment]
1-Stable http
2-https
3-stable mqtt
4-..

**Comment by kireevco** [comment]
@alonewolfx2 yeah, I agree with the priorities list.

**Comment by ajaybhargav** [comment]
+1 for this.. I will see if I can port thin client to Sming

**Comment by jcherrabi** [comment]
+10

**Comment by STASIUK** [comment]
+10!!!! For .net developers and other!
