### ISSUE TITLE
Missing function to read restart reason

### ISSUE THREAD

**Issue by etmmahi** [SmingHub/Sming#1953]
Hi,

is there a function to read the reset reason?
I can use this to debug restarting nodes.

Martijn

**Comment by mikee47** [comment]
You can use `system_get_rst_info()`. See the [NON-OS SDK reference](https://www.espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf) for details.

**Comment by etmmahi** [comment]
Thanks,

I missed this

Closing the PR
