### ISSUE TITLE
flashinit fails with clean project

### ISSUE THREAD

**Issue by fooker** [SmingHub/Sming#1966]
Looks like flashinit requires the `esp8266` component to be build before it can run so it will find `$(SDK_BASE)/bin/esp_init_data_default.bin`. If flashinit is executed in a clean tree, the file is missing.

**Comment by mikee47** [comment]
True. But then other things will be missing too, like spiffy.

In general build the framework is the first step before anything else.

Do you think the documentation requires clarification on this?

**Comment by fooker** [comment]
@mikee47 Maybe the build should be a dependency on that target?
