### ISSUE TITLE
Windows 10 debug problem

### ISSUE THREAD

**Issue by kwis2** [SmingHub/Sming#1972]
I have installed Sming on win 10 with Manual Windows Installation method, and there is no `xtensa-lx106-elf-gdb` in  `/Espressif/xtensa-lx106-elf/bin` folder nor even in whole `Espressif` folder.
I think it is some problem with UDK installation (?) `Espressif-ESP8266-DevKit-v2.2.1-x86.exe`

**Comment by mikee47** [comment]
Check out the documentation here
https://sming.readthedocs.io/en/latest/_inc/Sming/Arch/Esp8266/Components/gdbstub/index.html#gdb

(Just type GDB into the search)
