### ISSUE TITLE
Default MQTT Payload Parser can't handle empty messages

### ISSUE THREAD

**Issue by fooker** [SmingHub/Sming#1975]
MQTT supports sending messages without a payload (the remaining bytes after the variable headers are zero). If such a message is received by the `MqttClient` and processed by the default `MqttPayloadParser`, the client dies and does not accept any further messages.

At a first sight, it looks like `malloc` is called with `message->publish.content.length` which is `0` in such a case. Thus leading `malloc` to return `nullptr` and the following sanity-check to fail.

**Comment by slaff** [comment]
@fooker Can you send a PR with your suggested fix?

**Comment by fooker** [comment]
It looks like fixing the `payloadParser` is not enough. The `on_data_payload` and `on_data_end` callbacks will be called way to late (the are called if a follow-up message is received).

I've opened an associated issue in the according library: https://github.com/slaff/mqtt-codec/issues/3

**Comment by fooker** [comment]
@slaff If https://github.com/slaff/mqtt-codec/pull/4 gets merged, there is no need for change in Sming.

Another way to solve this is not to skip the callbacks on empty messages, but make them all be called with zero length. In such a case, I will come up with a PR.

**Comment by fooker** [comment]
@slaff will this be back-ported to a 4.0.x release?
