### ISSUE TITLE
Documentation 'adding external sources' out of date

### ISSUE THREAD

**Issue by mikee47** [SmingHub/Sming#1980]
https://sming.readthedocs.io/en/latest/contribute/external-sources.html

This page hasn't yet been updated for Sming 4.0.0.

**Comment by mikee47** [comment]
@slaff Hope you haven't spent time on this one yet, I've got it included in an update I'll be pushing out shortly.

**Comment by slaff** [comment]
> Hope you haven't spent time on this one yet

Not yet. 

>  I've got it included in an update I'll be pushing out shortly.

Great, thanks a lot in advance!

**Comment by mikee47** [comment]
Closed via #1987
