### ISSUE TITLE
Write guide to building a Component

### ISSUE THREAD

**Issue by mikee47** [SmingHub/Sming#2003]
I'll get this added to the documentation shortly, but in the meantime here is a list of some relevant issues and comments which I'll use for it:

https://github.com/SmingHub/Sming/pull/1992#issuecomment-564677869
https://github.com/SmingHub/Sming/pull/1724#issuecomment-504473709
#2002

**Comment by slaff** [comment]
Done in #2121. The next step should be to create a make target that is creating a skeleton component. Acoompanied with another target that should create a skeleton application.
