### ISSUE TITLE
Valgrind invalid Read error on TcpConnection

### ISSUE THREAD

**Issue by kpishere** [SmingHub/Sming#2016]
I see the following Valgrind error on the sample HttpServer_Bootstrap (and in my own program but the sample code result is here).

Note that I'd made the error disappear by commenting out this delete statement. But, further down, is the leak report -- there are leaks with this change.

Is this a problem or not?  To me, it looks like reading the pointer tcp is causing the error.  Is this an error to ignore?

TcpConnection.h:191
-----------------------

inline void checkSelfFree()
        {
                if(tcp == nullptr && autoSelfDestruct) {
                //      delete this;
                }
        }

----
IF_UP, AP: Host WiFi
IP_CHANGE, ip: 192.168.13.10, netmask: 255.255.255.0, gateway: 192.168.13.1
CUartServer::thread_routine: Uart #0 socket open
CUartServer::thread_routine: Uart #1 socket open
==10322== Invalid read of size 4
==10322==    at 0x12C6DC: TcpConnection::checkSelfFree() (TcpConnection.h:191)
==10322==    by 0x12CFC8: TcpConnection::internalOnPoll() (TcpConnection.cpp:507)
==10322==    by 0x1153BE: tcp_slowtmr (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x11B6D4: tcpip_tcp_timer (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x11BB25: sys_check_timeouts (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10EF0F: host_lwip_service (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10C977: main (startup.cpp:247)
==10322==  Address 0x4cfcc24 is 4 bytes inside a block of size 680 free'd
==10322==    at 0x4835F47: operator delete(void*, unsigned int) (vg_replace_malloc.c:581)
==10322==    by 0x130BA2: HttpServerConnection::~HttpServerConnection() (HttpServerConnection.h:49)
==10322==    by 0x12D581: TcpClient::close() (TcpClient.cpp:148)
==10322==    by 0x12C68D: onPoll (TcpConnection.cpp:154)
==10322==    by 0x12C68D: TcpConnection::onPoll() (TcpConnection.cpp:149)
==10322==    by 0x12CFBD: TcpConnection::internalOnPoll() (TcpConnection.cpp:506)
==10322==    by 0x1153BE: tcp_slowtmr (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x11B6D4: tcpip_tcp_timer (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x11BB25: sys_check_timeouts (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10EF0F: host_lwip_service (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10C977: main (startup.cpp:247)
==10322==  Block was alloc'd at
==10322==    at 0x4834CAB: operator new(unsigned int) (vg_replace_malloc.c:328)
==10322==    by 0x12DA15: HttpServer::createClient(tcp_pcb*) (HttpServer.cpp:40)
==10322==    by 0x12A87A: TcpServer::onAccept(tcp_pcb*, signed char) (TcpServer.cpp:80)
==10322==    by 0x12A207: TcpServer::staticAccept(void*, tcp_pcb*, signed char) (TcpServer.cpp:148)
==10322==    by 0x118ED5: tcp_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x1241DC: ip4_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x125391: ethernet_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x125A85: tapif_select (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10EF0A: host_lwip_service (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==10322==    by 0x10C977: main (startup.cpp:247)
==10322== 

.
.
.
==13572== 
==13572== HEAP SUMMARY:
==13572==     in use at exit: 652 bytes in 7 blocks
==13572==   total heap usage: 1,912 allocs, 1,905 frees, 99,511 bytes allocated
==13572== 
==13572== LEAK SUMMARY:
==13572==    definitely lost: 0 bytes in 0 blocks
==13572==    indirectly lost: 0 bytes in 0 blocks
==13572==      possibly lost: 0 bytes in 0 blocks
==13572==    still reachable: 652 bytes in 7 blocks
==13572==         suppressed: 0 bytes in 0 blocks
==13572== Reachable blocks (those to which a pointer was found) are not shown.
==13572== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==13572== 

==================
. With delete commented out ...
.
.
==11948== 
==11948== HEAP SUMMARY:
==11948==     in use at exit: 9,128 bytes in 192 blocks
==11948==   total heap usage: 1,655 allocs, 1,463 frees, 89,421 bytes allocated
==11948== 
==11948== 8,476 (4,080 direct, 4,396 indirect) bytes in 6 blocks are definitely lost in loss record 23 of 23
==11948==    at 0x4834CAB: operator new(unsigned int) (vg_replace_malloc.c:328)
==11948==    by 0x12D997: HttpServer::createClient(tcp_pcb*) (HttpServer.cpp:40)
==11948==    by 0x12A87A: TcpServer::onAccept(tcp_pcb*, signed char) (TcpServer.cpp:80)
==11948==    by 0x12A207: TcpServer::staticAccept(void*, tcp_pcb*, signed char) (TcpServer.cpp:148)
==11948==    by 0x118ED5: tcp_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==11948==    by 0x1241DC: ip4_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==11948==    by 0x125391: ethernet_input (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==11948==    by 0x125A85: tapif_select (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==11948==    by 0x10EF0A: host_lwip_service (in /opt/Sming/samples/HttpServer_Bootstrap/out/Host/debug/firmware/app)
==11948==    by 0x10C977: main (startup.cpp:247)
==11948== 
==11948== LEAK SUMMARY:
==11948==    definitely lost: 4,080 bytes in 6 blocks
==11948==    indirectly lost: 4,396 bytes in 179 blocks
==11948==      possibly lost: 0 bytes in 0 blocks
==11948==    still reachable: 652 bytes in 7 blocks
==11948==         suppressed: 0 bytes in 0 blocks
==11948== Reachable blocks (those to which a pointer was found) are not shown.
==11948== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==11948==

**Comment by slaff** [comment]
Fixed in #2017.
