### ISSUE TITLE
Sming on FreeBSD

### ISSUE THREAD

**Issue by kmihaylov** [SmingHub/Sming#2079]
Hello. I'm a bit behind the latest build environment requirements. SMING_HOME is clear. ESP_HOME in the past was esp-open-sdk build. But it changed few months ago and now uses the toolchains in SmingTools. However there are Linux and Windows binaries, and the source code archive is related to MinGW.

I remembered that Sming changed from native esp-open-sdk to ESP Quick Toolchain. Do you prepare Sming's toolchain binaries (in SmingTools) following the procedure as noted in https://github.com/earlephilhower/esp-quick-toolchain ?

Thanks!

**Comment by slaff** [comment]
> Do you prepare Sming's toolchain binaries ?

We just use the already pre-compiled binaries from the `earlephilhower/esp-quick-toolchain` project.  @mikee47 can you confirm this?

**Comment by mikee47** [comment]
That's right. See https://sming.readthedocs.io/en/latest/arch/esp8266/getting-started/eqt.html for details.

**Comment by kmihaylov** [comment]
https://github.com/earlephilhower/esp-quick-toolchain/issues/13
