### ISSUE TITLE
Another enhancement suggestion: aRest

### ISSUE THREAD

**Issue by MrZANE42** [SmingHub/Sming#21]
Hi
The https://github.com/marcoschwartz/aREST has just gotten ESP8266 support and would be a nice addition to the sming framework IMHO.

**Comment by robotiko** [comment]
+1

**Comment by smitjj** [comment]
+1, please

**Comment by hreintke** [comment]
This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
