### ISSUE TITLE
Basic Air Update -Power Down

### ISSUE THREAD

**Issue by crosofg** [SmingHub/Sming#213]
Is they any way to make the over the air update failsafe? If power goes down in the middle of writing to  flash, is there a way to revert back?

Can we add an enhancement which partitions the memory into two and copies the firmware in the unused part.And if the write process is successful only then esp will reboot with that firmware. Just like the user1.bin and user2.bin as given in the espressif documentation

**Comment by crosofg** [comment]
Can we add an enhancement which partitions the memory into two and copies the firmware in the unused part.And if the write process is successful only then esp will reboot with that firmware. Just like the user1.bin and user2.bin as given in the espressif documentation

**Comment by kireevco** [comment]
@anakod @alonewolfx2 @hreintke 
This is a sane suggestion, that everyone was talking about multiple times. What stops us from doing this?

**Comment by alonewolfx2** [comment]
time :)

**Comment by hreintke** [comment]
@kireevco : I have no experience in OTA and memory/flash allocation. Focusing on tcp/http/debug/commandprocessing for now.

**Comment by robotiko** [comment]
Closing: New OTA update using rBoot is failsafe and the recommended way for OTA.
