### ISSUE TITLE
Build and flash give no error / warning if firmware size exceeds the maximum accepted by device

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#221]
All goes ok and flashes, but device gets corrupted an don't boot.

**Comment by kireevco** [comment]
@robotiko sounds like a question for https://github.com/themadinventor/esptool
@anakod @alonewolfx2 Is there a way to check what is the max flash / should we check based on spi size / bin file?

**Comment by alonewolfx2** [comment]
@kireevco good question. propably we can check firmware size with one script in makefile.

**Comment by hreintke** [comment]
Sming repository is currently being restructured and cleaned. This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
