### ISSUE TITLE
MQTT TCP connection closes randomly..

### ISSUE THREAD

**Issue by dmarkey** [SmingHub/Sming#222]
onReadyToSendData: 3
TCP received: (null)
TCP connection closing
-TCP connection

Then on the mosquitto side:

1440081554: Socket error on client SmartController-10364675, disconnecting.

Using the latest Sming and the latest SDK.

**Comment by ADiea** [comment]
+1

**Comment by dmarkey** [comment]
http://dmarkey.com/~dmarkey/file.pcap here is a trace with the problem. Seems to be not handling a re-transmission properly?

**Comment by kireevco** [comment]
@dmarkey thank you so much for providing trace. @anakod what is requried to troubleshoot / fix this?

**Comment by tve** [comment]
I'm not seeing any problem highlighted by the packet trace. There's a packet missing in the trace according to wireshark. In the end, the server closes the connection cleanly. If the missing packet (according to the sequence numbers) wasn't sent by the esp8266 I would suspect a buffering problem.

**Comment by dmarkey** [comment]
Well the socket isnt closed cleanly on the server side:

Socket error on client SmartController-10364675, disconnecting.

**Comment by m0bygit** [comment]
@dmarkey @ADiea I had a similar problem with Mqtt. My problem was solved with commit 19bcf85add9e6fb4cbe7c61065c4129d9abcb496.

**Comment by hreintke** [comment]
Closed. Fixed by #550
