### ISSUE TITLE
ScreenOLED_SSD1306 sample fails to build

### ISSUE THREAD

**Issue by etmmahi** [SmingHub/Sming#2256]
Hi guys,

I just tried to build the sample ScreenOLED_SSD1306 from the develop branch.
It fails at:
```
.../Sming/Sming/Libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::drawFastHLineInternal(int16_t, int16_t, int16_t, uint16_t)':
.../Sming/Sming/Libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:635:21: error: ISO C++17 does not allow 'register' storage class specifier [-Werror=register]
  635 |   register uint8_t *pBuf = buffer;
```

It seems the patch for the Adafruit_SSD1306 Library needs to be upgraded to remove all the register keywords.
This change needs to be backported to the lts versions.

Best
Martijn

**Comment by mikee47** [comment]
Yes, probably needs fixing. You can build the sample with `make STRICT=1` and the errors will be converted to warnings.

**Comment by etmmahi** [comment]
The STRICT=1 makes compilation work again.

However fix is still needed. When I remove all the 'register' keywords, the code also compiles without problems/warnings

**Comment by slaff** [comment]
@etmmahi If you want create a PR with the latest `Adafruit_SSD1306` library version and updated sample.

**Comment by etmmahi** [comment]
With PR #2259 the sample application ScreenOLED_SSD1306 builds without any issues. pse merge
