### ISSUE TITLE
Manipulation of the data format JSON large size

### ISSUE THREAD

**Issue by STASIUK** [SmingHub/Sming#246]
Need help with a large file JSON format (64 objects).
Problem: Save data from VECTOR<User> Users; in a local file in json format.
But i have 64 objects, and as I understand, I do not have heap_size.
Could not somebody help me?

**Comment by hreintke** [comment]
Sming repository is currently being restructured and cleaned. This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
