### ISSUE TITLE
File system not getting initialized for HttpServer_Websocket server example

### ISSUE THREAD

**Issue by kteza1** [SmingHub/Sming#254]
```
Leaving...
python -m serial.tools.miniterm /dev/tty.SLAB_USBtoUART 115200
--- Miniterm on /dev/tty.SLAB_USBtoUART: 115200,8,N,1 ---
--- Quit: Ctrl+]  |  Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
```

No prints after this.

I removed `files` folder which contains `index.html` and filesystem seems to be getting initialized.  

Anyone else facing this issue?

**UPDATE: Seems to be Mac OSX specific issue. Working fine in Ubuntu**

**Comment by hreintke** [comment]
We will need more information to be able to check this issues.

If the problem persist, please submit a new issue with additional information.
