### ISSUE TITLE
Setting DEBUG_PRINT_FILENAME_AND_LINE not working correctly

### ISSUE THREAD

**Issue by IanAber** [SmingHub/Sming#2581]
If I set DEBUG_PRINT_FILENAME_AND_LINE=1 I get the line number in the debug output but NOT the file name. For example...
`[:44] Found 11 access points:

[:47] Starting the access point
mode : sta(2c:3a:e8:17:87:57) + softAP(2e:3a:e8:17:87:57)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
[:92] AP configuration loaded
[:314] scan completed: 11 found`

**Comment by slaff** [comment]
@ADiea do you want to look at this issue?
