### ISSUE TITLE
Preparation for Release 5.0 (was 4.8.0)

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#2597]
This issue is created to collect all the tasks we need to do before the 5.0 release (was initially scheduled as 4.8.0 release).

### Source Code
- [x] Update Sming/Core/SmingVersion.h.
- [x] Update Readme.md.
- [x] Merge develop into master.
- [x] Tag the source code in the master branch.
- [x] Add upgrade document

New features
------------------
- #2607
- #2614
- #2612
- #2629 
- #2623
- #2599
- #2647

Improvements
-------------------
- #2601

Bug fixes
------------
- #2613
- #2610
- #2609
- #2604
- #2603
- #2602
- #2600
- #2640

Changes
-----------

Deprecations
-----------------

Breaking Changes
------------------------

Security
-----------

All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/33)

**Comment by slaff** [comment]
@mikee47 is your [USB](https://github.com/mikee47/Sming/commits/feature/usb) library ready for merging?

**Comment by mikee47** [comment]
@slaff Nearly, needs documenting.

**Comment by mikee47** [comment]
@slaff I've just noticed https://www.katacoda.com/ has been shuttered...

**Comment by slaff** [comment]
> I've just noticed https://www.katacoda.com/ has been shuttered...

Yes, unfortunately. May be we can replace it with a gitpod or similar environment plus a text tutorial. I have started long ago some tests, see branch[ feature/devcontainers](https://github.com/SmingHub/SmingSkeletonApp/tree/feature/devcontainers) in SmingSkeletonApp, but haven't had the time to finish and polish.
