### ISSUE TITLE
Esp32 Wifi Station Implementation bug

### ISSUE THREAD

**Issue by mr-sven** [SmingHub/Sming#2598]
Hi,
I faced an issue regarding the station implementation.
On Esp32 the `esp_wifi_start` is not called if the current mode read from storage is already `WIFI_MODE_STA` or `WIFI_MODE_APSTA`:
https://github.com/SmingHub/Sming/blob/c3684aba275263c44be827bf9016ab5beb814afc/Sming/Components/Network/Arch/Esp32/Platform/StationImpl.cpp#L130

Looks like c&p error from the else branch lower.

**Comment by slaff** [comment]
@mr-sven can you submit a PR with the suggested fix?
