### ISSUE TITLE
Identifying code quality issues e.g. unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [SmingHub/Sming#2616]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AccessPointImpl::config](https://github.com/SmingHub/Sming/blob/112da39f9d718a37e937de8825f6faf4a1c45cc1/Sming/Components/Network/Arch/Esp8266/Platform/AccessPointImpl.cpp#L85 "AccessPointImpl::config function")
- [doUpgrade](https://github.com/SmingHub/Sming/blob/2345c3e8aacd94af917441f93f55e9a60dd7cee3/samples/Basic_Ota/app/application.cpp#L51 "doUpgrade function")
- [YeelightBulb](https://github.com/SmingHub/Sming/blob/07ecd3bdf33f5b56ec1c32c9587df456ffaa4c07/Sming/Libraries/Yeelight/YeelightBulb.cpp#L14 "Destructor for YeelightBulb")

**Comment by slaff** [comment]
@elfring can you prepare a PR with the suggested changes?

**Comment by slaff** [comment]
> Some of those should be using std::unique_ptr as well :-)

@mikee47 do you want to create a PR with the changes?

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by slaff** [comment]
Fixed in #2643

**Comment by mikee47** [comment]
I'm reopening this issue as it is not yet fully resolved. clang-tidy is undoubtedly useful, especially if it can be integrated into the build system in some way. Whether automated code changes are appropriate is another matter.... 

Are there any other offline code checking tools we might consider?

**Comment by elfring** [comment]
[Another update candidate was left over](https://github.com/SmingHub/Sming/blob/02835d8f4e539931c46b16191a6b38f7c0a4b04e/Sming/Components/Network/src/Network/TelnetServer.cpp#L34 "Update candidate: TelnetServer::enableCommand()").

**Comment by mikee47** [comment]
@elfring
