### ISSUE TITLE
faulty flash size detected by boot.esp32c3

### ISSUE THREAD

**Issue by pljakobs** [SmingHub/Sming#2618]
I hope this is not another "you're holding it wrong" issue but I also believe it's esptool, not sming, so I've opened an issue over there, this is just for information:
https://github.com/espressif/esptool/issues/837

**Comment by mikee47** [comment]
#2613 offers a brief explanation of the behaviour. For Sming, the bootloader is built with the flash size setting configured in the hardware config file. If this changes, you should do a make `sdk-config-clean` then re-build/flash the bootloader.

**Comment by pljakobs** [comment]
Interesting.
I had rebased my pwm stuff to the recent develop branch and then started to get this issue - with no other changes anywhere. 

My .hw file is configured for 4M - is that what you are referring to?
If I change this to 2M, things work fine, albeit the bootloader complains that the binary doesn't use all available flash.
I will try the sdk-clean.

**Comment by pljakobs** [comment]
ok, I don't understand it, but sdk-config-clean seems to have done the trick. I guess there was something that was still lingering around.
