### ISSUE TITLE
ssl no verify

### ISSUE THREAD

**Issue by natxopedreira** [SmingHub/Sming#2641]
Hello

Sorry as this is more a question that an issue, i would like to know if this is possible to do with this framework.

Use ssl/mqtt in "insecure" mode?
Set ssl to not verify, basically i want to use mqtt through port 8883 with ssl without validation.

Hope you get what i mean.

I know that can be done in esp32-idf but i prefer a c++ approach if possible, and the idea to be able to switch between rp2040/esp32 platforms sounds cool.

Here there is a method, that inline doc say so i assume that must be a way to say... not required
```
bool validateCertificate();
	/**
	 * @brief Called by SSL adapter when certificate validation is required
	 * @retval bool true if validation is success, false to abort connection
	 * @note SSL Internal method
	 */
```

But later i see that if this check its false it returns an SSL_ERROR_BAD_CERTIFICATE
https://github.com/SmingHub/Sming/blob/f2916177f3bb7f421ad63d0d9e7a63aed913fb95/Sming/Components/ssl/Axtls/AxConnection.cpp#L59

So maybe it not possible to avoid validation?

Thanks

**Comment by slaff** [comment]
@natxopedreira Take a look at the [MqttClient sample](https://github.com/SmingHub/Sming/tree/develop/samples/MqttClient_Hello).  In the [sample on line 100](https://github.com/SmingHub/Sming/blob/1a34cfa1b0b460e8cd26d557bdad40ffa8d15307/samples/MqttClient_Hello/app/application.cpp#L100) you will see how to disable the standard certificate validation:

https://github.com/SmingHub/Sming/blob/1a34cfa1b0b460e8cd26d557bdad40ffa8d15307/samples/MqttClient_Hello/app/application.cpp#L100

And if you don't want to have any other forms of validation you can delete line 101

https://github.com/SmingHub/Sming/blob/1a34cfa1b0b460e8cd26d557bdad40ffa8d15307/samples/MqttClient_Hello/app/application.cpp#L100

So in your case the SSL initialization should look like this:
```cpp
	mqtt.setSslInitHandler([](Ssl::Session& session) {
		session.options.verifyLater = true;
	});
```

**Comment by natxopedreira** [comment]
Ook, got it, so:

this will set to not verify during handshake
`session.options.verifyLater = true; `

and this void to use any cert
`session.keyCert.assign(default_private_key, sizeof(default_private_key), default_certificate, `


Thank you @slaff i went another route as a fast solution, but will give this a go as this framework is very interesting
