### ISSUE TITLE
Link to interactive documentation (on katacoda) is defunct

### ISSUE THREAD

**Issue by iokhahon** [SmingHub/Sming#2660]
The link on the Sming github page to https://www.katacoda.com/slaff/scenarios/sming-host-emulator  takes you to the following message.

> Thank you to the Katacoda community for your years of support. Katacoda.com is now closed. Learn more about this decision and
> access interactive learning on O’Reilly [here](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html).

There are very few resources on the internet for new Sming users, a broken link like this suggests the project is a dead and nobody cares about attracting new users/contributors.

**Comment by mikee47** [comment]
Looks like Killercoda supports Katacoda scenerios directly. Here's a test https://killercoda.com/smingdev/scenario/host
@slaff This requires configuration for your katacoda-scenarios repo. Do you want to update?

**Comment by slaff** [comment]
> Do you want to update?

@mikee47 yep, I am doing it. The new Sming host emulator link should be: https://killercoda.com/slaff/scenario/sming-host-emulator. And the ESP-32 should be under https://killercoda.com/slaff/scenario/sming-on-esp32. Is this enough or I should do something more?

**Comment by mikee47** [comment]
@slaff Thank you - looks good! I've had a quick run through the esp32 scenario and works as-is, though it does need updating as IDF versions have moved on.
I don't think katacoda required users to log in first, but killercoda definitely does.
