### ISSUE TITLE
HttpServer_WebSockets disconnect when ESP try to send binary data

### ISSUE THREAD

**Issue by williamesp2015** [SmingHub/Sming#267]
I tested HttpServer_WebSockets example and I found two main issues 1) disconnecting ESP when EXP try to send binary data and 2) can not continuously send data string more than 5 times/sec the result is:"ERROR: undefined" and consequently disconnected.

**Comment by williamesp2015** [comment]
Websocket is capable to send and receive data very fast (https://www.youtube.com/watch?v=8ISbmQTbjDI) please see https://github.com/cnlohr/ws2812esp8266 If Sming developers be interested, Sming Websocket could be the best platform for Websocket server and client

**Comment by hreintke** [comment]
You will need to supply more information and log information to be able to check

I will close this issue, I the problems persist please submit a new one with additional info.
