### ISSUE TITLE
The interactive tutorial for using host emulator is no longer available 

### ISSUE THREAD

**Issue by xeonqq** [SmingHub/Sming#2698]
The interactive tutorial link on the following page for using host emulator is no longer valid 
https://sming-slaff.readthedocs.io/en/fix-docs-with-esp32/arch/host/host-emulator.html

**Comment by slaff** [comment]
The correct link is https://killercoda.com/slaff/scenario/sming-host-emulator. @xeonqq thank you for reporting. I will create a fix shortly...

**Comment by xeonqq** [comment]
Thank you!
