### ISSUE TITLE
Request for COAP server and client

### ISSUE THREAD

**Issue by kteza1** [SmingHub/Sming#270]
I believe CoAP should be present in Sming.

**Comment by robotiko** [comment]
+1  CoAP is a great addition to IOT platform.

**Comment by dereulenspiegel** [comment]
+1

**Comment by flexiti** [comment]
By the way :)

http://www.slideshare.net/paolopat/internet-ofthingsprotocolswar

**Comment by HaknCo** [comment]
I started to look into this issue.
Lobaro CoAP Server (https://github.com/Lobaro/lobaro-coap) worked almost out-of-the-box.
You can find my code here https://github.com/HaknCo/sming-coap
By the way, currently I am working on a CoAP client, which is based on the NodeMCU code, which again seems to be based on the microcoap project.

**Comment by kteza1** [comment]
@HaknCo That would be a great contribution to Sming

**Comment by HaknCo** [comment]
Just finished the CoAP client !!!

Server and Client can be found here : https://github.com/HaknCo/sming-coap.
GET, POST, PUT, DELETE work.
OBSERVE and BLOCKWISE will follow hopefully.

Let me know if it works for you.

**Comment by ystrem** [comment]
Hi, great work ! Currently I'm using MQTT, is there any big think about CoAP that I want to change it to CoAP ?

**Comment by HaknCo** [comment]
It depends, as long as you are interested in PubSub, MQTT is a good protocol. But if you are interested in Internet resources, meaning if you have URIs,
you definitely need CoAP or HTTP.

CoAP follows REST principles, thus it easy to integrate into Web Applications through proxies.

KR

**Comment by hreintke** [comment]
Closing. If cloapp client is finished please submit a PR for further discussion
