### ISSUE TITLE
On ESP32 GPIO32 GPIO33 can't be used as output

### ISSUE THREAD

**Issue by profjmer** [SmingHub/Sming#2715]
I seems we can't use normal pinMode() and digitalWrite() on GPIO32 and GPIO33
If external 32Khz crystal is not used, those pins would be a + to have access.
Is there other way to access them in the framework ?

**Comment by mikee47** [comment]
I've not tested those pins, but a quick search of the esp-idf and found this https://github.com/espressif/esp-idf/issues/285

Probably needs some attention in `Arch/Esp32/Core/Digital.cpp`.

**Comment by mikee47** [comment]
Also checked logic in Digital.cpp and don't see any issues - the above link refers to disabling the pin as RTC which `pinMode` does already.

**Comment by mikee47** [comment]
If you still can't get this working please provide details of your development setup, particularly `ESP32 variant`, `IDF version`. Make sure you're using latest develop branch of Sming please.

**Comment by profjmer** [comment]
My wrong,
Basic_Blink works, so it's on my side.
Thank you for your time
