### ISSUE TITLE
 error: implicit declaration of function 'system_rtc_mem_read'

### ISSUE THREAD

**Issue by pljakobs** [SmingHub/Sming#2746]
I guess, during the recent work on rboot, the include for esp_system.h was lost somewhere?
I have added it to Sming/Components/rboot/rboot/appcode/rboot-api.h which works for me - is that the place you want it? I can submit a PR.

**Comment by mikee47** [comment]
Thanks for finding this! Bit fiddly as change required in submodule, but thank you for offer.

**Comment by pljakobs** [comment]
I've rebased my pr and opened it to your "sming" branch, now it only has one commit
