### ISSUE TITLE
#warning "**Y2038** time_t is only 32-bits in this build configuration stops the build for esp32 due to -Werror=cpp

### ISSUE THREAD

**Issue by xeonqq** [SmingHub/Sming#2784]
When using the lastest sming in docker and try to build esp32
I have the following error:
![Screenshot from 2024-06-01 21-11-29](https://github.com/SmingHub/Sming/assets/4160429/54f5cceb-cf5c-4f5f-be87-f1d0a8bfcf12)

Have to delete that line from DataTime.cpp to make it work, I don't know where this -Werror=cpp is defined. Or if this warning is necessary.

**Comment by mikee47** [comment]
See issue #2758.

1. Build with `STRICT=1` to allow compilation to continue
2. Fix the problem. i.e. you're using an old IDF version (4.3 or 4.4)

**Comment by xeonqq** [comment]
I just rebuild the docker image with the [Dockerfile](https://github.com/SmingHub/Sming/blob/develop/Tools/Docker/cli/Dockerfile), cuz I want the new websocket fix. Shouldn't it pull the latest IDF version automatically for me?

**Comment by mikee47** [comment]
Ah, I see. The default IDF installed is version 4.4, we should probably update that to 5.2.

**Comment by mikee47** [comment]
For now, you can modify the dockerfile as per https://sming.readthedocs.io/en/latest/_inc/Sming/Arch/Esp32/README.html#idf-versions:

```
RUN INSTALL_IDF_VER=5.2 Tools/install.sh $INSTALL_ARGS
```

**Comment by mikee47** [comment]
Warning now removed.
