### ISSUE TITLE
Windows Esp8266 CI build randomly failing due to lwip2

### ISSUE THREAD

**Issue by mikee47** [SmingHub/Sming#2806]
With #2793 we're getting 'undefined reference' errors https://github.com/SmingHub/Sming/actions/runs/9543740796/job/26300929559

It's Windows only, and re-running the test usually succeeds so not a particular priority. Possibly a race condition in the makefiles?

Windows builds are pretty bad anyway: WSL2 is a better option.

**Comment by slaff** [comment]
> Possibly a race condition in the makefiles?

@mikee47 I saw this too. Will check if at least downloading of a file or a repo fails silently somewhere...

**Comment by slaff** [comment]
Should be fixed in #2815. Feel free to re-open the issue if it occurs again.

**Comment by mikee47** [comment]
Thanks slaff. I did take a look at modifying the lwip2 makefile but I like your solution better :-)
