### ISSUE TITLE
Install Sming Examples (optional) fails

### ISSUE THREAD

**Issue by DominicMe** [SmingHub/Sming#281]
The command listed in Install "Sming Examples (optional)" section for the installation guide is broken.

Error:

sming.examples not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "'https://www.myget.org/F/kireevco-chocolatey/"

**Comment by hreintke** [comment]
@kireevco : 
Does this issue still needs action ? If not please close the issue.
