### ISSUE TITLE
RFC: Update DateTime service to more modern Time lib from arduino

### ISSUE THREAD

**Issue by avr39-ripe** [SmingHub/Sming#288]
Hello!
Here is some Request For Comments:
May be we should import newer version of DateTime from https://github.com/PaulStoffregen/Time
As it statet on its README: "The code is derived from the Playground DateTime library but is updated
to provide an API that is more flexable and easier to use." moreover, many arduino time-relevant libs relay on Time library for example library to serve DS3131 RTC module https://github.com/JChristensen/DS3232RTC require Time library from above. As far as I understand there is very little local changes to Smings version of DateTime library, so this changes can be easyly ported to Time library. If there is no obligation, I can try to replace DateTime component of Sming to Time (indeed I will ask for some help, but can do much of the work myself)

So please comment on this.

PS. By the way, I successfuly ported missing part of Time lib to current DateTime service in Sming and compile DS3232RTC lib, moreover it JUST WORKS with hardware connected to esp12 module ;)

**Comment by hreintke** [comment]
No progress/information for a long time. 
Closing the issue
