### ISSUE TITLE
develop is tagged 4.0.0-rc-4

### ISSUE THREAD

**Issue by pljakobs** [SmingHub/Sming#2891]
to make sure I was building off the correct Sming source, I included `git describe --tags` in my build - for the develp branch, that returns `4.0.0-rc-4` - would be great if that would read devel-5.3 (or 6). 4.0.0 is a bit confusing at first.

**Comment by slaff** [comment]
Thank you for the suggestion. Sure, I will try to find the fist commit in the 6.0.0 development and tag it as 6.0.0-dev. And will do the same for future versions.
