### ISSUE TITLE
Again, the problem with the system Debug Output 

### ISSUE THREAD

**Issue by STASIUK** [SmingHub/Sming#295]
problem with the system Debug Output!
Output system Debug information when disable 
>Serial.systemDebugOutput(false);

**Comment by hreintke** [comment]
@STASIUK : 
Can you provide the sming and adk version you are using ?

**Comment by Tavalin** [comment]
@STASIUK what's the actual issue?

**Comment by STASIUK** [comment]
> scandone
add 0
aid 3
pm open phy_2,type:2 0 0
cnt 
> 
connected with myAPP, channel 10
dhcp client start...
ip:192.168.2.8,mask:255.255.255.0,gw:192.168.2.1

How to disable output this information?

**Comment by flexiti** [comment]
http://bbs.espressif.com/viewtopic.php?f=13&t=610&sid=c12accff25fc0cf04b6f19e04f6a5cb0#unread

**Comment by flexiti** [comment]
Read info from esspresif point 4:
4. it is the ROM log (startup log) we can't remove or disable it . But you could call system_uart_swap to use MTCK & MTDO as UART0 

Thanks for your interest in ESP8266 !
