### ISSUE TITLE
Software serial? It's possible?

### ISSUE THREAD

**Issue by STASIUK** [SmingHub/Sming#299]
Is it possible to run Software serial?

**Comment by flexiti** [comment]
TX yes, RX will be more difficult -  It depends on the speed you want to get

**Comment by STASIUK** [comment]
for example 9600
possible?

**Comment by flexiti** [comment]
at that speed:
TX - (eg. timer) every 104 us
RX - one bit is about 104 us, there must be some sampling, eg. 10 times, it means that the polling (eg. the timer) would have to be every 10us (and can not be disturbed) to find start bit.
Or based on port interrupt on the edge and first timer after 52 us and next every 104 us)
Possible, but You must have a good knowledge of the system and interrupt priorities

eg. 110 baud - bit is 10 ms long  ,it is easier :)

**Comment by hreintke** [comment]
No information for a long time.
Closing the issue

**Comment by crosofg** [comment]
Is software serial possible? Can I connect four serial port devices?

**Comment by flexiti** [comment]
Yes, as described above

**Comment by crosofg** [comment]
Can some library like this [](https://github.com/plerup/espsoftwareserial) be used to connect four serial devices to esp8266?
