### ISSUE TITLE
What about JTAG (or similar) debugging?

### ISSUE THREAD

**Issue by maiorfi** [SmingHub/Sming#310]
Is there any way to do low-level hardware debugging?

**Comment by slaff** [comment]
You can check this article: http://visualgdb.com/tutorials/esp8266/. Unfortunately it is only for Windows.

**Comment by maiorfi** [comment]
Great post! Thanks!

**Comment by slaff** [comment]
@maiorfi By the way:  If you want to try software debugging take a look at [Arduino-ESP](https://github.com/esp8266/Arduino/tree/esp8266/hardware/esp8266com/esp8266/libraries/GDBStub) and the [Smart.JS blog](https://blog.cesanta.com/esp8266-gdb)

**Comment by hreintke** [comment]
Handled by #350
