### ISSUE TITLE
Espressif's open lwip

### ISSUE THREAD

**Issue by alonewolfx2** [SmingHub/Sming#313]
Can we change liblwip to Espressif's new open lwip? It would be very good and usefull.

**Comment by pvvx** [comment]
SDK 1.4.0 (Open lwip: https://github.com/pvvx/MinEspSDKLib/tree/master/app/sdklib/lwip )
1) struct netif. netif.h. Add:
#if DEF_SDK_VERSION >= 1400 // (SDK 1.4.0)
  void * dhcpc_event; // +40 (SDK 1.4.0)
#endif
2) New eagle_lwip_if.c: https://github.com/pvvx/MinEspSDKLib/blob/master/app/sdklib/system/eagle_lwip_if.c

**Comment by alonewolfx2** [comment]
@pvvx nice to see you :) i will try and let you know

**Comment by pvvx** [comment]
Espressif: Open source LWIP for ESP_IOT_SDK_V1.4.0: http://bbs.espressif.com/viewtopic.php?f=46&t=1221

**Comment by alonewolfx2** [comment]
@pvvx can you provide pr with esp open lwip for us ?
