### ISSUE TITLE
new DS1820 example and class without forbidden Dealy()

### ISSUE THREAD

**Issue by flexiti** [SmingHub/Sming#318]
Can we merge  #274  ?
We still have a bad example for the DS1820 in the master and develop

**Comment by hreintke** [comment]
@kireevco : @raburton 
Can we merge branch feature/Temperature_DS1820-delay into Develop ?
If so, can one of you do this ?
If not, what steps are needed to get this functionality into Develop ?

DS1820 will then be part of next Sming Release

**Comment by alonewolfx2** [comment]
i will test in this night. if its working fine i will merge it .

**Comment by hreintke** [comment]
@flexiti : 
PR is merged, can you verify correct working and if OK close the issue ?

**Comment by flexiti** [comment]
@hreintke 
I think is ok. I checked on 1,2,3,4 sensors connected in parallel

**Comment by alonewolfx2** [comment]
i checked 2 sensor parallel and its ok.
