### ISSUE TITLE
UdpConnection::sendStringTo creates copy of data

### ISSUE THREAD

**Issue by vsirvent** [SmingHub/Sming#335]
I think it should pass data by reference, not value:

from 

void UdpConnection::sendStringTo(IPAddress remoteIP, uint16_t remotePort, const String data)

to

void UdpConnection::sendStringTo(IPAddress remoteIP, uint16_t remotePort, const String& data)

it's internally calling sendTo which already makes a copy of data.

**Comment by kireevco** [comment]
@anakod @alonewolfx2 @hreintke @raburton any thoughts?

**Comment by slaff** [comment]
@vsirvent Please make a PR request.
