### ISSUE TITLE
GPIO9 wdt reset when trying to use it

### ISSUE THREAD

**Issue by alon24** [SmingHub/Sming#336]
In esp 12-e,f,q we have GPIO9 an GPIO10 that should be able to use if we flash with DIO mode (not qio).

When flashing with DIO GPIO10 is available (input, output, interrupt).
When trying to use GPIO9 we get a wdt reset always (input, output, interrupt)
It would be nice to get this working (extrapins are always welcomed).

@alonewolfx2 said that he thinks that nodemcu allows you the user of GPIO9,10 in this mode (dio)

**Comment by alonewolfx2** [comment]
Maybe I am wrong I am not sure :)

**Comment by robotiko** [comment]
This can be related to #397 
If the gpio address is not rigth and it is set or read, the esp resets.

**Comment by hreintke** [comment]
Closed due to no progress
