### ISSUE TITLE
How to configure MQTT for LWT?

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#337]
I am trying to configure my ESP to post a message with Last Will and Testament (LWT) on MQTT. I cannot find any example or any function declared for the same in the header file.

Can anybody point me in right direction?

**Comment by slaff** [comment]
Take a look at my recent PR: https://github.com/slaff/Sming/commit/23997249620d9173c1ee29b21db41979a3cf015f. Once it is in the master branch, if it makes it to there, you should be able to easily set LWT.

**Comment by kireevco** [comment]
@ashubhatt Do you think this solves your issue?

**Comment by hreintke** [comment]
Solved by #390

**Comment by ashubhatt** [comment]
I dont think the LWT feature works in Sming.

I tried to check the working, but after disconnection, the LWT message is not sent.
I am using the latest build - 1.4.0
