### ISSUE TITLE
Binary files in the distribution package & CI

### ISSUE THREAD

**Issue by kireevco** [SmingHub/Sming#341]
Hi all,
Let's sync up on the topic of how do we distribute sming for all users.
I see it this way: 

### 1. We build sming core in the CI (Jenkins)
_Build binaries (currently libsming and spiffy) for all platforms. This will be available as sming-core or some similar zip file._
We will have 3 files as a result of this build:
- sming-core-1.0.4-linux-x86_64.tar.gz 
- sming-core-1.0.4-win32-x86_64.zip 
- sming-core-1.0.4-darwin-x86_64.zip

### 2. We package environment
_Full isolated environment that contains a specific sdk version (tested one), and other external tools. This package contains sming-core contents as well._
- sming-1.0.4-linux-x86_64.tar.gz 
- sming-1.0.4-win32-x86_64.zip 
- sming-1.0.4-darwin-x86_64.zip

### 3. We create an installer (optional)
_Should work in a cross-platform way_
CI step that takes care of building an installer package

The main idea here that user __shouldn't be required__ to think about anything other then his project, and the closest way to implement this is build a package.
I'm working on building a ci cluster with at least all 3 platforms.
I will update this proposal when I get more details, but until then feel free to comment.

**Comment by kireevco** [comment]
Good news, I was able to run OSX on my Proxmox cluster. This will allow use build on mac too:
![](http://content.screencast.com/users/kireevco/folders/Jing/media/29402b71-4d52-480b-ac8f-d7f7f5a1e64a/00000187.png)

**Comment by raburton** [comment]
Quick thought, will write it while I think about it. We need to add a "release" or similar make target. It will build everything and then call a limited clean target that removes all the intermediate files but just leaves the binaries we want (where clean normally cleans everything). Then a new version can simply be checked out, built with release target and then zipped.

**Comment by hreintke** [comment]
Some thoughts on timing.
Now/soon we have the major update on rboot integration/spiffy/spiffs and a number of fixes ready.
I think it would be wise to take this as a Sming release 1.4.0 before adding more functionality.

Question the is whether we would release 1.4.0 in the "old way" or are already (partly ?) ready for taking (parts of) the ideas above ?

**Comment by kireevco** [comment]
I am not ready to make a cross platform build yet.
--
Sincerely,
  Dmitry Kireev
  Cell: +1 (818) 850-55-77
  Skype: kireev.co <http://kireev.co/>

**Comment by raburton** [comment]
@hreintke rBoot was integrated in v1.3.0. We do have plenty of new stuff though, and bug fixes, waiting to go. I'd like the new spiffs/spiffy to get a more testing before it goes into a release though. If there are no more issues tomorrow (as people are currently testing with it) I'll merge it to develop so it gets wider testing. I suggest development freeze around that time and assuming no blockers within a couple of days release v1.4.0, in the same was as v1.3.0. This issue is going to take a little time to get up and running so we shouldn't wait in the mean time.

**Comment by raburton** [comment]
@kireevco do you realise that little image you posted is 3.8mb? Not very mobile friendly!

**Comment by kireevco** [comment]
@raburton ah... stupid retina screenshots. sorry.

**Comment by hreintke** [comment]
@raburton : 
Yes, that was my idea too.
Once we freeze I will submit an issue "Feedback on Release 1.4.0" where we can collect issues/opinions on the release to come.
One thing one forehand : we will need documentation as there are actions needed from users to upgrade without problems.

**Comment by kireevco** [comment]
Moving along:

<img width="1439" alt="2015-10-19_1122" src="https://cloud.githubusercontent.com/assets/1790594/10574089/054eb6c6-7654-11e5-83fc-d2779a7192be.png">

**Comment by kireevco** [comment]
I got esp-alt-sdk built on my cluster, all platforms work correctly. I'll work on sming build steps. 
Good news, that travisci has mac builder now!

**Comment by hreintke** [comment]
Travis running implemented.
