### ISSUE TITLE
What goes wrong if you try to use Sming with Xcode 7.1?

### ISSUE THREAD

**Issue by ericmnel** [SmingHub/Sming#363]
The Mac start instructions say that Xcode 6.2 works and 6.3 doesn't - 6.2 refuses to install on MacOS 10.11 so I can't use it.   What will the side effects be of using a later version of Xcode like 6.3 or 7.1?

**Comment by kireevco** [comment]
Hi, @ericmnel, xcode is required to compile esp-open-sdk. If you are using a prebuild binary, I don't think it matters.

**Comment by ericmnel** [comment]
OK Thanks!
