### ISSUE TITLE
readme and wiki files have absolute links

### ISSUE THREAD

**Issue by hreintke** [SmingHub/Sming#365]
The readme.md and wikipages contain links with absolute addresses.
f.e. https://github.com/anakod/Sming/wiki/MacOS-Quickstart from readme.md

When someone forks the sminghub repository his/her fork will contain wrong links.
By following a link he/she will be redirected to main repo 
We could solve that by using relative links

../../wiki/MacOS-Quickstart

I am not sure how to test in my fork without (in)direct updating/pushing to sminghub/sming repo

**Comment by kireevco** [comment]
@hreintke I agree on README.

Wiki pages are using github internal links:
<img width="927" alt="00000208" src="https://cloud.githubusercontent.com/assets/1790594/10839267/d9c8f09c-7ee2-11e5-913e-b13390c2d37f.png">

**Comment by raburton** [comment]
When you create a fork you don't get the wiki anyway.

**Comment by hreintke** [comment]
@kireevco : 
Just closing or do you take the action to update README ?

**Comment by kireevco** [comment]
as @raburton said fork won't get a wiki. I don't see a reason to update README. Wikipages are relative to wiki (internal links), so they should be fine.

**Comment by kireevco** [comment]
Actually one change worth making - change anakod to SmingHub in all links.
I made this change.
