### ISSUE TITLE
.settings junk

### ISSUE THREAD

**Issue by raburton** [SmingHub/Sming#376]
All the samples seem to have a folder called .settings that is full of eclipse stuff, but it doesn't seem to be important project stuff, just user settings. Can Anyone who uses eclipse confirm that these aren't needed and I'll strip them out.

**Comment by hreintke** [comment]
I am busy cleaning up and correcting the eclipse settings/options for both framework and examples.
Will submit a PR for that shortly.

**Comment by raburton** [comment]
Cool.

**Comment by raburton** [comment]
I can pull all those out and add the necessary to the .gitignore for you if you like. I've got a few minutes spare...

**Comment by kireevco** [comment]
Thank you, @hreintke I assume you remember about cross-platform needs?

**Comment by hreintke** [comment]
@kireevco : 
I make sure that I have the used paths only dependent on the SMING_HOME and ESP_HOME.
That is also how the current implementation works.
Eclipse itself is multiplatform, so should this should work on all.

Do I miss something in this reasoning  ?

**Comment by kireevco** [comment]
@hreintke 
> I make sure that I have the used paths only dependent on the SMING_HOME and ESP_HOME.

Yes, and also we need to make sure that path separators work fine on all systems. But they should be ok.

**Comment by kireevco** [comment]
@hreintke any update?

**Comment by hreintke** [comment]
No, Other priorities prevailed

**Comment by raburton** [comment]
done
