### ISSUE TITLE
When installing with Chocolatey the development environment does not work, compile error.

### ISSUE THREAD

**Issue by fenixscd** [SmingHub/Sming#388]
When installing with Chocolatey the development environment does not work, compile error.

C + app / application.cpp
AR out / build / app_app.a
LD out / build / app.out
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.1.0/../../../../xtensa-lx106-elf/bin/ld.exe: can not find -lsming
collect2.exe: error: ld returned 1 exit status
make: *** [out / build / app.out] Error 1

**Comment by raburton** [comment]
please see your own issue #381, from just yesterday, in which you had the same problem and the answer was given

**Comment by raburton** [comment]
in addition, please only use the github issue tracker for reporting bugs or feature requests, it is not a user help forum

**Comment by fenixscd** [comment]
ok
