### ISSUE TITLE
GPIO9 and 10 is overwritten during  Adafruit_SSD1306:display() method

### ISSUE THREAD

**Issue by tprochazka** [SmingHub/Sming#397]
If you will use GPIO9 a 10 as output pins together with Adafruit_SSD1306 library, state of these GPIOS will be overwritten every time that OLED is updated by display() method.

I'm not sure just now with the exact reason now.
But I'm very close. I tried to replace 
```
*csport |= cspinmask;
*dcport |= dcpinmask;
*csport &= ~cspinmask;
*csport |= cspinmask;
```
by
```
digitalWrite(cs, HIGH);
digitalWrite(dc, HIGH);
digitalWrite(cs, LOW);
digitalWrite(cs, HIGH);
```
In Adafruit_SSD1306.cpp.
And problem is gone!

It looks that bit mask is incorrect and change more pins!
I checked that uint8_t is used for PortReg and PortMask it is correct for ESP like 32 bit CPU? 
Or it is problem in digitalPinToBitMask() or portOutputRegister() ?

**Comment by tprochazka** [comment]
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Arduino.h#L227

**Comment by anakod** [comment]
Ok, got it. I think we should make minimal test code for repeating this problem and when we can start working on register implementation part.

**Comment by tprochazka** [comment]
I already localize and found the problem, 8 bit variable was used in Sming instead of 32 bit for GPIO register.

**Comment by anakod** [comment]
Please look my comment to related P-R. I think it isn't right and willn't work for high pin numbers.

**Comment by tprochazka** [comment]
@anakod  ESP8266 Arduino project use also 32 bit register, why do you think that it will not work?

**Comment by hreintke** [comment]
Issue should be moved to SmingRTOS.

**Comment by tprochazka** [comment]
I don't understand why this was fixed in RTOS version and not here, id this is still under development, or not?
