### ISSUE TITLE
Allow CFLAGS in Makefile-user.mk

### ISSUE THREAD

**Issue by piperpilot** [SmingHub/Sming#434]
A very simple change to allow the user to pass in their own CFLAGS from Makefile-user.mk.  In my example I want to pass in a project version like this:

```
CFLAGS		+= -DSMOBOTVERSION=$(SMOBOTVERSION)
```

Pull request follows.

**Comment by raburton** [comment]
Already possible, see 0a4404a33.

**Comment by piperpilot** [comment]
Closing as already done.
