### ISSUE TITLE
ScreenOLED_SSD1306 example is not Sming style and resets device 

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#438]
It is arduino style code with delays and the demo itself resets device before ending.

**Comment by alonewolfx2** [comment]
@flexiti where are you :)

**Comment by flexiti** [comment]
@alonewolfx2 Here ☺ BTW.  Neopixel work ok now

**Comment by alonewolfx2** [comment]
i tried working fine thank you :) can you update this example with sming style :)

**Comment by flexiti** [comment]
@alonewolfx2 
ok, I will check it

**Comment by flexiti** [comment]
Done #442
