### ISSUE TITLE
__errno symbol not defined & esptool.py errors

### ISSUE THREAD

**Issue by zardam** [SmingHub/Sming#450]
Missing __errno symbol is the root cause of esptool.py problems on branch develop.

I have tracked down the issue to "JsonVariant.cpp" which includes errno.h from the toolchain (newlib) and not from the custom libc of Sming (musl derivate), which declare errno a different way.

Using the right header from https://github.com/anakod/esp_microc/blob/master/include/errno.h solves the problem (errno is associated to the symbol __errno_location).

I'm not an expert in this domain, so I dont know exactly the right way to solve this problem. If anyone has an advice, I can make a pull request.

**Comment by hreintke** [comment]
Fixed
