### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by raburton** [SmingHub/Sming#462]
Travis sdk needs to be updated to v1.4 (or possibly v1.5 shortly) as it's currently only at v1.2, the builds have been failing ever since we moved up to supporting (and requiring) sdk v1.4. @kireevco are you able to sort this? I think you set up the original.

**Comment by kireevco** [comment]
@raburton yeah. I'll do that.

**Comment by raburton** [comment]
thanks

**Comment by raburton** [comment]
closed by #482
