### ISSUE TITLE
esptool2 path definition

### ISSUE THREAD

**Issue by tprochazka** [SmingHub/Sming#470]
Makefile-project.mk now contains
```
# esptool2 path
ESPTOOL2 ?= esptool2
```
Maybe default location should be defined like this
```
# esptool2 path
ESPTOOL2 ?= $(SDK_TOOLS)/esptool2
```
to be compatible with other Sming tools.

What do you think?

**Comment by alonewolfx2** [comment]
@tprochazka but esptool2 isnt a sdk tool. its came from @raburton 's repo.

**Comment by tprochazka** [comment]
Yes. I know. I builded it myself and automatically put at the same place like espotool.exe and it didn't work. And I think that in the future, when new version of the Sming will be release it will be part of sdk tool distributed by Chocolatey (or any other way)

**Comment by raburton** [comment]
No plans to ship esptool2 with Sming, if that changes this path could be updated. As things stand the current path is the appropriate one.

**Comment by tprochazka** [comment]
So why is old one esptool shipped by Sming?
Or not shipped directly but installed by Chocolatey.
I think that this is one to benefit of Sming, that it is easy to setup building environment.
