### ISSUE TITLE
LWT feature of MQTT not working

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#491]
I am using Sming 1.4.0 and trying the sample code "MQTTClient_Hello".
Although the LWT function is implemented, the actual LWT message is not received in case of abrupt disconnection.

I have opened issue #337, but it was closed assuming the latest build have added the feature; the bug still remains.

Kindly update the source code.

**Comment by Informatic** [comment]
I can confirm it is working now.

**Comment by matoushybl** [comment]
Is LWT working with the patch? After setting LWT and disconnecting power, it was still not sent.

**Comment by flexiti** [comment]
Are You using last develop ?

**Comment by matoushybl** [comment]
Yes, I do. Is the keep alive interval important for LWT? I mean if it is for example 1 hour, will it send LWT after the one hour?

**Comment by flexiti** [comment]
no, keep alive is not important for LWT if socket is closed eg. no internet connection
(depends on broker)
For me LWT is working after aprox. 30 sec then device is off

> if(!mqtt.setWill("main/device/100","{\"Value\":0,\"No\":100,\"Status\":\"Off Line\",\"Time\":\""+SystemClock.getSystemTimeString()+"\"}", 1, true)) {
> 			debugf("Unable to set the last will and testament. Most probably there is not enough memory on the device.");
> 		}
> 
> 	mqtt.connect("esp8266-100",MQTT_USERNAME,MQTT_PWD);
> 	mqtt.subscribe("main/#");
> 	mqtt.publishWithQoS("main/device/100","{\"Value\":1,\"No\":100,\"Status\":\"On Line\",\"Time\":\""+SystemClock.getSystemTimeString()+"\"}",1,true);
>

**Comment by matoushybl** [comment]
I have a very similar code as yours, I am starting to think that this is caused by broker, at my second attempt the LWT was received after more than two hours. What broker are you using?

**Comment by flexiti** [comment]
Mosquitto on my serwer

**Comment by matoushybl** [comment]
Thanks, me too. That is weird, I updated mosquitto and it still isn't working, I'll dig deeper to find out what the problem is.

**Comment by matoushybl** [comment]
Yeah, by power off, I haven't noticed the question, sorry.

**Comment by hreintke** [comment]
Fixed
