### ISSUE TITLE
ContentType::fromFileExtension returns text/plain for jpeg files

### ISSUE THREAD

**Issue by dieki-n** [SmingHub/Sming#502]
This causes Firefox to display the file as gibberish text instead of an actual image.

Line 45 of Sming/SmingCore/Network/WebConstants.h is the offender:

    if (ext.equals("jpg") | ext.equals("jpeg")) return TEXT;

**Comment by raburton** [comment]
Submit a PR...

**Comment by raburton** [comment]
Or I'll do it myself.
