### ISSUE TITLE
Sming support on http://platformio.org/

### ISSUE THREAD

**Issue by tprochazka** [SmingHub/Sming#508]
Will be really great for Sming if it will have support on http://platformio.org/#!/
Espressif SDK is already there and Arduino implementation too
http://platformio.org/#!/boards?filter%5Bframeworks%5D=arduino
https://github.com/esp8266/Arduino/blob/master/doc/platformio.md

It should allows to use also different IDE than Eclipse like
http://docs.platformio.org/en/latest/ide/clion.html

**Comment by Vity01** [comment]
+1

**Comment by hreintke** [comment]
@tprochazka : 
I understand the enhancement but I have no idea what needs to be done and how difficult it would to maintain.
Would suggest that you investigate further on the above and/or other aspects and feedback.
Based on that we can decide on further actions and if neeed I will expect a PR from you.

**Comment by tprochazka** [comment]
I just found that it exists, I will try to use it and investigate how difficult it is.

**Comment by tprochazka** [comment]
Here in video presentation how it works
https://www.youtube.com/watch?v=lXchL3hpDO4

**Comment by nistvan86** [comment]
+1
Sming is an amazing project but as a beginner with Eclipse CDT projects I've found it hard to create a new project from scratch. PlatformIO greatly simplifies this process.

**Comment by chriscohnen** [comment]
+1
I am also interested in having Sming available on PlatformIO
Hope this will be implemented

**Comment by andgeno** [comment]
+1

**Comment by hreintke** [comment]
I agree on the suggestion to allow sming installation with platformio.
Can someone take the lead in that.
Please open an issue on SmingRTOS on that.
