### ISSUE TITLE
Handle Usernames with Spaces for sming.examples Chocolatey Package

### ISSUE THREAD

**Issue by xieliwei** [SmingHub/Sming#512]
In the chocolately install script for sming.examples, Eclipse is invoked with `-data $eclipseWorkspace` but should be ``-data `"$eclipseWorkspace`"`` to handle cases where there are spaces in the workplace path.

This occurs twice within the script I think.

**Comment by kireevco** [comment]
@xieliwei Can you please submit a PR to github.com/kireevco/chocolatey-packages ? thanks.
