### ISSUE TITLE
Add a TCP Disconnect Callback function

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#516]
Hey guys,

Please provide a delegate to add a callback function for TCP disconnection. The callback function should fire once the functionTcpConnection::close() is fired.

If you guys can provide a workaround solution, I am all ears.

Thanks

**Comment by ashubhatt** [comment]
Used: 
virtual err_t onReceive(pbuf *buf);

**Comment by alonewolfx2** [comment]
@ashubhatt what is your full function for connection close event?

**Comment by ashubhatt** [comment]
I used a delegate function for callback:
```
typedef Delegate<void()> MqttDisconnectCallback;
```

Then set this callback using a new function:
```
void MqttClient::setDisconnectCb(MqttDisconnectCallback dcb /* = NULL */){
	if(dcb)
		this->disCallback = dcb;
}
```

Finally in virtual err_t onReceive(pbuf *buf), I called the delegate function:
```
if (buf == NULL)
	{
		// Disconnected, close it
		this->disCallback();
		TcpClient::onReceive(buf);
	}
```

**Comment by alonewolfx2** [comment]
ok. can you make PR for this?

**Comment by ashubhatt** [comment]
The implementation was applied specifically for MQTT. But can be used similarly for other child classes of TCP Connection.
PR: #518
