### ISSUE TITLE
Development freeze for Sming Release V2.1

### ISSUE THREAD

**Issue by hreintke** [SmingHub/Sming#519]
A number of bugs did not make it into V2.0, are now merged and tested OK in develop.

I propose to release bugfix Sming V2.1 

Created a Draft Release V2.1 and will submit a PR to update the Sming version.

**Comment by hreintke** [comment]
No response on this yet,

What is your opinion,  there a few larger enhancements ready to merge.
If we do that before releasing it will take some time have the bugfixes in a released version.

**Comment by flexiti** [comment]
Maybe before it, maerge should be done ? 
A lot of pull requests is waiting

**Comment by hreintke** [comment]
@raburton : 
I think all is set and merged into develop for release.
Can you merge develop into master ?

**Comment by alonewolfx2** [comment]
Merged
