### ISSUE TITLE
Var position during template processing

### ISSUE THREAD

**Issue by jobidon** [SmingHub/Sming#520]
There seems to be an issue with template processing when a variable name happens to be on the edge of the TCP buffer (1024). The code spits out a partial template but does not resume processing of the rest of the template.
To reproduce, create a template with 1020 bytes of data followed by '{myvariable}' and a bunch of data following that.
What happens then is that the first 1020 chars are output and the HTTP server stalls and does not close the connection, resulting in a partial template.

Preliminary testing indicate that this simple fix corrects the issue:
in Sming/Sming/SmingCore/DataSourceStream.cpp, line 225 should be:
state = eTES_StartVar;

This seems to force the code to resume processing where it left off before reaching the end of the buffer.
Further tests are required to commit this fix.

**Comment by hreintke** [comment]
Solved by #531
