### ISSUE TITLE
TelnetServer Bug: curClient not initialized in constructor

### ISSUE THREAD

**Issue by gschmottlach** [SmingHub/Sming#524]
I ran across a bug in TelnetServer that appears sporadically. The ```curClient``` member variable is **not** being initialized to NULL in the constructor. As a result, depending on what's stuffed in the memory region at start-up, you may not be able to telnet into your application. This fix is pretty simple. Here's the revised constructor with ```curClient``` explicitly initialized:

```
TelnetServer::TelnetServer()
	:
	TcpServer(),
	curClient(nullptr)
{
	// TODO Auto-generated constructor stub

}
```
This was found in the latest *develop* branch.

**Comment by hreintke** [comment]
@gschmottlach :
Good catch, thanks.
Did a quick check and think it is also valid for commandExecutor.

I prefer to have the intialization done in the TelnetServer.h where the variable is defined.

Can you make a PR for this ?

**Comment by gschmottlach** [comment]
As requested I've submitted a PR for this. Both ```curClient``` and ```commandExecutor``` are set to ```nullptr``` in TelnetServer.h.

**Comment by hreintke** [comment]
Solved
