### ISSUE TITLE
rBoot - SPI_SPEED change

### ISSUE THREAD

**Issue by flexiti** [SmingHub/Sming#530]
Where I do wrong?
Regardless of the setting SPI_SPEED  at the start of the rBoot I have always this information:

Flash Size:   32 Mbit
Flash Mode:   QIO
Flash Speed:  40 MHz
rBoot Option: Big flash

**Comment by raburton** [comment]
You are supposed to set the spi speed (along with the other flash options) when you flash the rom. Using esptool.py will do this correctly, some old windows tools don't.

**Comment by flexiti** [comment]
It does not change because I was programming via OtaUpdate.
When I flashed its ok. Thanks
