### ISSUE TITLE
FTP server command LIST is not able to show more like 50 files (depends on filename length)

### ISSUE THREAD

**Issue by tprochazka** [SmingHub/Sming#538]
Steps to reproduce:

Use FtpServer_Files and ad this code to generate more files on FS

```
	for (int i = 0; i<100; i++) {
		WDT.alive();
		fileSetContent("example" + String(i) + ".txt", "hello world!");
	}
```

Then connect to the FTP server and you will see just something like 50 files.

It is because ```class FTPDataFileList``` defined in ```FTPServerConnection``` trying to sent complete list in one iteration, but output buffer for this is limited.

I'm working on fix.

**Comment by hreintke** [comment]
Needs to be documented as a known limitation.
