### ISSUE TITLE
MQTT client does not send PING when receiving messages

### ISSUE THREAD

**Issue by Informatic** [SmingHub/Sming#549]
MQTT PINGREQ when there is no outgoing activity are handled in `MqttClient::onReadyToSendData`. However, `sleep` variable checked there is reset to 0 in `TcpConnection::staticOnReceive` (as well as `onSent`). In such case `mqtt_ping` is never called when client receives multiple messages with QoS 0 with intervals lower than 10 seconds.

MQTT client should store its own "sleep-like" counter variable, reset only in `onSent` event (or just use millis()?)

**Comment by fcgdam** [comment]
Yes, I've also hit this issue when only receiving data, after 10s the connection is dropped.
My solution was to inform the broker by setting  keepAlive() to a large value.

**Comment by hreintke** [comment]
Solve by #550
