### ISSUE TITLE
Option to reconfigure http server

### ISSUE THREAD

**Issue by icodk** [SmingHub/Sming#556]
Currently the HttpServer has only the addPath() method to configure the  server. I am missing the option to reconfigure. A use case could be that you allows web interface for a short while after boot, after that only one page should be available. A simple solution could  be to add clearPath method and then you could add other handlers., as before with addPath()
```
void HttpServer::clearPath(void)
{
        paths.clear();
}
```

**Comment by hreintke** [comment]
@icodk : 
It is a not good idea to have only the option of a "full clear" of all paths.
If you can think of a solution to manage the paths in a generic way we can discus that here.

**Comment by icodk** [comment]
@hreintke 
Can't beat your arguments. So here are mine: full clear is calling the clear() function of the HashMap existing function  so no additional complex code should be implemented. at the same time, you get full control of the web server configuration because you can again use addPath.
