### ISSUE TITLE
build error with latest code...any ideas?

### ISSUE THREAD

**Issue by rfeisel** [SmingHub/Sming#558]
15:24:29 **** Build of configuration Sming for project SmingFramework ****
make all 
C+ system/m_printf.cpp
In file included from c:\tools\sming\sming\smingcore\network\ntpclient.h:8:0,
                 from c:\tools\sming\sming\smingcore\SystemClock.h:7,
                 from c:\tools\sming\sming\smingcore\smingcore.h:18,
                 from system/m_printf.cpp:10:
c:\tools\sming\sming\smingcore\platform\station.h:36:25: error: 'SC_TYPE_ESPTOUCH_AIRKISS' was not declared in this scope
  SCT_EspTouch_AirKiss = SC_TYPE_ESPTOUCH_AIRKISS
                         ^
make: *** [out/build/system/m_printf.o] Error 1

15:24:39 Build Finished (took 9s.904ms)

**Comment by raburton** [comment]
Sming requires sdk v1.4/v1.5
