### ISSUE TITLE
How to disable statements printing on Serial port after OTA?

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#569]
@raburton When I perform OTA, the ets_printf() statements are executed during reboot. 
Can I disable these statements which are being printed after reboot?

Such as:
rBoot v1.2.1 - richardaburton@gmail.com
Flash Size:   4 Mbit
Flash Speed:  40 MHz
etc

**Comment by raburton** [comment]
Only by modifying rBoot itself. However, the the esp spews junk on boot anyway, so you can't get rid of all output on a reboot.
