### ISSUE TITLE
How to access extra pins on ESP 12E modules?

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#574]
Hello,

I want to access the additional pins available in ESP 12E (or in NodeMCU v3) as general GPIOs.
How can I access those pins and how to configure them as GPIOs (input or output)?
![image](https://cloud.githubusercontent.com/assets/14809433/12667929/8e0e7bd6-c677-11e5-91b2-18f916566a18.png)

**Comment by flexiti** [comment]
You can use only 2 of them,  if you open the metal casing and de-connect the port 9 and 10 from flash.memory.
(ESP will work in DIO mode and port 9 and 10 will be free)
Other uses are not yet known, but potentially could be used the same SPI for  to two devices, ie. Flash and user device on the same SPI bus

**Comment by ashubhatt** [comment]
Thanks for the information. I was under the impression that these are extra pins which can be utilized as per user's will. However, upon getting some insight, I think these pins are better left alone.
