### ISSUE TITLE
Hardcoded timings in Neopixel driver

### ISSUE THREAD

**Issue by UncleRus** [SmingHub/Sming#594]
Neopixel driver (and many other drivers I suppose) doesn't work when CPU on 160 MHz because of hardcodced F_CPU value and dependent timings. See https://github.com/SmingHub/Sming/blob/develop/Sming/Libraries/Adafruit_NeoPixel/Adafruit_NeoPixel.cpp#L108

How to reproduce: add `system_update_cpu_freq(160);` as first line to the `init()` function in https://github.com/SmingHub/Sming/blob/develop/samples/Basic_Neopixel/app/application.cpp#L178

**Comment by hreintke** [comment]
Closed in conjunction with #595
