### ISSUE TITLE
Websocket silently disconnect

### ISSUE THREAD

**Issue by icodk** [SmingHub/Sming#602]
After browser-ESP websocket connection created successfully, the ESP connect to remote https web server by using  GET with some parameters. However at that time the earlier established websocket connection to the browser silently breaks(silently= no onClose or wsDisconnected are called). No additional messages arrived at the browser.
More information:
1. The connection with the remote server using ssl is successful.
2. If the ESP is in AP(+STA) mode and the device on which the browser is running is connected to the ESP through the ESP own AP, the websocket connection is not broken.
3. Connecting with one browser directly to the ESP AP and another browser  throught the AP the ESP use to connect to the https server shows all the messages are received on the first while on the second browser messages are received only up to the moment where the connection to the https server is established.
Looks like a wifi channel level issue to me. Hopefully somebody can  shed some light on what is going on here. Any questions are welcome.

**Comment by hreintke** [comment]
closed due to no progress
