### ISSUE TITLE
Delegate pattern needs documentation / examples.

### ISSUE THREAD

**Issue by mralexgray** [SmingHub/Sming#605]
It (the delegate system in `sming`) looks powerful, and relatively straight forward...  but it is NOT clear how to implement it yourself.

This...

```c++
template< class >
class MethodCaller;  /* undefined */
template< class ClassType, class ReturnType, typename... ParamsList > 
class MethodCaller<ReturnType (ClassType::*)(ParamsList ...)> : 
public IDelegateCaller<ReturnType, ParamsList...>
```

Isn't exactly _self-documenting_, lol.

A good place to start would be with timers...

for example.. how do we write methods for objects to be able to use them with 

    Timer& IRAM_ATTR initializeMs(uint32_t milliseconds, TimerDelegate delegateFunction = NULL);

**Comment by Bravo13** [comment]
+1

**Comment by hreintke** [comment]
Just made a PR for Delegate example #606
If no comments are coming for that will commit into develop branch
