### ISSUE TITLE
How to Reconnect mmqt ?

### ISSUE THREAD

**Issue by tinamore** [SmingHub/Sming#65]
Hi.
I have problem: how to ESP8266 reconnect to MQTT broker when MQTT broker server downtime and startup again.
Thanks.

**Comment by anakod** [comment]
I will check it. Temporary workaround to guarante all-time connection:

```C++
public void startMqtt()
{
    if (WifiStation.isConnected() && mqtt.isProcessing())
    {
            return;
    }
    else
    {
        mqtt.connect(DEVICE_NAME);
        mqtt.subscribe(MQTT_SUBCRIBE);
    }
}
...

timer.initializeMs( ... startMqtt).start()
```

**Comment by hreintke** [comment]
Sming repository is currently being restructured and cleaned. This issue has been inactive for a long period and is being closed. If the issue is still valid please open a new with complete description
