### ISSUE TITLE
How to implement system_os_task?

### ISSUE THREAD

**Issue by ashubhatt** [SmingHub/Sming#655]
Hello All,

The basic sdk of esp8266 provides several system_os* functions as mentioned in the SDK Programming Guide. I would like to implement some of those. 
Can someone show me how to implement those functions?

**Comment by alonewolfx2** [comment]
you can define in system.h and system.cpp and you can use in application.h
here is system.h https://github.com/SmingHub/Sming/blob/develop/Sming/SmingCore/Platform/System.h

**Comment by ashubhatt** [comment]
Thank you.
