### ISSUE TITLE
Bug: The header field name is case-insensitive but is not processed as such.

### ISSUE THREAD

**Issue by yunjova** [SmingHub/Sming#672]
There is a bug in the file: "`Sming/Sming/SmingCore/Network/HttpRequest.cpp`".

The header field name is case-insensitive according to:
  https://tools.ietf.org/html/rfc7230
    ...
    _**3.2.  Header Fields**
       Each header field consists of a case-insensitive field name followed
       by a colon (":"), optional leading whitespace, the field value, and
       optional trailing whitespace._
    ...

So in: "`Sming/Sming/SmingCore/Network/HttpRequest.cpp`"
  the function:
    `String HttpRequest::getHeader(String headerName, String defaultValue /* = "" */)`
  must do a case-insensitive compare.

Example: It should accept `Content-Type:` but also `Content-type:` (lowercase t in -type).

**Comment by patrickjahns** [comment]
Good catch. The proposed solution is not complete. There are more parts of the code that need to be addressed in order to enable case insensitive parsing and processing

I will provide a patch towards #622 and #631

**Comment by patrickjahns** [comment]
Fix provided - please see #681 and test it
