### ISSUE TITLE
Eclipse resolving standard objects e.g. String

### ISSUE THREAD

**Issue by Pfannex** [SmingHub/Sming#683]
Hi,

I installed all recommended Eclipse/Sming parts inclusive the Espressif SDK.
All functions are running well, also the examples are compilable.

Also I imported the komplete SmingFramework into my Workspace.

Now I got some Errors left over.
E.g. the String object will marked as Error, but is compilable.

Can anybody help me to set up my envirement.

Geetings from Hamburg
Pf@nne

![eclipse](https://cloud.githubusercontent.com/assets/7262813/14257424/06aed248-fa9e-11e5-8189-6a2327283dbc.PNG)

![eclipse1](https://cloud.githubusercontent.com/assets/7262813/14257878/2029cb36-faa0-11e5-9b63-f0a2093d99e2.PNG)

**Comment by cvgaviao** [comment]
I was getting same problems using eclipse cdt neon at a ubuntu machine.
but after applying the fix in the PR#679 the problem was resolved

**Comment by hreintke** [comment]
Issue solved.
