### ISSUE TITLE
SPIFFs/Filesystem issues/remarks

### ISSUE THREAD

**Issue by patrickjahns** [SmingHub/Sming#687]
I`ve noticed a couple of problems / annoyances / issues with the filesystem these days:

- if the file is bigger than free space, we can not recover properly (also see: pellepl/spiffs#82)
  
- there is currently no simple call in Filesystem to check/get the free space 
->this might be possible by creating a wrapper around `SPIFFS_info` (see: https://github.com/pellepl/spiffs/wiki/Using-spiffs#checking-filesystem)
  
- methods writing data to spiffs (HttpClient, FTPServer) will simply fail/cause resets when the file system is full or we try to write more data than is available

Edit:
There is also a newer spiffy Version - would be great to also update the included one

**Comment by raburton** [comment]
Try the newspiffs branch. Don't have the time to test it out on a real device, but integrated the new version and compile tested it at least.

**Comment by hreintke** [comment]
New Spiffs version will be integrated within SmingRTOS
