### ISSUE TITLE
Implement TCP keep-alive to keep TCP connection permanently on

### ISSUE THREAD

**Issue by helpme1** [SmingHub/Sming#688]
I am using SMING to implement a TCP client. The TCP client initiates the connection. I noticed that the TCP connection drops after some time. It would be desirable to implement the TCP keep-alive feature to keep the TCP connection permanently on.

**Comment by hreintke** [comment]
@helpme1 : 
The TCP protocol keepalive will protect against a firewall/router dropping the connection
I expect your Tcpconnection is dropped after a Sming defined time_out value.
You can update that using the setTimeout(value) function. Setting value to 0xFFFF will make it unlimited.

**Comment by helpme1** [comment]
Thank you for the answer.
