### ISSUE TITLE
error on apptest.cpp

### ISSUE THREAD

**Issue by cvgaviao** [SmingHub/Sming#724]
I can build Sming properly inside eclipse CDT using make, but there is a file with an error in the line 23. This is the line with error in apptest.cpp:
`	DynamicJsonBuffer jsonBuffer;
`
> The type 'ArduinoJson::Internals::BlockJsonBuffer' must implement the inherited pure virtual method 'ArduinoJson::JsonBuffer::alloc'

**Comment by hreintke** [comment]
@cvgaviao :
The apptest.cpp is an obsolete file from early testing of Sming framework.
The application examples are available in the samples direcory.

The apptest.cpp is already removed from SmingRTOS.

**Comment by cvgaviao** [comment]
@hreintke  should I remove and propose a PR or you already have done that ?

**Comment by hreintke** [comment]
@cvgaviao : 
Yes, please make a PR so this will be solved in SmingNONOS too.

**Comment by hreintke** [comment]
Issue resolved
