### ISSUE TITLE
Connect to multiple Access Points as Station

### ISSUE THREAD

**Issue by Thijs-Riezebeek** [SmingHub/Sming#738]
I have three ESP8266 devices. When I flash two of them having in WiFi mode softAP and one in Station mode, the device in Station mode will only connect with one of the devices in Access Point mode.

How can I make the device in Station mode connect with multiple Access Points?

**Comment by slaff** [comment]
@Thijs-Riezebeek I don't think this is possible out-of-the-box and is out of the scope of Sming. But I am pretty sure that it is possible to implement with some efforts.
