### ISSUE TITLE
HttpServer_WebSocket sample not working

### ISSUE THREAD

**Issue by johndoe8967** [SmingHub/Sming#744]
I had a short look at the HttpServer_WebSocket and there are at least 2 bugs with prevent from easy using
- Makefile-user.mk: spiffs is disabled 
- web folder: wrong index.html (is a copy bug from the AJAX sample)

**Comment by hreintke** [comment]
@johndoe8967 
Did a quick check and indeed not correctly.
If you can make a PR for both SmingNONOS and SmingRTOS I will merge.

**Comment by johndoe8967** [comment]
problem seems to be only in  SmingNONOS 
RTOS already uses spiffs

**Comment by slaff** [comment]
@johndoe8967 That issue should have been fixed in the latest source code. Feel free to reopen the ticket if the HttpServer_WebSocket is still not working for you.
