### ISSUE TITLE
 how can I use std :: string in my project

### ISSUE THREAD

**Issue by fernandomorse** [SmingHub/Sming#747]
Can anybody help me. instructions to include in SMING design , std :: string  (iostream)??

Thanks.

**Comment by hreintke** [comment]
There is no standard file available within Sming. 
AFAIK the iostream is based on filesystem

**Comment by fernandomorse** [comment]
Thanks. Close this topic.

**Comment by anakod** [comment]
Please use "String" class and spiffs functionality instead.
