### ISSUE TITLE
Using <cassert> doesn't work with Sming

### ISSUE THREAD

**Issue by cmarrin** [SmingHub/Sming#751]
I'm using assert() by including <cassert>. This causes an undefined reference to __assert_func. The replacement from Sming is in esp_systemapi.h. I want to use the standard include because my app is cross-platform (esp/mac). I've solved this problem by including the following snippet in my app.cpp file:

```
void __assert_func(const char *file, int line, const char *func, const char *what)
{
    SYSTEM_ERROR("Assertion failed: (%s), function %s, file %s, line %d", what, func, file, line);
    while (1) ;
}
```

but it seems like Sming should support this in the core

**Comment by slaff** [comment]
@cmarrin If you think that can help other developers please make a Pull Request and we will review it.
