### ISSUE TITLE
WifiStation isn't firing Event

### ISSUE THREAD

**Issue by gikvin** [SmingHub/Sming#756]
I have 2 event set on WifiStation connection and fail. First time it is firing one of them correctly but
after losing and then reconnecting to wifi, wifi station isn't firing connection event!

![image](https://cloud.githubusercontent.com/assets/16151647/16886207/e34e07ba-4ae3-11e6-9dc0-87591ec8f402.JPG)

and no event after reconnecting wifi.

**Comment by avr39-ripe** [comment]
how you set wifi events? do you use WifiEvents? if so what events do yo catch by you callback / delegate?  what do you mean lost connection? is wifi router turn off/on or how?

**Comment by gikvin** [comment]
I'm using this method
`WifiStation.waitConnection(connectOk, 30, connectFail);`
I'm not using WifiEvents.
If wifi router goes on and off i want my connectOk function to be called again.

**Comment by hreintke** [comment]
WifiStation.waitconnection is designed and implemented to fire only once.
if you need more control/information of Wifi status you should use WifiEvents.

**Comment by gikvin** [comment]
Thank you!
I think this issue needs to be closed.

**Comment by gikvin** [comment]
Meago,yw y
