### ISSUE TITLE
WebSocket Client

### ISSUE THREAD

**Issue by iNiSiRe** [SmingHub/Sming#766]
Sorry, I can't find it. PR is closed (https://github.com/SmingHub/Sming/pull/258), but no master, nor develop branch doesn't contains this feature and branch SmingHub:feature/websocket-client is missing. Where is it?

**Comment by slaff** [comment]
@iNiSiRe The websocket client is under development. You can follow the discussion from here: https://github.com/SmingHub/Sming/pull/795
