### ISSUE TITLE
Pass / retrieve data with GET requests

### ISSUE THREAD

**Issue by DominicMe** [SmingHub/Sming#767]
I can use the following code to execute a function when a specified URL is requested but unless I use a POST request I see no way to execute the function on variable GET URL's.

`server.addPath("/ajax", onAjax);`

Is it possible to pass variables with a GET request? Perhaps there is a wildcard that would allow specifying of variable URL's?

**Comment by slaff** [comment]
With the latest Http refactoring (#1112) that issue shouldn't be relevant any longer.
