### ISSUE TITLE
File read write Error

### ISSUE THREAD

**Issue by crosofg** [SmingHub/Sming#768]
I am getting error upon writing content to flash memory. 
Using this

```
AppSettings.ssid=SSID;
AppSettings.password=password;
AppSettings.save();
```

gives 

```
open errno -10004

write errno -10010
```

Any idea why does it occur? I have used spiff_mount() to load the spiff.

**Comment by slaff** [comment]
@crosofg Did you make sure that spiffs FS is generated and flashed on the device?

**Comment by slaff** [comment]
@crosofg Feel free to reopen the ticket is you have more information related to this issue.
