### ISSUE TITLE
equivalent function of  adc.readvdd33() in sming?

### ISSUE THREAD

**Issue by marqueeeeeee** [SmingHub/Sming#771]
for li-po battery level checking is there a readvdd function?  thank you!

**Comment by flexiti** [comment]
analogRead()

**Comment by marqueeeeeee** [comment]
no need to connect to adc? if i call analogRead() it will read the 3.3v vcc?

**Comment by flexiti** [comment]
This work in this way (see below), so use A0 as parametr and You can read vcc.
int vcc = analogRead(A0);

```
inline uint16_t analogRead(uint16_t pin)
{
	if (pin == A0)
		return system_adc_read();
	else
		return -1; // Not supported
}
```

**Comment by marqueeeeeee** [comment]
wow, thank you for this! 👍  will try it later this evening.

**Comment by slaff** [comment]
@marqueeeeeee Did the suggested solution work for you? If yes, please close the issue.
