### ISSUE TITLE
Spi Master/Slave Library

### ISSUE THREAD

**Issue by Matheus-Garbelini** [SmingHub/Sming#777]
Hello, Could it be possible to port SPI library so esp could work in master or slave mode?

**Comment by harry-boe** [comment]
The SPI implementation supports only master mode right now. 
Slave mode is a completely different story as you need to handle interrupts when traffic comes.
If you like to do it the espressif sdk (examples/peripherial_test) would provide a starting point.

What is the setup where you need slave mode?

**Comment by Matheus-Garbelini** [comment]
@harry-boe I need a simples setup like what esp8266 core SPISlave currently have:
https://github.com/esp8266/Arduino/tree/master/libraries/SPISlave

It trigger an interrupt Avery 32bytes (i guess). If im not mistaken, me-no-dev configure the spi using the DMA to handle the data transfer. Please, Look forward to this kind of implementation on sming as it would certainly increase sming Framework to work with other very fast systems. (Like raspberry-esp)
