### ISSUE TITLE
Delegate attachInterrupt

### ISSUE THREAD

**Issue by fernandomorse** [SmingHub/Sming#788]
I need an example for code: attachInterrupt (GPIO, interrupt CONFIG, LOW); using delegate.

**Comment by hreintke** [comment]
@fernandomorse : 
There is a basic_delegates example which shows the generic use of delegates.

Noticed that we missed the tyedef in the attachInterrupt,.

For attacheInterrupt it you can use would be like 
```
typedef Delegate<void()> InterruptDelegate;
class example 
{
 void interruptRoutine()
{...}
...
}
```
In the class code you can then use : 
```
attachInterrupt(GPIO,InterruptDelegate(&example::interruptRoutine,this),LOW) 

```

**Comment by fernandomorse** [comment]
Grateful, realized changes in interrupt.h. Working perfectly.

Please, close topic.
