### ISSUE TITLE
HttpServer causes WDT Reset

### ISSUE THREAD

**Issue by Deeenis** [SmingHub/Sming#797]
Followed the installation:
https://github.com/SmingHub/Sming/wiki/MacOS-Quickstart

Tried out this example:
https://github.com/SmingHub/Sming/blob/develop/samples/DNSCaptivePortal/app/application.cpp

Nothing happens, stripped down all code, and ended up with only:
`#include <user_config.h>
#include <SmingCore/SmingCore.h>

Timer procTimer;
HttpServer server;

void loop() {
	Serial.println("Hello world!");
}

void init()
{
	Serial.begin(115200);
	procTimer.initializeMs(1000, loop).start();
}`

HttpServer server; Makes the ESP write WDT reset:

`tail 4
chksum 0xf6
load 0x3ffe8000, len 884, room 4 
tail 0
chksum 0xb3
load 0x3ffe8378, len 4708, room 8 
tail 12
chksum 0xbb
csum 0xbb

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset`

ESP8266-12F, MacOS 10.11.2, newest pull of esptool, esptool2, Sming and the sdk described in the tutorial (esp_iot_sdk_v1.5.0).

**Comment by slaff** [comment]
@Deeenis I had the same issue as you. What you need to do is first erase the flash that you have:

```
esptool.py -p /dev/ttyUSB0 erase_flash
```

And then upload the new firmware. It should be working flawlessly. 
Feel free to reopen the ticket if you still have that issue.
