### ISSUE TITLE
"write to files hangs ESP8266-01 module" - SPIFFS version problem

### ISSUE THREAD

**Issue by kwis2** [SmingHub/Sming#815]
according to https://github.com/nodemcu/nodemcu-firmware/issues/1452 and follow, there was problem in SPIFFS - especially v 0.3.3 used by SMING. It was solved in current SPIFFS version 0.3.6. could you please update SPIFFS in current SMING

**Comment by slaff** [comment]
@kwis2 Can you test PR #816 and tell us if it is working for you?

**Comment by slaff** [comment]
@kwis2 Should be fixed in the latest version with this commit 19d977a6a1267e7429ddd9c9eedf6266149e3b48. Give it a try and tell us if it is working for you.

**Comment by kwis2** [comment]
with commit 19d977a program works from the first run :)))
thanx @slaff
