### ISSUE TITLE
X.509 and AWS IOT support

### ISSUE THREAD

**Issue by ZeevG** [SmingHub/Sming#822]
I noticed recently that ssl support for mqtt was added which is really cool. Is this compatible with the X.509 authentication protocol that AWS IOT uses? It seems quite similar, both public key systems, but AWS never actually refer to it as SSL.

**Comment by slaff** [comment]
[X.509](https://en.wikipedia.org/wiki/X.509) is important part of SSL that is related to the methodology used for trusting a certificate. And as such it is also part of the SSL that we have and that comes with axTLS.

**Comment by slaff** [comment]
@ZeevG Take a look at the sample in this PR: https://github.com/SmingHub/Sming/pull/2149.
