### ISSUE TITLE
We need logo for the project.

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#829]
We are looking for a logo for the project. If you have suggestions make sure to put them as comments to this issue.

**Comment by chall3ng3r** [comment]
My younger brother is professional logo designer. I'll ask him for few designs to select from. Will post here.

**Comment by DominicMe** [comment]
A while back I made a logo for [ESP8266 Sming Framework](http://dominicm.com/esp8266-sming-framework-arch-linux/) article as I couldn't find one. The low resolution logo used at a time and now seems to be taken from a railway company in Netherlands which is a bit bizarre :)

@anakod noticed the logo and suggested I post it here. I can send vector / psd original if you decide you want to use it.

**Comment by slaff** [comment]
@DominicMe Please, send the PSD as long as it does not infringe any copyright laws.

**Comment by anakod** [comment]
@DominicMe glad to see you on github. I'm personally like logo designed by you, and think it can be used as official Sming Framework logo.

**Comment by DominicMe** [comment]
Here is the AI vector file and high res png.

http://owncloud.dominicm.com/index.php/s/lUJ5ckZtyz1aPtt

![sming](https://cloud.githubusercontent.com/assets/2036768/22843269/9c76e4c8-efd0-11e6-89a8-f0f05f4c262e.png)

**Comment by anakod** [comment]
Big thanks @DominicMe !
