### ISSUE TITLE
Migrating from linux to windows

### ISSUE THREAD

**Issue by fernandomorse** [SmingHub/Sming#851]
I'm migrating from linux to windows platform. I have performed the procedures defined for installing Sming on windows. (sming v3.0)

In the procedure, Build Sming Library:
Cd c: \ tools \ sming \ Sming
Make all

following error:

SmingCore / HardwareSerial.cpp: In constructor 'HardwareSerial :: HardwareSerial (int)':
SmingCore / HardwareSerial.cpp: 32: 77: error: too few arguments to function 'void * pvPortMalloc (size_t, const char *, uint32)' serialQueue = (os_event_t *) os_malloc (sizeof (os_event_t) * SERIAL_QUEUE_LEN);
                                                                              ^
Include this file from c: \ tools \ sming \ sming \ include \ user_config.h: 29: 0,
                  From c: \ tools \ sming \ sming \ wiring \ wiringframeworkdependencies.h: 11,
                  From SmingCore /../ SmingCore / HardwareSerial.h: 11,
                  From SmingCore / HardwareSerial.cpp: 10: system / include / esp_systemapi.h: 70: 14: note: declared here
  Extern void * pvPortMalloc (size_t xWantedSize, const char * file, uint32 line);
               ^
Make: *** [out / build / SmingCore / HardwareSerial.o] Error 1

Any idea
Grateful.

**Comment by slaff** [comment]
@fernandomorse Seems to me like mixing SmingNONOS code with SmingRTOS code. Most probably the SMING_HOME env variable is set incorrectly. Feel free to reopen the ticket if there is something more that we can help here.
