### ISSUE TITLE
MQTT over TLS

### ISSUE THREAD

**Issue by TomaszKn** [SmingHub/Sming#857]
HI
Is possible connect to Mosquitto broker over TLS/SSL on 8883 port?
How convert ca.crt to cert.h?

**Comment by slaff** [comment]
> Is possible connect to Mosquitto broker over TLS/SSL on 8883 port?

@TomaszKn Yes, it is possible - take a look at the MqttClient_Hello ( https://github.com/SmingHub/Sming/blob/develop/samples/MqttClient_Hello/app/application.cpp ) sample.

> How convert ca.crt to cert.h?

Do you want to send client certificate?

**Comment by TomaszKn** [comment]
True.
I have origin/master where isn't SSL in MQTT, but after change to develop and rebuild all project when I'm flashing my ESP-01 or ESP-07, chip not start. 
It test on MQTT SSL and Basic_SSL

`Wrote 274432 bytes at 0x9000 in 23.8 seconds (92.3 kbit/s)...`
`Leaving...`
`python -m serial.tools.miniterm /dev/ttyUSB0 115200`
`--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---`
`--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---`
`380, len 12528, room 8 `
`tail 8`
`chksum 0x7c`
`csum 0x7c`
`csum err`
`ets_main.c Fatal exception (28): `
`epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000`
`Fatal exception (28): `
`epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000`
`Fatal exception (28):` 
`epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
`

**Comment by slaff** [comment]
It could be that the application is too big for ESP-01 with 512 KB flash. Can you try something for me: Erase your flash before saving the firmware on it.

```
./esptool.py --port /dev/ttyUSB0 erase_flash
```

If needed replace the port variable with your one.

After that flash the application.

**Comment by TomaszKn** [comment]
Couldn't boot again

**Comment by powo01** [comment]
At my ESP-01 the MqTT Client Example is working. The compiled binary is about 310kB
I have compiled in a cert and key in DER format but the output told my something is wrong

**Comment by slaff** [comment]
> ... but the output told me something is wrong

@powo01 can you paste the output to see details?

**Comment by slaff** [comment]
@TomaszKn Please, paste the output when you flash the ROMs on the device. Type `make flash V=1`.

**Comment by slaff** [comment]
Feel free to reopen if there is more information.
