### ISSUE TITLE
SPIFFS not mounted in example ScreenTFT_ILI9340-ILI9341

### ISSUE THREAD

**Issue by brunodymios** [SmingHub/Sming#860]
In the **ScreenTFT_ILI9340-ILI9341** example included in the samples directory, the SPIFFS is used to read a BMP file that will be shown on the display.
The code lacks of a **spiffs_mount();** instruction in the init() in order to be able to read files.

**Comment by slaff** [comment]
Can you send us PR with the needed changes?

**Comment by brunodymios** [comment]
@slaff sure, done.
Pull Request #865
