### ISSUE TITLE
What ESP8266 boards are compatible?

### ISSUE THREAD

**Issue by colombojrj** [SmingHub/Sming#866]
First of all, thanks do the project. It is very well documented! 

But, there are several ESP8266 boards, for example, 12E, 01, etc. What are compatible or tested?

Thanks!

**Comment by slaff** [comment]
@colombojrj Probably all ESPs with flash size >= 1MB will work. ESP-01 is having too little flash for most of the examples to work with the 1.5.x SDK.

Tested: I am using ESP-12E with 4MB flash for tests.

**Comment by colombojrj** [comment]
Thanks man!

**Comment by ADiea** [comment]
I used ESP 7 with 512K until recently now waiting for new hw based on 12E

**Comment by johndoe8967** [comment]
I ordered a bunch of 512k from china and they work great for my projects.
Of course I've to check size limitations and I can't use all features in one project.

**Comment by Ogyb** [comment]
i use ESP-7, ESP-02, ESP-201, ESP-07S (external antenna connector) for projects and ESP12 for testing.

**Comment by anakod** [comment]
All boards compatible with Sming :)
