### ISSUE TITLE
how to proceed after building the output

### ISSUE THREAD

**Issue by agauniyal** [SmingHub/Sming#867]
I've successfully built the program which creates a new directory `out` containing `build` and `firmware` directories with files inside them. How should I proceed forward assuming I've all tools installed and esp8266 device connected on `/dev/ttyUSB0`?

**Comment by agauniyal** [comment]
```
.
├── app
│   └── application.cpp
├── include
│   └── user_config.h
├── Makefile
├── Makefile-user.mk
└── out
    ├── build
    │   ├── app
    │   │   └── application.o
    │   ├── app_app.a
    │   └── app.out
    └── firmware
        ├── 0x00000.bin
        ├── 0x09000.bin
        ├── firmware.map
        └── fwMeminfo.new

6 directories, 11 files
```

**Comment by slaff** [comment]
`make flash` should be the next command.

Take a look at the wiki page: https://github.com/SmingHub/Sming/wiki/Linux-Quickstart#build-and-flash-a-basic-blink-example-using-ttyusb0
