### ISSUE TITLE
better dependency checks for make

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#895]
It would be great to have automatic dependency checking for all source files. I think that it should be possible (see http://make.mad-scientist.net/papers/advanced-auto-dependency-generation).

Also spiffs should be updated whenever a source files changes.

However, I'm not an expert for gnu make. Perhaps someone has done that before so it can be integrated into the standard makefiles?

**Comment by slaff** [comment]
@tius2000 feel free to reopen this ticket if there are more specific things/suggestions to improve our build process.
