### ISSUE TITLE
HardwareTimer and ESP8266_new_pwm seem to crash spiffs access

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#906]
Whenever _HardwareTimer_ or _ESP8266_new_pwm_ is active, spiffs (e. g. _HttpResponse::sendFile_) becomes instable on my system and leads to a reboot. Perhaps this is a symptom of a hardware conflict or an unsafe interrupt operation. Has anyone experienced the same problem?

If this is confirmed and the underlying cause cannot be solved, perhaps a safe guard around the spiffs calls with ETS_FRC1_INTR_DISABLE() should be implemented within Sming?

**Comment by slaff** [comment]
@tius2000 Please, ask also [spiffs](https://github.com/pellepl/spiffs/issues) and [ESP8266_new_pwm](https://github.com/StefanBruens/ESP8266_new_pwm/issues) communities.

**Comment by slaff** [comment]
@tius2000 Feel free to reopen the ticket once you have more information from one of the other projects.
