### ISSUE TITLE
Not flashing new code

### ISSUE THREAD

**Issue by dbelz** [SmingHub/Sming#937]
Hello Guys,

i have downloaded the Windows Setup over Chocolately and everything seems to be fine. I can run and build the samples and so on. So i have copied one example to another location to write my own code / project.

Before i flashed my own stuff i had the Basic Wifi Sample running on the Board. When i now flash my firmware over eclipse the build process and so on is running fine. But in the Serial Output i see the old messages which are produced by the Basic Wifi example.

How can i fix this? I just want to run my own code.

Kind Regards,
Daniel

**Comment by ADiea** [comment]
Please attach console output from the flashing step

**Comment by dbelz** [comment]
> 14:27:22 **** Build of configuration Sming for project Mesh ****
make all 
C+ app/application.cpp
AR out/build/app_app.a
LD out/build/app.out

#Memory / Section info:
------------------------------------------------------------------------------
   Section|                   Description| Start (hex)|   End (hex)|Used space
------------------------------------------------------------------------------
      data|        Initialized Data (RAM)|    3FFE8000|    3FFE8374|     884
    rodata|           ReadOnly Data (RAM)|    3FFE8378|    3FFE8DB8|    2624
       bss|      Uninitialized Data (RAM)|    3FFE8DB8|    3FFEF2E8|   25904
      text|            Cached Code (IRAM)|    40100000|    40105C0E|   23566
irom0_text|           Uncached Code (SPI)|    40209000|    402391AA|  197034
Total Used RAM : 29412
Free RAM : 52508
Free IRam : 9220
------------------------------------------------------------------------------
# Generating image...
Generate firmware images successully in folder out/firmware.
Done
# Generating spiffs_bin
Checking for spiffs files
No files found in ./files.
Creating empty out/firmware/spiff_rom.bin
Creating rom 'out/firmware/spiff_rom.bin' of size 0x30000 (196608) bytes.
Creating empty filesystem.
out/firmware/spiff_rom.bin---------->0x3C000

14:27:31 Build Finished (took 8s.733ms)

>

**Comment by slaff** [comment]
@dbelz But, have you run `make flash` to actually re-program your ESP8266 device?

**Comment by dbelz** [comment]
yes ofc i have done that. the flash:

`14:45:32 **** Build of configuration Sming for project Mesh ****
make flash 
Killing Terminal to free COM3
FEHLER: Der Prozess "Terminal.exe" wurde nicht gefunden.
/c/Espressif/utils/esptool.exe -p COM3 -b 115200 write_flash -ff 40m -fm dio -fs 4m 0x00000 out/firmware/0x00000.bin 0x09000 out/firmware/0x09000.bin 0x3C000 out/firmware/spiff_rom.bin
Connecting...
Erasing flash...
head: 7 ;total: 7
erase size : 16384

Writing at 0x00000000... (3 %) 
Writing at 0x00000400... (7 %) 
Writing at 0x00000800... (11 %) 
Writing at 0x00000c00... (14 %) 
Writing at 0x00001000... (18 %) 
Writing at 0x00001400... (22 %) 
Writing at 0x00001800... (25 %) 
Writing at 0x00001c00... (29 %) 
Writing at 0x00002000... (33 %) 
Writing at 0x00002400... (37 %) 
Writing at 0x00002800... (40 %) 
Writing at 0x00002c00... (44 %) 
Writing at 0x00003000... (48 %) 
Writing at 0x00003400... (51 %) 
Writing at 0x00003800... (55 %) 
Writing at 0x00003c00... (59 %) 
Writing at 0x00004000... (62 %) 
Writing at 0x00004400... (66 %) 
Writing at 0x00004800... (70 %) 
Writing at 0x00004c00... (74 %) 
Writing at 0x00005000... (77 %) 
Writing at 0x00005400... (81 %) 
Writing at 0x00005800... (85 %) 
Writing at 0x00005c00... (88 %) 
Writing at 0x00006000... (92 %) 
Writing at 0x00006400... (96 %) 
Writing at 0x00006800... (100 %) 
Written 27648 bytes in 2.70 seconds (81.80 kbit/s)...
Erasing flash...
head:  7 ;total: 49
erase size :  172032

Writing at 0x00009000... (0 %) 
Writing at 0x00009400... (1 %) 
Writing at 0x00009800... (1 %) 
Writing at 0x00009c00... (2 %) 
Writing at 0x0000a000... (2 %) 
Writing at 0x0000a400... (3 %) 
Writing at 0x0000a800... (3 %) 
Writing at 0x0000ac00... (4 %) 
Writing at 0x0000b000... (4 %) 
Writing at 0x0000b400... (5 %) 
Writing at 0x0000b800... (5 %) 
Writing at 0x0000bc00... (6 %) 
Writing at 0x0000c000... (6 %) 
Writing at 0x0000c400... (7 %) 
Writing at 0x0000c800... (7 %) 
Writing at 0x0000cc00... (8 %) 
Writing at 0x0000d000... (8 %) 
Writing at 0x0000d400... (9 %) 
Writing at 0x0000d800... (9 %) 
Writing at 0x0000dc00... (10 %) 
Writing at 0x0000e000... (10 %) 
Writing at 0x0000e400... (11 %) 
Writing at 0x0000e800... (11 %) 
Writing at 0x0000ec00... (12 %) 
Writing at 0x0000f000... (12 %) 
Writing at 0x0000f400... (13 %) 
Writing at 0x0000f800... (13 %) 
Writing at 0x0000fc00... (14 %) 
Writing at 0x00010000... (15 %) 
Writing at 0x00010400... (15 %) 
Writing at 0x00010800... (16 %) 
Writing at 0x00010c00... (16 %) 
Writing at 0x00011000... (17 %) 
Writing at 0x00011400... (17 %) 
Writing at 0x00011800... (18 %) 
Writing at 0x00011c00... (18 %) 
Writing at 0x00012000... (19 %) 
Writing at 0x00012400... (19 %) 
Writing at 0x00012800... (20 %) 
Writing at 0x00012c00... (20 %) 
Writing at 0x00013000... (21 %) 
Writing at 0x00013400... (21 %) 
Writing at 0x00013800... (22 %) 
Writing at 0x00013c00... (22 %) 
Writing at 0x00014000... (23 %) 
Writing at 0x00014400... (23 %) 
Writing at 0x00014800... (24 %) 
Writing at 0x00014c00... (24 %) 
Writing at 0x00015000... (25 %) 
Writing at 0x00015400... (25 %) 
Writing at 0x00015800... (26 %) 
Writing at 0x00015c00... (26 %) 
Writing at 0x00016000... (27 %) 
Writing at 0x00016400... (27 %) 
Writing at 0x00016800... (28 %) 
Writing at 0x00016c00... (29 %) 
Writing at 0x00017000... (29 %) 
Writing at 0x00017400... (30 %) 
Writing at 0x00017800... (30 %) 
Writing at 0x00017c00... (31 %) 
Writing at 0x00018000... (31 %) 
Writing at 0x00018400... (32 %) 
Writing at 0x00018800... (32 %) 
Writing at 0x00018c00... (33 %) 
Writing at 0x00019000... (33 %) 
Writing at 0x00019400... (34 %) 
Writing at 0x00019800... (34 %) 
Writing at 0x00019c00... (35 %) 
Writing at 0x0001a000... (35 %) 
Writing at 0x0001a400... (36 %) 
Writing at 0x0001a800... (36 %) 
Writing at 0x0001ac00... (37 %) 
Writing at 0x0001b000... (37 %) 
Writing at 0x0001b400... (38 %) 
Writing at 0x0001b800... (38 %) 
Writing at 0x0001bc00... (39 %) 
Writing at 0x0001c000... (39 %) 
Writing at 0x0001c400... (40 %) 
Writing at 0x0001c800... (40 %) 
Writing at 0x0001cc00... (41 %) 
Writing at 0x0001d000... (41 %) 
Writing at 0x0001d400... (42 %) 
Writing at 0x0001d800... (43 %) 
Writing at 0x0001dc00... (43 %) 
Writing at 0x0001e000... (44 %) 
Writing at 0x0001e400... (44 %) 
Writing at 0x0001e800... (45 %) 
Writing at 0x0001ec00... (45 %) 
Writing at 0x0001f000... (46 %) 
Writing at 0x0001f400... (46 %) 
Writing at 0x0001f800... (47 %) 
Writing at 0x0001fc00... (47 %) 
Writing at 0x00020000... (48 %) 
Writing at 0x00020400... (48 %) 
Writing at 0x00020800... (49 %) 
Writing at 0x00020c00... (49 %) 
Writing at 0x00021000... (50 %) 
Writing at 0x00021400... (50 %) 
Writing at 0x00021800... (51 %) 
Writing at 0x00021c00... (51 %) 
Writing at 0x00022000... (52 %) 
Writing at 0x00022400... (52 %) 
Writing at 0x00022800... (53 %) 
Writing at 0x00022c00... (53 %) 
Writing at 0x00023000... (54 %) 
Writing at 0x00023400... (54 %) 
Writing at 0x00023800... (55 %) 
Writing at 0x00023c00... (55 %) 
Writing at 0x00024000... (56 %) 
Writing at 0x00024400... (56 %) 
Writing at 0x00024800... (57 %) 
Writing at 0x00024c00... (58 %) 
Writing at 0x00025000... (58 %) 
Writing at 0x00025400... (59 %) 
Writing at 0x00025800... (59 %) 
Writing at 0x00025c00... (60 %) 
Writing at 0x00026000... (60 %) 
Writing at 0x00026400... (61 %) 
Writing at 0x00026800... (61 %) 
Writing at 0x00026c00... (62 %) 
Writing at 0x00027000... (62 %) 
Writing at 0x00027400... (63 %) 
Writing at 0x00027800... (63 %) 
Writing at 0x00027c00... (64 %) 
Writing at 0x00028000... (64 %) 
Writing at 0x00028400... (65 %) 
Writing at 0x00028800... (65 %) 
Writing at 0x00028c00... (66 %) 
Writing at 0x00029000... (66 %) 
Writing at 0x00029400... (67 %) 
Writing at 0x00029800... (67 %) 
Writing at 0x00029c00... (68 %) 
Writing at 0x0002a000... (68 %) 
Writing at 0x0002a400... (69 %) 
Writing at 0x0002a800... (69 %) 
Writing at 0x0002ac00... (70 %) 
Writing at 0x0002b000... (70 %) 
Writing at 0x0002b400... (71 %) 
Writing at 0x0002b800... (72 %) 
Writing at 0x0002bc00... (72 %) 
Writing at 0x0002c000... (73 %) 
Writing at 0x0002c400... (73 %) 
Writing at 0x0002c800... (74 %) 
Writing at 0x0002cc00... (74 %) 
Writing at 0x0002d000... (75 %) 
Writing at 0x0002d400... (75 %) 
Writing at 0x0002d800... (76 %) 
Writing at 0x0002dc00... (76 %) 
Writing at 0x0002e000... (77 %) 
Writing at 0x0002e400... (77 %) 
Writing at 0x0002e800... (78 %) 
Writing at 0x0002ec00... (78 %) 
Writing at 0x0002f000... (79 %) 
Writing at 0x0002f400... (79 %) 
Writing at 0x0002f800... (80 %) 
Writing at 0x0002fc00... (80 %) 
Writing at 0x00030000... (81 %) 
Writing at 0x00030400... (81 %) 
Writing at 0x00030800... (82 %) 
Writing at 0x00030c00... (82 %) 
Writing at 0x00031000... (83 %) 
Writing at 0x00031400... (83 %) 
Writing at 0x00031800... (84 %) 
Writing at 0x00031c00... (84 %) 
Writing at 0x00032000... (85 %) 
Writing at 0x00032400... (86 %) 
Writing at 0x00032800... (86 %) 
Writing at 0x00032c00... (87 %) 
Writing at 0x00033000... (87 %) 
Writing at 0x00033400... (88 %) 
Writing at 0x00033800... (88 %) 
Writing at 0x00033c00... (89 %) 
Writing at 0x00034000... (89 %) 
Writing at 0x00034400... (90 %) 
Writing at 0x00034800... (90 %) 
Writing at 0x00034c00... (91 %) 
Writing at 0x00035000... (91 %) 
Writing at 0x00035400... (92 %) 
Writing at 0x00035800... (92 %) 
Writing at 0x00035c00... (93 %) 
Writing at 0x00036000... (93 %) 
Writing at 0x00036400... (94 %) 
Writing at 0x00036800... (94 %) 
Writing at 0x00036c00... (95 %) 
Writing at 0x00037000... (95 %) 
Writing at 0x00037400... (96 %) 
Writing at 0x00037800... (96 %) 
Writing at 0x00037c00... (97 %) 
Writing at 0x00038000... (97 %) 
Writing at 0x00038400... (98 %) 
Writing at 0x00038800... (98 %) 
Writing at 0x00038c00... (99 %) 
Writing at 0x00039000... (100 %) 
Written 197632 bytes in 19.38 seconds (81.59 kbit/s)...
Erasing flash...
head:  4 ;total: 48
erase size :  180224

Writing at 0x0003c000... (0 %) 
Writing at 0x0003c400... (1 %) 
Writing at 0x0003c800... (1 %) 
Writing at 0x0003cc00... (2 %) 
Writing at 0x0003d000... (2 %) 
Writing at 0x0003d400... (3 %) 
Writing at 0x0003d800... (3 %) 
Writing at 0x0003dc00... (4 %) 
Writing at 0x0003e000... (4 %) 
Writing at 0x0003e400... (5 %) 
Writing at 0x0003e800... (5 %) 
Writing at 0x0003ec00... (6 %) 
Writing at 0x0003f000... (6 %) 
Writing at 0x0003f400... (7 %) 
Writing at 0x0003f800... (7 %) 
Writing at 0x0003fc00... (8 %) 
Writing at 0x00040000... (8 %) 
Writing at 0x00040400... (9 %) 
Writing at 0x00040800... (9 %) 
Writing at 0x00040c00... (10 %) 
Writing at 0x00041000... (10 %) 
Writing at 0x00041400... (11 %) 
Writing at 0x00041800... (11 %) 
Writing at 0x00041c00... (12 %) 
Writing at 0x00042000... (13 %) 
Writing at 0x00042400... (13 %) 
Writing at 0x00042800... (14 %) 
Writing at 0x00042c00... (14 %) 
Writing at 0x00043000... (15 %) 
Writing at 0x00043400... (15 %) 
Writing at 0x00043800... (16 %) 
Writing at 0x00043c00... (16 %) 
Writing at 0x00044000... (17 %) 
Writing at 0x00044400... (17 %) 
Writing at 0x00044800... (18 %) 
Writing at 0x00044c00... (18 %) 
Writing at 0x00045000... (19 %) 
Writing at 0x00045400... (19 %) 
Writing at 0x00045800... (20 %) 
Writing at 0x00045c00... (20 %) 
Writing at 0x00046000... (21 %) 
Writing at 0x00046400... (21 %) 
Writing at 0x00046800... (22 %) 
Writing at 0x00046c00... (22 %) 
Writing at 0x00047000... (23 %) 
Writing at 0x00047400... (23 %) 
Writing at 0x00047800... (24 %) 
Writing at 0x00047c00... (25 %) 
Writing at 0x00048000... (25 %) 
Writing at 0x00048400... (26 %) 
Writing at 0x00048800... (26 %) 
Writing at 0x00048c00... (27 %) 
Writing at 0x00049000... (27 %) 
Writing at 0x00049400... (28 %) 
Writing at 0x00049800... (28 %) 
Writing at 0x00049c00... (29 %) 
Writing at 0x0004a000... (29 %) 
Writing at 0x0004a400... (30 %) 
Writing at 0x0004a800... (30 %) 
Writing at 0x0004ac00... (31 %) 
Writing at 0x0004b000... (31 %) 
Writing at 0x0004b400... (32 %) 
Writing at 0x0004b800... (32 %) 
Writing at 0x0004bc00... (33 %) 
Writing at 0x0004c000... (33 %) 
Writing at 0x0004c400... (34 %) 
Writing at 0x0004c800... (34 %) 
Writing at 0x0004cc00... (35 %) 
Writing at 0x0004d000... (35 %) 
Writing at 0x0004d400... (36 %) 
Writing at 0x0004d800... (36 %) 
Writing at 0x0004dc00... (37 %) 
Writing at 0x0004e000... (38 %) 
Writing at 0x0004e400... (38 %) 
Writing at 0x0004e800... (39 %) 
Writing at 0x0004ec00... (39 %) 
Writing at 0x0004f000... (40 %) 
Writing at 0x0004f400... (40 %) 
Writing at 0x0004f800... (41 %) 
Writing at 0x0004fc00... (41 %) 
Writing at 0x00050000... (42 %) 
Writing at 0x00050400... (42 %) 
Writing at 0x00050800... (43 %) 
Writing at 0x00050c00... (43 %) 
Writing at 0x00051000... (44 %) 
Writing at 0x00051400... (44 %) 
Writing at 0x00051800... (45 %) 
Writing at 0x00051c00... (45 %) 
Writing at 0x00052000... (46 %) 
Writing at 0x00052400... (46 %) 
Writing at 0x00052800... (47 %) 
Writing at 0x00052c00... (47 %) 
Writing at 0x00053000... (48 %) 
Writing at 0x00053400... (48 %) 
Writing at 0x00053800... (49 %) 
Writing at 0x00053c00... (50 %) 
Writing at 0x00054000... (50 %) 
Writing at 0x00054400... (51 %) 
Writing at 0x00054800... (51 %) 
Writing at 0x00054c00... (52 %) 
Writing at 0x00055000... (52 %) 
Writing at 0x00055400... (53 %) 
Writing at 0x00055800... (53 %) 
Writing at 0x00055c00... (54 %) 
Writing at 0x00056000... (54 %) 
Writing at 0x00056400... (55 %) 
Writing at 0x00056800... (55 %) 
Writing at 0x00056c00... (56 %) 
Writing at 0x00057000... (56 %) 
Writing at 0x00057400... (57 %) 
Writing at 0x00057800... (57 %) 
Writing at 0x00057c00... (58 %) 
Writing at 0x00058000... (58 %) 
Writing at 0x00058400... (59 %) 
Writing at 0x00058800... (59 %) 
Writing at 0x00058c00... (60 %) 
Writing at 0x00059000... (60 %) 
Writing at 0x00059400... (61 %) 
Writing at 0x00059800... (61 %) 
Writing at 0x00059c00... (62 %) 
Writing at 0x0005a000... (63 %) 
Writing at 0x0005a400... (63 %) 
Writing at 0x0005a800... (64 %) 
Writing at 0x0005ac00... (64 %) 
Writing at 0x0005b000... (65 %) 
Writing at 0x0005b400... (65 %) 
Writing at 0x0005b800... (66 %) 
Writing at 0x0005bc00... (66 %) 
Writing at 0x0005c000... (67 %) 
Writing at 0x0005c400... (67 %) 
Writing at 0x0005c800... (68 %) 
Writing at 0x0005cc00... (68 %) 
Writing at 0x0005d000... (69 %) 
Writing at 0x0005d400... (69 %) 
Writing at 0x0005d800... (70 %) 
Writing at 0x0005dc00... (70 %) 
Writing at 0x0005e000... (71 %) 
Writing at 0x0005e400... (71 %) 
Writing at 0x0005e800... (72 %) 
Writing at 0x0005ec00... (72 %) 
Writing at 0x0005f000... (73 %) 
Writing at 0x0005f400... (73 %) 
Writing at 0x0005f800... (74 %) 
Writing at 0x0005fc00... (75 %) 
Writing at 0x00060000... (75 %) 
Writing at 0x00060400... (76 %) 
Writing at 0x00060800... (76 %) 
Writing at 0x00060c00... (77 %) 
Writing at 0x00061000... (77 %) 
Writing at 0x00061400... (78 %) 
Writing at 0x00061800... (78 %) 
Writing at 0x00061c00... (79 %) 
Writing at 0x00062000... (79 %) 
Writing at 0x00062400... (80 %) 
Writing at 0x00062800... (80 %) 
Writing at 0x00062c00... (81 %) 
Writing at 0x00063000... (81 %) 
Writing at 0x00063400... (82 %) 
Writing at 0x00063800... (82 %) 
Writing at 0x00063c00... (83 %) 
Writing at 0x00064000... (83 %) 
Writing at 0x00064400... (84 %) 
Writing at 0x00064800... (84 %) 
Writing at 0x00064c00... (85 %) 
Writing at 0x00065000... (85 %) 
Writing at 0x00065400... (86 %) 
Writing at 0x00065800... (86 %) 
Writing at 0x00065c00... (87 %) 
Writing at 0x00066000... (88 %) 
Writing at 0x00066400... (88 %) 
Writing at 0x00066800... (89 %) 
Writing at 0x00066c00... (89 %) 
Writing at 0x00067000... (90 %) 
Writing at 0x00067400... (90 %) 
Writing at 0x00067800... (91 %) 
Writing at 0x00067c00... (91 %) 
Writing at 0x00068000... (92 %) 
Writing at 0x00068400... (92 %) 
Writing at 0x00068800... (93 %) 
Writing at 0x00068c00... (93 %) 
Writing at 0x00069000... (94 %) 
Writing at 0x00069400... (94 %) 
Writing at 0x00069800... (95 %) 
Writing at 0x00069c00... (95 %) 
Writing at 0x0006a000... (96 %) 
Writing at 0x0006a400... (96 %) 
Writing at 0x0006a800... (97 %) 
Writing at 0x0006ac00... (97 %) 
Writing at 0x0006b000... (98 %) 
Writing at 0x0006b400... (98 %) 
Writing at 0x0006b800... (99 %) 
Writing at 0x0006bc00... (100 %) 
Written 196608 bytes in 18.60 seconds (84.57 kbit/s)...

Leaving...
/c/Espressif/utils/Terminal.exe COM3 115200`

My Code is this(very simple stuff):
`#include <user_config.h>
#include <SmingCore/SmingCore.h>

void listNetworks(bool succeeded, BssList list)
{
	if (!succeeded)
	{
		Serial.println("Failed to scan networks");
		return;
	}

	int meshNetworkNodes = 0;

	for (int i = 0; i < list.count(); i++)
	{
		Serial.print("\tWiFi: ");
		Serial.print(list[i].ssid);
		Serial.print(", ");
		Serial.print(list[i].getAuthorizationMethodName());
		if (list[i].hidden) Serial.print(" (hidden)");
		Serial.println();

		if(list[i].ssid.startsWith("ESP-MESH-")) {
			meshNetworkNodes++;
		}
	}

	Serial.print(meshNetworkNodes);
}

void init()
{
	Serial.begin(SERIAL_BAUD_RATE);

	WifiStation.startScan(listNetworks);
}`

But when the Serial Terminal is open it prints a list of the wifis, reconnect try message, scandone message and so on(old things from the Basic Wifi Example)

**Comment by slaff** [comment]
> But when the Serial Terminal is open it prints a list of the wifis, reconnect try message, scandone message and so on

Hm, I am getting the feeling that you are seeing the system messages. Can you paste them here?

**Comment by dbelz** [comment]
`scandone
List of Wifis here
0scan completed: 17 found
reconnect
f r0, scandone
no PleaseEnterSSID found, reconnect after 1 s
reconnect`

**Comment by slaff** [comment]
So my bold guess is that your new code is actually flashed. What you see are system messages. You can try to add the following lines to your program

```
void init()
{
Serial.begin(SERIAL_BAUD_RATE);
Serial.systemDebugOutput(false); // this will disable printing of the system messages

Serial.printf("Great NEW Firmware\n");

// Notice: The next code line below probably will not work if you haven't enabled station mode before that 
//             To fix this uncomment the line below:
//  WifiStation.enable(true);             
WifiStation.startScan(listNetworks);
}`
```

**Comment by dbelz** [comment]
It works now! 

Im just starting with this stuff so sorry for the many questions^^
