### ISSUE TITLE
Basic AirUpdate, Basic rBoot firmware download failing

### ISSUE THREAD

**Issue by STwilight** [SmingHub/Sming#954]
Hi, dear community!

I'm trying to get success with Sming's Basic AirUpdate and Basic rBoot samples.
Module is booting OK, but when I'm trying to execute FW downloading from server, on all servers (local XAMPP or remote, specified in AirUpdate example) I'm getting the same error: "failed to download software".

Files, that must be downloaded, are located at their places, are accessible and freely can be downloaded with browser.

I'm changing only SSID/Password/URL values and getting no any errors or warnings due compilation.

I'm using Win10, Sming 3.0.1, UDK 2.0.9 by Cherts, ESP-12 with 1Mb (8Mbit) of flash.

Please, help. Thanks.

**Comment by slaff** [comment]
Test with the latest Sming version and feel free to reopen this issue if the problem persists.
