### ISSUE TITLE
v3.1.1 Hotfix Windows install

### ISSUE THREAD

**Issue by kwis2** [SmingHub/Sming#962]
with mingw32 compiled succesfully but a lot of warnings (compile succes messages skiped), messages are only with first compile - after `make clean` next `mak`e without problem

> C:\tools\sming\Sming>make
> In file included from include/lwip/stats.h:37:0,
>                  from lwip/core/dhcp.c:73:
> lwip/core/dhcp.c: In function 'dhcp_cleanup':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> lwip/core/dhcp.c:629:5: note: in expansion of macro 'mem_free'
>      mem_free(netif->dhcp);
>      ^
> lwip/core/dhcp.c: In function 'dhcp_start':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> lwip/core/dhcp.c:673:27: note: in expansion of macro 'mem_malloc'
>      dhcp = (struct dhcp *)mem_malloc(sizeof(struct dhcp));
>                            ^
> lwip/core/dhcp.c: In function 'dhcp_bind':
> lwip/core/dhcp.c:1059:3: warning: implicit declaration of function 'system_stati
> on_got_ip_set' [-Wimplicit-function-declaration]
>    system_station_got_ip_set(&ip, &mask, &gw);
>    ^
> In file included from lwip/core/dns.c:80:0:
> lwip/core/dns.c: In function 'dns_recv':
> include/lwip/mem.h:67:28: warning: implicit declaration of function 'pvPortZallo
> c' [-Wimplicit-function-declaration]
>  #define mem_zalloc(s)      pvPortZalloc(s, "", 0)
>                             ^
> include/lwip/mem.h:99:22: note: in expansion of macro 'mem_zalloc'
>  #define os_zalloc(s) mem_zalloc((s))
>                       ^
> lwip/core/dns.c:746:38: note: in expansion of macro 'os_zalloc'
>    u8_t* dns_payload_buffer = (u8_t* )os_zalloc(LWIP_MEM_ALIGN_BUFFER(DNS_MSG_SI
> ZE));
>                                       ^
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/mem.h:102:20: note: in expansion of macro 'mem_free'
>  #define os_free(p) mem_free((p))
>                     ^
> lwip/core/dns.c:856:3: note: in expansion of macro 'os_free'
>    os_free(dns_payload_buffer);
>    ^
> In file included from include/lwip/stats.h:37:0,
>                  from lwip/core/pbuf.c:66:
> lwip/core/pbuf.c: In function 'pbuf_alloc':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/pbuf.c:297:24: note: in expansion of macro 'memp_malloc'
>      p = (struct pbuf *)memp_malloc(MEMP_PBUF_POOL);
>                         ^
> lwip/core/pbuf.c: In function 'pbuf_free':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/pbuf.c:742:9: note: in expansion of macro 'memp_free'
>          memp_free(MEMP_PBUF_POOL, p);
>          ^
> In file included from include/lwip/memp.h:84:0,
>                  from lwip/core/raw.c:46:
> lwip/core/raw.c: In function 'raw_remove':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/raw.c:325:3: note: in expansion of macro 'memp_free'
>    memp_free(MEMP_RAW_PCB, pcb);
>    ^
> lwip/core/raw.c: In function 'raw_new':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/raw.c:345:27: note: in expansion of macro 'memp_malloc'
>    pcb = (struct raw_pcb *)memp_malloc(MEMP_RAW_PCB);
>                            ^
> In file included from lwip/core/tcp.c:48:0:
> lwip/core/tcp.c: In function 'tcp_close_shutdown':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/tcp.c:192:5: note: in expansion of macro 'memp_free'
>      memp_free(MEMP_TCP_PCB, pcb);//´¬Ż´¬ŻMEMP_TCP_PCB´¬Ż-+´¬Ż´¬Ż´¬ŻŔÂĘ´¬Ż=Ě+Á´¬
> Ż´¬Ż´¬Żpcb´¬Ż´¬ŻËŽ´¬Ż¦Á´¬Żď¬ÍÁ,´¬Ż=Ě´¬Ż´¬Ż-+´¬Ż
>      ^
> lwip/core/tcp.c: In function 'tcp_listen_with_backlog':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/tcp.c:530:35: note: in expansion of macro 'memp_malloc'
>    lpcb = (struct tcp_pcb_listen *)memp_malloc(MEMP_TCP_PCB_LISTEN);//´¬Ż´¬Ż´¬Ż´
> ¬Ż´¬Ż-+´¬Żě¬Ň-´¬Ż
>                                    ^
> lwip/core/tcp.c: In function 'tcp_slowtmr':
> lwip/core/tcp.c:813:33: warning: implicit declaration of function 'system_get_da
> ta_of_array_8' [-Wimplicit-function-declaration]
>          if (pcb->persist_cnt >= system_get_data_of_array_8(tcp_persist_backoff,
>  pcb->persist_backoff-1)) {
>                                  ^
> In file included from include/lwip/tcp.h:40:0,
>                  from include/lwip/tcp_impl.h:39,
>                  from lwip/core/tcp_in.c:48:
> lwip/core/tcp_in.c: In function 'tcp_input':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/tcp_in.c:351:9: note: in expansion of macro 'memp_free'
>          memp_free(MEMP_TCP_PCB, pcb);
>          ^
> In file included from include/lwip/tcp.h:40:0,
>                  from include/lwip/tcp_impl.h:39,
>                  from lwip/core/tcp_out.c:45:
> lwip/core/tcp_out.c: In function 'tcp_create_segment':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/tcp_out.c:166:32: note: in expansion of macro 'memp_malloc'
>    if ((seg = (struct tcp_seg *)memp_malloc(MEMP_TCP_SEG)) == NULL) {
>                                 ^
> In file included from include/lwip/tcp.h:40:0,
>                  from include/lwip/tcp_impl.h:39,
>                  from lwip/core/timers.c:45:
> lwip/core/timers.c: In function 'sys_timeout':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/timers.c:296:33: note: in expansion of macro 'memp_malloc'
>    timeout = (struct sys_timeo *)memp_malloc(MEMP_SYS_TIMEOUT);
>                                  ^
> lwip/core/timers.c: In function 'sys_untimeout':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/timers.c:367:7: note: in expansion of macro 'memp_free'
>        memp_free(MEMP_SYS_TIMEOUT, t);
>        ^
> In file included from include/lwip/memp.h:84:0,
>                  from lwip/core/udp.c:55:
> lwip/core/udp.c: In function 'udp_remove':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/udp.c:929:3: note: in expansion of macro 'memp_free'
>    memp_free(MEMP_UDP_PCB, pcb);
>    ^
> lwip/core/udp.c: In function 'udp_new':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/udp.c:944:27: note: in expansion of macro 'memp_malloc'
>    pcb = (struct udp_pcb *)memp_malloc(MEMP_UDP_PCB);
>                            ^
> In file included from lwip/core/ipv4/igmp.c:87:0:
> lwip/core/ipv4/igmp.c: In function 'igmp_stop':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/core/ipv4/igmp.c:255:7: note: in expansion of macro 'memp_free'
>        memp_free(MEMP_IGMP_GROUP, group);
>        ^
> lwip/core/ipv4/igmp.c: In function 'igmp_lookup_group':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/core/ipv4/igmp.c:333:32: note: in expansion of macro 'memp_malloc'
>    group = (struct igmp_group *)memp_malloc(MEMP_IGMP_GROUP);
>                                 ^
> lwip/core/ipv4/ip_addr.c: In function 'ipaddr_aton':
> lwip/core/ipv4/ip_addr.c:170:10: warning: implicit declaration of function 'isdi
> git' [-Wimplicit-function-declaration]
>      if (!isdigit(c))
>           ^
> In file included from include/lwip/stats.h:37:0,
>                  from lwip/netif/etharp.c:53:
> lwip/netif/etharp.c: In function 'free_etharp_q':
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/memp.h:88:31: note: in expansion of macro 'mem_free'
>  #define memp_free(type, mem)  mem_free(mem)
>                                ^
> lwip/netif/etharp.c:165:5: note: in expansion of macro 'memp_free'
>      memp_free(MEMP_ARP_QUEUE, r);
>      ^
> lwip/netif/etharp.c: In function 'etharp_query':
> include/lwip/mem.h:58:23: warning: implicit declaration of function 'pvPortMallo
> c' [-Wimplicit-function-declaration]
>  #define mem_malloc(s) pvPortMalloc(s, "", 0)
>                        ^
> include/lwip/memp.h:87:31: note: in expansion of macro 'mem_malloc'
>  #define memp_malloc(type)     mem_malloc(memp_sizes[type])
>                                ^
> lwip/netif/etharp.c:1139:44: note: in expansion of macro 'memp_malloc'
>        new_entry = (struct etharp_q_entry *)memp_malloc(MEMP_ARP_QUEUE);
>                                             ^
> In file included from lwip/app/dhcpserver.c:5:0:
> lwip/app/dhcpserver.c: In function 'parse_msg':
> include/lwip/mem.h:67:28: warning: implicit declaration of function 'pvPortZallo
> c' [-Wimplicit-function-declaration]
>  #define mem_zalloc(s)      pvPortZalloc(s, "", 0)
>                             ^
> include/lwip/mem.h:99:22: note: in expansion of macro 'mem_zalloc'
>  #define os_zalloc(s) mem_zalloc((s))
>                       ^
> lwip/app/dhcpserver.c:662:46: note: in expansion of macro 'os_zalloc'
>            pdhcps_pool = (struct dhcps_pool *)os_zalloc(sizeof(struct dhcps_pool
> ));
>                                               ^
> include/lwip/mem.h:55:21: warning: implicit declaration of function 'vPortFree'
> [-Wimplicit-function-declaration]
>  #define mem_free(s) vPortFree(s, "", 0)
>                      ^
> include/lwip/mem.h:102:20: note: in expansion of macro 'mem_free'
>  #define os_free(p) mem_free((p))
>                     ^
> lwip/app/dhcpserver.c:684:15: note: in expansion of macro 'os_free'
>                os_free(pnode);
>                ^
> lwip/app/dhcpserver.c:712:11: warning: implicit declaration of function 'wifi_so
> ftap_set_station_info' [-Wimplicit-function-declaration]
>        if (wifi_softap_set_station_info(m->chaddr, &client_address) == false) {
>            ^
>

**Comment by slaff** [comment]
Yes, that is normal. The code compiles ok and later on we can take care to suppress the warnings.
