### ISSUE TITLE
Discussion: Drop support for espressif bootloader?

### ISSUE THREAD

**Issue by tius2000** [SmingHub/Sming#971]
Are there any advantages of the espressif bootloader? Would it make sense to to support rboot only to simplify the framework?

**Comment by slaff** [comment]
If no one really insists on supporting Espressif's bootloader we can go even further:
* If bootloaded is needed then only rBoot will be used
* We can offer also images without bootloader, thus freeing space on Flash and memory.

**Comment by ADiea** [comment]
+1 to drop support (lathough not used rboot yet, ut if you force me...i'll have to learn :) )

**Comment by slaff** [comment]
Moving to only one bootloader, namely the superb rBoot, will help us get rid of:
- [ ] Different LD scripts
- [ ] Different project makefiles
- [ ] Different HttpFirmwareUpdate classes

Adding applications without bootloader, where no OTA or ROM switching is required, will
- [ ] Increase the amount of free space and heap available to the application
 

So I can see a lot of advantages for the code quality and for the users of Sming.

**Is anyone here using the Espressif Bootloader to do Over-The-Air (OTA) firmware updates?**

**Comment by avr39-ripe** [comment]
+1 to drop original bootloader
+1 to all @slaff remarks

**Comment by slaff** [comment]
> Drop support for espressif bootloader

@anakod @piperpilot @raburton What is your opinion on this?

**Comment by tius2000** [comment]
@slaff: great - also the option of having no bootloader at all!

**Comment by raburton** [comment]
I don't think I realised we supported the espressif bootloader anyway, or if I did I'd forgotten. In what way is it currently supported?

**Comment by piperpilot** [comment]
I use only rboot...I tried the espressif bootloader and it sucked.  I +1 the switch to rboot or nothing.

**Comment by rosiste** [comment]
+1 to drop original bootloader

**Comment by slaff** [comment]
Ok, starting from version 3.2.0 (#977) we will drop support for Espressif's boolader and use only rBoot as bootloader. Plus, hopefully, add support for standalone applications.

Any final thoughts before we close the discussion?

**Comment by tius2000** [comment]
I recently started to create completely refactored makefile for rboot-only projects with many additions (address calculation, automatic linker script creation, dependency detection etc.). However, it is still work in progress. It has a different name, so there are no collisions with the current makefiles. 

Should I create a PR for that when it is finished?

**Comment by slaff** [comment]
> Should I create a PR for that when it is finished?

Yes, please.

**Comment by anakod** [comment]
We should drop support for old non-actual things, and moreover, we should drop support for my original OTA updater (and than remove Basic_AirUpdate example), because rboot is better and cover all cases.

**Comment by tius2000** [comment]
I submitted my refactored makefile as requested #985. However, this is still work in progress, all comments are welcome!

**Comment by riban-bw** [comment]
I fully support (+1) making rBoot our only second stage boot loader but please add support for standalone (no second stage boot loader) before dropping support for Espressif second stage boot loader. I am unable to get rBoot and SPIFFS working together (#1009) and we should have a method of creating images without rBoot, just in case of similar issues.
