### ISSUE TITLE
Feature-Request: HTTPS support in HttpClient

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#99]
It looks like the HttpClient supports only http.

```CPP
bool HttpClient::startDownload(URL uri, HttpClientMode mode, HttpClientCompletedCallback onCompleted)
{
	//...
	if (uri.Protocol != "http") return false;
```
It would be very helpful to have also HTTPS support.

**Comment by anakod** [comment]
I think it should be switchable option, because HTTPS is very expensive in memory usage

**Comment by antelder** [comment]
+1 to https. all over the net people are looking for https support, would be a killer feature for sming. I just need a single https post to get an auth token...

**Comment by tprochazka** [comment]
I saw that current Espressif SDK already has direct support for HTTPS

**Comment by anakod** [comment]
Looks like SDK doesn't have correct HTTPS verification: http://www.esp8266.com/viewtopic.php?f=6&t=3343&p=19188&hilit=sha1#p19188

**Comment by robotiko** [comment]
Maybe this can be an starting point:
and ESP project that implements https 
https://github.com/SuperHouse/esp-open-rtos

ported lib 
 https://github.com/SuperHouse/axtls as a submodule optimized for low memory devices.

**Comment by slaff** [comment]
The Arduino/ESP project already has HTTPS support ( https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/WiFiClientSecure.cpp ). May be someone with good C/C++ skills can port this code to Sming?

**Comment by harry-boe** [comment]
bump for this issue.
 I guess we can close this with the new SSL implementation #596

**Comment by ADiea** [comment]
Hi but does the http client open a HTTP conn or a HTTPS connection to the server based on the protocol part in the URL? Sorry diodn't have time to test the new SSL implementation
