### ISSUE TITLE
Unify style for delegate class names

### ISSUE THREAD

**Issue by zgoda** [SmingHub/Sming#994]
I just found out that there are 2 styles (maybe more?, I just started learning Sming) used to format delegate class names, there is eg. `ConnectionDelegate` and `onStationDisconnectDelegate`. I think it would be better to maintain consistent coding style across framework.

**Comment by anakod** [comment]
That's right. Delegates as all other classes should be named from capital letter, without any prefixes.

**Comment by zgoda** [comment]
I found prefixed in `WifiEvents.h` and starting with small letter in `rBootHttpUpdate.h`. I'm working on PR with this.

**Comment by zgoda** [comment]
PR #1042 is under review, closing this issue.
